### ISSUE TITLE
Missing font

### ISSUE THREAD

**Issue by Lurgrid** [Jas-SinghFSU/HyprPanel#1]
Hello,

I found your project really incredible so I installed it on my computer using Arch & Hyprland but I'm missing some fonts because the icons are buggy, do you know what fonts I need?

![image](https://github.com/user-attachments/assets/1ab03b34-7d60-4f69-b243-1d37737e3fdd)

**Comment by Jas-SinghFSU** [comment]
Yes, you need to install NerdFonts for those icons to work. I'll update the Readme.

**Comment by Lurgrid** [comment]
Thank you very much, it works perfectly now!

**Comment by bloodhori** [comment]
I'm sorry somethin is unclear for me: there are a million nerd-fonts, which one?

**Comment by Jas-SinghFSU** [comment]
@bloodhori The 2 that I like are Ubuntu Mono and JetBrains Mono. But you can pick any one that you like. They all contain the icons you need.
