### ISSUE TITLE
Can matugen work without setting the wallpaper and just taking the colors from the picture chosen ?

### ISSUE THREAD

**Issue by rishav12s** [Jas-SinghFSU/HyprPanel#102]
I am using a script to dynamically select images from a folder as wallpaper using swww 

it would be better if there is an option when selecting the wallpaper in the bar settings only takes the color from it and not directly setting it as wallpaper

maybe setting a link to the current wall (that changes when ever time i change the wall)  and setting the link as the wallpaper so that it changes the color but doesnt set the link as the wall

i tried this and swww got messed up coz it sets the link as wall when restarting

**Comment by Jas-SinghFSU** [comment]
Yes, I'll look for a intuitive way to provide this.

**Comment by rishav12s** [comment]
@Jas-SinghFSU adding to this 

tried to do a complete fresh install of hyprpanel to fix the swww issue and this happens after a reboot 
![240810_22h29m26s_screenshot](https://github.com/user-attachments/assets/0c157921-06e8-488c-b9f0-16d6fa43aa3f)

distorted wallpaper and swww crash sending me back to sddm

removing matugen doesnt work seems like hyprpanel is intefering with swww even when no wallpaper is set in the settings of the bar

swww randomly crashes when this is happening

**Comment by Jas-SinghFSU** [comment]
I'll look into making swww/wallpaper service opt-in.

**Comment by Jas-SinghFSU** [comment]
@rishav12s Could you test branch `wallpaper_opt_out` by going to `Settings > Theming > General` and disabling `Apply Wallpapers`? Note that this will kill the swww service so you may have to manually restart it again.

But this will make it so the theme is generated off of the wallpaper but the wallpaper isn't applied. This can of course be enabled again in the same option. Please let me know if that satisfies your use-case and if it fixes the bugs it caused with your existing `swww` instance.

**Comment by rishav12s** [comment]
@Jas-SinghFSU i will try and let you later for sure been busy with work all day

**Comment by Jas-SinghFSU** [comment]
No stress, whenever you get a chance.
