### ISSUE TITLE
[Annoying Bug!!!] The Settings "window" doesn't fit and breaks when next to another windows in the same workspace

### ISSUE THREAD

**Issue by UnaTried** [Jas-SinghFSU/HyprPanel#106]
**Describe the bug**
When I have the settings "window" open next to another application like my terminal or the web browser, I can't access the side that is at the edge of my screen. So if the "window" is on the left side, I can't access the left side of it. And if it's on the right, I can't access the right side.

**To Reproduce**
Open settings "window" next to another app

**Expected behavior**
To have the app work and shrink according to the space available.

**Screenshots**
I can't do any right now, since I'm on my phone.

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager: Hyprland

**Additional context**
Nothing to add.

**Comment by Jas-SinghFSU** [comment]
Until I get around to making the settings window float, you can add this rule in your `hyprland.conf` to force the settings to float on top of other windows.
```
windowrulev2 = float, class:^(.*com.github.Aylur.ags*)$
```

Hopefully that resolves some irritation for you in the meantime.

**Comment by matavach** [comment]
I've noticed this too. Can probably change the minimum width of the window
