### ISSUE TITLE
Settings app doesn't retain changes to dashboard config

### ISSUE THREAD

**Issue by ashebanow** [Jas-SinghFSU/HyprPanel#11]
**Describe the bug**
I've tried it several times. Changing Edge to Firefox, or Spotify to Youtube Music, nothing gets saved. I tried opening/closing the app after edits, or switching to another tab, but everytime I go back to the Dashboard panel it reverts to original setings, and my changes never show on the actual dashboard.

**To Reproduce**
As above

**Expected behavior**
Once I edit the dashboard config, I expect it to take effect immediately and remember those changes across restarts

**Screenshots**

**Desktop (please complete the following information):**
 - Distribution: Endeavor
 - Window Manager/Desktop Environment: Hyprland, of course

**Additional context**

**Comment by ashebanow** [comment]
In fact none of the settings stuff seems to persist.... I fixed for myself by editing the defaults in options.ts

**Comment by Jas-SinghFSU** [comment]
Are you seeing any errors when you attempt to make changes? Also it's not intuitive but you have to press 'Enter' after every input for it to take effect which is easy to miss since there's no indication (currently at least).

**Comment by ashebanow** [comment]
No errors in the logs. I think the Enter thing is what got me, I definitely wasn't doing that. Now that I do press enter, it works. Thanks for the help, but you should definitely add a per-tab apply/revert button to make it clearer.

**Comment by Jas-SinghFSU** [comment]
Each setting does have a revert button but I agree that there should be some indication that the input settings haven't been applied. I'll mark this ticket as a feature request so I can come back to this and implement it.
