### ISSUE TITLE
Menus do not scale properly according to the monitor's scaling settings.

### ISSUE THREAD

**Issue by Shubham-550** [Jas-SinghFSU/HyprPanel#111]
**Describe the bug**
When using a monitor with a non-default scale factor (e.g., 1.2x or 1.6x), menus appear large and some go off the screen.

**To Reproduce**
In hyprland.config change monitor scale other than `1`.
`monitor=name,resolution,position,scale`

**Expected behavior**
Menus should scale appropriately based on the monitor's scale and should always remain fully visible within the screen boundaries.
Options to customize menu size and border.

**Screenshots**
![screenshot_2024-08-12_07-23-21](https://github.com/user-attachments/assets/11701206-72ca-4fda-a0f9-669929f37b80)
![screenshot_2024-08-12_07-23-31](https://github.com/user-attachments/assets/35fad0c2-3f5b-4b19-824e-6b5e499fba20)
![screenshot_2024-08-12_07-23-43](https://github.com/user-attachments/assets/55b637ea-5158-4008-9ce2-a902271b1a58)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Comment by Jas-SinghFSU** [comment]
We'll keep this issue specific to the menu's going out of the screen. As for scaling, you can change the font-size and that should scale you appropriately in the settings > general.

We can create a separate issue to allow scaling on the menus individually.

**Comment by Shubham-550** [comment]
Changing font size affect both monitors

**Comment by Shubham-550** [comment]
Also, settings window do not scale properly in small window.

https://github.com/user-attachments/assets/cef0260e-48a9-4dcf-af50-d03a8f77ed94

**Comment by Jas-SinghFSU** [comment]
```
windowrulev2 = float, class:^(.*com.github.Aylur.ags*)$
```
You can add that to make the settings window float. Unfortunately the component used for switching pages isn't too flexible for sizing. That likely needs a rework and will get one when the menu gets refactored and updated.

But the floating rule should hopefully help you.

**Comment by Jas-SinghFSU** [comment]
Let's create a separate ticket for improved scaling per monitor..
