### ISSUE TITLE
[Bug] Can't open options where notifications are

### ISSUE THREAD

**Issue by zDyanTB** [Jas-SinghFSU/HyprPanel#116]
**Describe the bug**
Can't expand options where notifcations are showed
e.g: notications shows on the right, widgets that are on the right can't expand, or even hover

**To Reproduce**
Send an notifcation and try open any option on the same side

**Expected behavior**
overlay ?

**Desktop (please complete the following information):**
 - Distribution: Nix
 - Window Manager/Desktop Environment: Hyprland

https://github.com/user-attachments/assets/11c9244d-3abd-4b3a-ad22-55bc39b11ad1

**Comment by matavach** [comment]
I was able to reproduce this easily.
Will take a look.
