### ISSUE TITLE
[Request] New bar widgets

### ISSUE THREAD

**Issue by zDyanTB** [Jas-SinghFSU/HyprPanel#123]
Would be great to have more widgets for the bar, like weather and powermenu

I suggest shifting the power options to an expandable widgets on the bar, IMO it's more intuitive and concise

[yuri dotfiles](https://github.com/yurihikari/garuda-sway-config?tab=readme-ov-file) shows a cool weather widget
![image](https://github.com/user-attachments/assets/87ea4d46-655f-41cb-b6e1-3dd752e13dc0)
just like an cpu,ram usage

**Comment by Jas-SinghFSU** [comment]
The goal is to implement the ability for users to create custom modules from within HyprPanel like waybar. The difference is that hyprpanel won't limit the ability to intervals but also allow events. All these custom modules then be satisfied by that implemention.

**Comment by zDyanTB** [comment]
I see, but these widgets already have an implementation, I just want an `bar` version. Would this be possible?

**Comment by Jas-SinghFSU** [comment]
Could you quantify some of the widgets that you'd want please? That way they can be prioritized when work begins.

**Comment by zDyanTB** [comment]
A power menu, and weather, cpu and ram usage

![image](https://github.com/user-attachments/assets/ee83eb6d-86b5-4480-b5f2-e390b8e628f5)
As I said, they already exists

**Comment by Jas-SinghFSU** [comment]
Implemented: I'll update the Wiki to reflect the changes.
In the meantime you can refer to: https://github.com/Jas-SinghFSU/HyprPanel/pull/213#issue-2499190614
