### ISSUE TITLE
More transperancy options

### ISSUE THREAD

**Issue by sweetspace** [Jas-SinghFSU/HyprPanel#124]
The only current transparency option is a toggle on / off for the main background of the bar. It'd be great to have more options and maybe a slider for opacity strength.

![snapshot_2024-08-14_21-27-33](https://github.com/user-attachments/assets/2ffbd879-068b-4cd1-9a67-5fb663ac29c8)

I'd love to see this implemented for the widgets (Dashboard, media, clock menu etc) and the bar _background_ itself.

**Comment by Jas-SinghFSU** [comment]
@sweetspace 
Each element can now have a custom opacity applied to it. This includes:

Bar's background
Bar's buttons
Each dropdown menu: Theming > General Settings > Menu Opacity
Notifications
OSD
Tooltip (controlled by dropdown menu opacity: Theming > General Settings > Menu Opacity)
System popover menus (controlled by dropdown menu opacity: Theming > General Settings > Menu Opacity)

**Comment by sweetspace** [comment]
Thank you!
