### ISSUE TITLE
More popover menu theme options

### ISSUE THREAD

**Issue by sweetspace** [Jas-SinghFSU/HyprPanel#132]
The border and button colors of the popover menu recently added is unable to be themed.
![snapshot_2024-08-15_17-09-58](https://github.com/user-attachments/assets/ccbbbc80-83a2-41ff-88b2-9666c2208aa4)

**Comment by Jas-SinghFSU** [comment]
@sweetspace  All the issues have been resolved. If they still persist please disable and re-enable matugen.
