### ISSUE TITLE
Dynamic theme preset switching using commands

### ISSUE THREAD

**Issue by rishav12s** [Jas-SinghFSU/HyprPanel#133]
The new theme and config import options work wonderfully 

Specially the theme presets looks gorgeous and work better than matugen 

Would it be possible to switch configs by using a terminal command so that i dont have to manually go into the overview everytime 

maybe doing `ags theme ~/HyprPanel/themes/name-of-theme.json` or some other implementation

great work as always thanks for the dedication 

(the swww thing was also fixed but now i wanna just use presets man 😆)

**Comment by Jas-SinghFSU** [comment]
@rishav12s  Implemented a global method called `useTheme` which takes the path of the theme as input.

You can call it like so:
```bash
ags -r "useTheme('$HOME/.config/ags/themes/nord.json')"
```

**Comment by rishav12s** [comment]
works as intended thanks
