### ISSUE TITLE
Widget for keyboard layouts

### ISSUE THREAD

**Issue by Ali-SZ** [Jas-SinghFSU/HyprPanel#138]
**Is your feature request related to a problem? Please describe.**
I use two keyboard layouts and a widget for showing current keyboard layout would be great.

**Describe the solution you'd like**
A widget for showing current keyboard layout.
Something like this:
![Screenshot_2024-08-16_20-18-07](https://github.com/user-attachments/assets/4cd463c4-d315-4d88-9a0d-159399d24b8e)

**Comment by orxngc** [comment]
Related to this, an OSD that detected when the keyboard layout is changed and displayed the change would be awesome.

**Comment by Jas-SinghFSU** [comment]
Implemented: I'll update the Wiki to reflect the changes.
In the meantime you can refer to: https://github.com/Jas-SinghFSU/HyprPanel/pull/213#issue-2499190614
