### ISSUE TITLE
Error opening AGS

### ISSUE THREAD

**Issue by greeid** [Jas-SinghFSU/HyprPanel#14]
**Describe the bug**
Give an error when trying to open AGS

**To Reproduce**
Clone the config, install deps and try doing `ags`

**Expected behavior**
AGS gets started

**Screenshots**
```text
(com.github.Aylur.ags:268228): Gjs-CRITICAL **: 09:13:39.223: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Button 0x622491887320.
== Stack trace for context 0x622490a69cf0 ==
```
**Desktop (please complete the following information):**
 - Distribution: EndeavourOS
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
It repeats many times like this : 
![image](https://github.com/user-attachments/assets/f5f34418-de02-497b-af41-ab556f9a6d5b)

**Comment by Jas-SinghFSU** [comment]
Could you paste the complete logs? The error that is generating the JSAPI logs is usually above them all.

**Comment by greeid** [comment]
```txt
(com.github.Aylur.ags:283316): Gjs-Console-WARNING **: 09:41:52.640: Another notification daemon is already running: SwayNotificationCenter
Another system tray is already running

(com.github.Aylur.ags:283316): Gjs-Console-CRITICAL **: 09:41:53.211: GLib.SpawnError: Failed to execute child process “gpustat” (No such file or directory)
proc@resource:///com/github/Aylur/ags/utils/exec.js:11:27
execAsync@resource:///com/github/Aylur/ags/utils/exec.js:77:19
startPoll/this._interval<@resource:///com/github/Aylur/ags/variable.js:40:60
interval@resource:///com/github/Aylur/ags/utils/timeout.js:3:5
startPoll@resource:///com/github/Aylur/ags/variable.js:40:30
Variable@resource:///com/github/Aylur/ags/variable.js:26:18
default@resource:///com/github/Aylur/ags/variable.js:130:36
Stats@file:///tmp/ags/hyprpanel/main.js:5978:23
dashboard_default@file:///tmp/ags/hyprpanel/main.js:6337:17
@file:///tmp/ags/hyprpanel/main.js:6358:3
async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:283316): Gjs-CRITICAL **: 09:41:53.222: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Box 0x573ab0aaf580.
== Stack trace for context 0x573aafcb4d80 ==

(com.github.Aylur.ags:283316): Gjs-CRITICAL **: 09:41:53.222: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Icon 0x573ab0a81470.
== Stack trace for context 0x573aafcb4d80 ==
```

**Comment by Jas-SinghFSU** [comment]
Have you ensured that all the dependencies are install? By running both the pacman AND the yay commands in the instructions?

If so then could you share the following lines in your `/tmp/ags/hyprpanel/main.js`
line 5978, 6337 and 6358

**Comment by greeid** [comment]
Thanks, seems like one dep wasn't installed from AUR, 
but how can I change the font and font-size?

I tried editing `scss/variable.scss` but it reverts back to the default after running ags

**Comment by greeid** [comment]
Also how do I decrease overall size of widgets? 
Some widgets are crossing the bounds of screen

![image](https://github.com/user-attachments/assets/bccca31d-b933-4e6c-98a0-5cb419a4b539)
like here

**Comment by greeid** [comment]
Like here changing the font-size from configuration also yields the same result 

https://github.com/user-attachments/assets/d6e04396-2fd3-465a-b9af-19ed336323ea

**Comment by Jas-SinghFSU** [comment]
You're not able to change font size in the settings menu > Config > General?  Thay will make it scale properly so it's not so large.

**Comment by greeid** [comment]
> You're not able to change font size in the settings menu > Config > General? Thay will make it scale properly so it's not so large.

you can see the video I attached

**Comment by Jas-SinghFSU** [comment]
Ah, did you make sure to press enter after inputting the value? It's not very obvious but for them to take effect you have to input your value and press enter.

**Comment by greeid** [comment]
How can I decrease the margin on both side and make the bar a little floating instead of attaching to screen?
I thought there would be some margin/padding but I couldn't find one that would accomplisht the said stuff

![image](https://github.com/user-attachments/assets/7695b931-14b1-4da7-a919-35c89d088ff0)
Like here my waybar doesn't have margin between workspace and edge of waybar and is also floating independently instead of being attached to the screen

![image](https://github.com/user-attachments/assets/d0985f37-772d-4039-a102-f83187f954f8)
but here in AGS the bar is attached to the screen and there is a lot of blank space 

Plus the space between the icons and text is too much for modules in right any way to fix that?

Sorry for the trouble in advanced

**Comment by Jas-SinghFSU** [comment]
That functionality doesn't exist and would be nice feature indeed. Could you please open a feature request issue and I'll get to it soon.

**Comment by greeid** [comment]
> That functionality doesn't exist and would be nice feature indeed. Could you please open a feature request issue and I'll get to it soon.

Cool will do 

But how do I decrease space between the icons and text
like in the right modules ( sound, wifi etc.) you can see that icon and text have 1 or 2 white space more than needed 

i tried looking through the code to see, but I can't seem to find it haha

**Comment by Jas-SinghFSU** [comment]
Those modules all sit under `modules/bar`. So volume would be `modules/bar/index.ts`. If you look at line 38, the spacing is handled by a literal space (as in the space character) rather than margins which is honestly quite awful of an implementation. You feature request would involve me implementing this with actual styled margins.

It's a remnant of the beginnings of the project that never got updated, so I should do that probably.

**Comment by Jas-SinghFSU** [comment]
> But how do I decrease space between the icons and text
Let's open a new feature request for that.

If everything else is good I will be closing this ticket. If you disagree please feel free to open it again with a comment.
