### ISSUE TITLE
HyprPanel restarts when the Config/Theme import dialog is closed (canceled)

### ISSUE THREAD

**Issue by Jas-SinghFSU** [Jas-SinghFSU/HyprPanel#141]
HyprPanel should only restart when a theme is applied. It does so even when we cancel out of the dialog without choosing a theme.

**Comment by Roxor-007** [comment]
Hey! This may be irrelevant but I made my own customisations from settings of hyprpanel. I do not know what I did wrong but when I reinstalled my hyprland and installed all the  theme packages back. The import theme/config did not work for me. I am not sure if I did anything wrong. Could you please take a look? I am kinda new to hyprland and found your repo very good and intresting.
https://github.com/Roxor-007/dots.git

**Comment by Jas-SinghFSU** [comment]
@Roxor-007 Could you open a ticket so we can discuss in the ticket please? Easier to follow.

**Comment by Jas-SinghFSU** [comment]
By ticket I mean issue, sorry.
