### ISSUE TITLE
Image browse window appers behind bar

### ISSUE THREAD

**Issue by XJHero07** [Jas-SinghFSU/HyprPanel#145]
**Describe the bug**
The window to select the image for pfp and wallpaper gets covered by the bar.

**To Reproduce**
Followed the NixOS steps and followed the configuration instructions in the readme.

**Expected behavior**
To be able to see the top part of the file select window.

**Screenshots**
Sadly cant, didnt configure any screenshot method.

**Desktop (please complete the following information):**
 - Distribution: NixOS flakes with Home Manager.
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
Its probably because the bar is not locked to the background, tried looking through Hyprland wiki but no luck, I swear I saw something about that.
Thank you for reading this, love your work.

**Comment by Jas-SinghFSU** [comment]
@XJHero07 You can now change the Layer of your bar via Configuration > Bar > Layer and move it to 'Bottom' so your windows can remain on top of it.
