### ISSUE TITLE
ability to include own window titles and media icon without directly changing index.ts for both

### ISSUE THREAD

**Issue by rishav12s** [Jas-SinghFSU/HyprPanel#148]
I think this is a necessary feature as users might have different choices of browsers, applications, terminals and media players (as for myself i prefer to use foot and thorium over kitty and firefox sometimes)

I have to edit the index.ts for both the bar modules everytime doing git pull as they get overwrite when there is a change of code

maybe sourcing another file which has all the window titles and icons for specific media player into the index.ts so that users can have their custom applications show with icons and correct window title

**Comment by Jas-SinghFSU** [comment]
@rishav12s The Window Title Mappings option in Configuration > Bar > Window Titles now has an input to let users define this. The option has a link to the wiki on how to define custom mappings as well: https://hyprpanel.com/configuration/panel.html#window-title-mappings
