### ISSUE TITLE
any way to fix the dashboard not scaling properly

### ISSUE THREAD

**Issue by rishav12s** [Jas-SinghFSU/HyprPanel#150]
i know this has been brought up earlier but i still couldnt find a proper solution 

maybe seperate font size scaling for the bar and dashboard could fix it 

setting the font size to 0.9rem or lesser numbers fixes it but makes the bar too small and ugly 

my gdk_scale is 1 and monitor scaling in hyprland.conf is 1

im using a 1366x768 res laptop with hyprpanel's default font and font size set to 1.0rem as its the most comfortable for me atm

![240818_15h32m20s_screenshot](https://github.com/user-attachments/assets/53b5bf09-46e5-46c5-88ea-07287850a98b)

**Comment by Jas-SinghFSU** [comment]
I'll implement individual scaling today.

**Comment by Jas-SinghFSU** [comment]
@rishav12s All the individual menus and the bar can now be scaled without effecting each other. The options to scale can be found in Configuration > General.
