### ISSUE TITLE
Change number of shortcuts and directories

### ISSUE THREAD

**Issue by LDAP** [Jas-SinghFSU/HyprPanel#152]
**Is your feature request related to a problem? Please describe.**
I find it overwhelming having too many shortcuts and directories.

**Describe the solution you'd like**
Adapt the layout to the number of items with non-empty configuration.

**Describe alternatives you've considered**
-

**Additional context**
![image](https://github.com/user-attachments/assets/5f342e1e-7584-4e8f-830f-a941bcdb89b0)

**Comment by Jas-SinghFSU** [comment]
Shortcut icons now automatically hide if no command is provided.
