### ISSUE TITLE
Help adding updates and brightness modules, as well as a border around modules

### ISSUE THREAD

**Issue by zstg** [Jas-SinghFSU/HyprPanel#16]
**Is your feature request related to a problem? Please describe.**
I'm not quite sure how to add additional modules to this bar. I'd like a module (quite similar to the volume module) that displays brightness. And I'd like to know how to create a new module (perhaps by duplicating and modifying existing code for 1 module?) for showing the number of updates (on hover, it shows what updates are available - via `yay -Qu` on Arch, and if i click it it opens a terminal window prompting me to update). I *have* achieved this on Waybar, but I have no idea how to get this working on AGS.

**Describe the solution you'd like**
- how to create a custom module
- module for brightness
- module for updates
- blue border around windows

**Describe the steps you've taken**
This is how it looks in my fork. I'd modified the border of the individual menus, but I'm not able to set this blue border around 
![image](https://github.com/user-attachments/assets/2d0492cb-0d0a-499e-b15d-2cf11dd90b09)

**Additional context**
Forgive me if this isn't the right place to ask for help (I guess it isn't).

**Comment by zstg** [comment]
![image](https://github.com/user-attachments/assets/7f25be8e-e854-4a36-a4bd-b3ae1ffc5f3e)
Here's a pic of Waybar's CPU usage, brightness and updates modules.

**Comment by Jas-SinghFSU** [comment]
> I'd modified the border of the individual menus, but I'm not able to set this blue border around

Could you clarify this please? I'm not sure I understand.

In terms of creating custom modules, you can follow the documentation over at https://aylur.github.io/ags-docs/ to know how to develop in AGS. For reference, you can look at https://github.com/Jas-SinghFSU/HyprPanel/blob/master/modules/bar/window_title/index.ts as that is a rather simple bar module.

**Comment by zstg** [comment]
I tried copying the window_title files, but I do not understand how to use it, rename it to create a custom module. I reckon if I'm able to "duplicate" one of the modules (say the window title module) I'll be able to replace the content there with the content that I'd want (namely updates)
