### ISSUE TITLE
Ability to hide bar via hotkey

### ISSUE THREAD

**Issue by Fifthdread** [Jas-SinghFSU/HyprPanel#164]
Hello! I've recently migrated from Waybar, and one of the features I enjoyed was the ability to hide the bar via hotkey such as SUPER + B. Sometimes it was nice for me to hide the bar when it wasn't in use.

I haven't found a method to do this with HyprPanel so far, but it'd be nice. With Waybar, SUPER+B would slide the bar up out of view and hyprland tiles would expand to use the new available space.

**Comment by Jas-SinghFSU** [comment]
You can do this with the command:
```
ags -t bar-0
```
Replace 0 with the id of your monitor.  So if you want to hide the bar on monitor with id 2, you can
```
ags -t bar-2
```

**Comment by Fifthdread** [comment]
Awesome. Thanks- works like a charm. Will close!
