### ISSUE TITLE
Cannot change clock icon color

### ISSUE THREAD

**Issue by plasmoduck** [Jas-SinghFSU/HyprPanel#167]
Cannot change clock icon color independent of text color like all the other elements. The clock icon should be yellow and text white. But the icon is white like the text. 

I have attached a screenshot showing my config options and the bar. Hopefully this can be fixed. 

![20240822_17h08m33s_grim](https://github.com/user-attachments/assets/ec505d3b-0ecc-4260-919b-5622b36c0f30)

**Comment by Jas-SinghFSU** [comment]
The clock 'icon' is embedded into the formatting of the time and isn't a standalone icon like the rest. That's why there's not a way to color it separately.

**Comment by Jas-SinghFSU** [comment]
I might add a standalone icon.

**Comment by plasmoduck** [comment]
Yeah I figured that was the case, the icon (glyph) is embedded into the formatting. Just thought it was odd there was the option to change the color for it when it does nothing. Hopefully you can fix it so it's possible to change the color like all the other elements. Cheers :)

**Comment by Jas-SinghFSU** [comment]
@plasmoduck Added
