### ISSUE TITLE
Insane RAM consumption with notificaion panel on

### ISSUE THREAD

**Issue by greed-d** [Jas-SinghFSU/HyprPanel#171]
**Describe the bug**
So I lent my laptop to my brother, who kept screenshoting stuff he's studying about, now ags has about 100 notification and when I try to clear it my laptop completely freezes

**To Reproduce**
Have about 100 notifications on notification panel and try to clear all of them at once

**Expected behavior**
Shouldn't consume much RAM

**Screenshots**
![20240822230619_1](https://github.com/user-attachments/assets/6e32a3fb-fc07-4f6f-bcbb-65932c8e6556)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
I have around 6.6 GB of usable RAM and AGS is taking about 4.4 of it

**Comment by Jas-SinghFSU** [comment]
Note for self: Potentially related to #170

**Comment by Jas-SinghFSU** [comment]
@greed-d If you are able to still replicate this, could you - once replicated - try deleting your `~/.cache/ags/notifications/` directory and disabling `Preserve Actions` in `Settings > Configuration > Notifications`?

**Comment by greed-d** [comment]
Followed the instructions and removed `~/.cache/ags/notifications` which removed all notification, then Disabled `Preserve Action` 
after that again added around 100 notifications, the RAM usage did spike but not as much as before, but after that AGS suddenly closed giving message 

```text
(com.github.Aylur.ags:2317612): Gjs-CRITICAL **: 11:13:22.216: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was enter-notify-event on Ags_Button 0x58b47d299d80.
== Stack trace for context 0x58b46eef4e20 ==
#0   58b46efbc518 i   resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266 (13a91c47d560 @ 139)
Gdk-Message: 11:13:59.073: Lost connection to Wayland compositor.
```
There was bunch of these message and the starting log couldn't be found as my terminal only preserves last 10,000 lines

**Comment by greed-d** [comment]
It also consumes insane amount of CPU resource one I try clearing all notification at once

```text
 

(com.github.Aylur.ags:2367919): Gjs-Console-WARNING **: 12:21:53.940: Error: missing dependencies: swww
dependencies@file:///tmp/ags/hyprpanel/main.js:1129:18
Wallpaper@file:///tmp/ags/hyprpanel/main.js:1245:10
@file:///tmp/ags/hyprpanel/main.js:1257:25
async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:2367919): Gjs-Console-WARNING **: 12:21:55.096: Another notification daemon is already running: SwayNotificationCenter

(com.github.Aylur.ags:2367919): Gjs-WARNING **: 12:21:57.186: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
execAsync@resource:///com/github/Aylur/ags/utils/exec.js:78:12
onConfigParsed@file:///tmp/ags/hyprpanel/main.js:9837:31
_load@resource:///com/github/Aylur/ags/app.js:203:29
async*vfunc_activate@resource:///com/github/Aylur/ags/app.js:109:14
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
Gdk-Message: 12:22:47.375: Lost connection to Wayland compositor.
```
same error message 

And this is cpu consumption 

![image](https://github.com/user-attachments/assets/25925eae-8415-4afb-a431-c6dfb254dc05)

**Comment by Jas-SinghFSU** [comment]
Gotcha, I'll have to look into it this weekend. Thanks for the info, extremely useful.

**Comment by greed-d** [comment]
I think this will be fixed after fixing the notification issue, but the clock also gets stuck and I have to restart ags ko resume it.., 
plus while on the topic of clock, normally the calendar also isn't updated after 00:00, so sometimes I get confused haha

https://github.com/user-attachments/assets/73161606-5bd4-4ee4-8bf3-c7f41a276af2

**Comment by Jas-SinghFSU** [comment]
Is the stuck clock issue happening right after the notification issue? Or is it happening separately

**Comment by greed-d** [comment]
After notification gets stuck and unstuck clock gets stuck

**Comment by Jas-SinghFSU** [comment]
Gotcha. What I meant was that the clock issue doesn't happen if the notification issue doesn't happen right? Just trying to triage before I work on it this weekend.

**Comment by greed-d** [comment]
Yes, the clock issue ( freezing of clock ) only occurs after ags has stuck with notification panel

**Comment by zDyanTB** [comment]
Note: sending an notification freezes the bar for ~2 seconds

**Comment by Jas-SinghFSU** [comment]
@zDyanTB When it freezes the bar, how many notifications are in the Notifications menu? Could you share your system specs when you get a chance please? I can easily replicate the issue when there are numerous notifications but I can't seem to replicate the lag with just a few < 20.

**Comment by Jas-SinghFSU** [comment]
Is your matugen code modified ins ome way? It seems to be trying to access a bat-colors.tmTheme in the .config/matugen/templates. Hyprpanel doesn't have that code and since it can't seem to find that file, it's failing to generate colors. 

Still looking into the performance issue.

**Comment by anotherhadi** [comment]
The pagination menu works great, however, could we hide it if npage == 1?
