### ISSUE TITLE
Monitor Placement

### ISSUE THREAD

**Issue by WhatsCS** [Jas-SinghFSU/HyprPanel#175]
**Is your feature request related to a problem? Please describe.**
No problem, just would like the ability to have the panel be "mounted" to the bottom of monitors.

**Describe the solution you'd like**
Config option per panel to dictate where on the monitor the panel should be mounted.

**Describe alternatives you've considered**
Biting the bullet and making a pull request, but I hate working with js/ts.

**Comment by Jas-SinghFSU** [comment]
Hey, you can criticize JS but I will not have you blasphemize TS hehe.

**Comment by Jas-SinghFSU** [comment]
Added an option to move the bar to the bottom in `Configuration > Bar > Locations`.
