### ISSUE TITLE
Floating bar instead of attaching to the edges of screen

### ISSUE THREAD

**Issue by greeid** [Jas-SinghFSU/HyprPanel#18]
**Is your feature request related to a problem? Please describe.**
A floating bar instead of bar attaching to the edges of screen and also the ability to decrease left and right margin

**Describe the solution you'd like**
Have an option to switch between the floating and fixed bar and also manage the spacing

**Describe alternatives you've considered**
Waybar has similar features

**Additional context**
Waybar : 
![image](https://github.com/user-attachments/assets/2fea5f0e-179e-4331-93ae-93fd1beffde9)

Hyprpanel:
![image](https://github.com/user-attachments/assets/4f2561b3-9693-4a00-a55c-bdf600b2ea61)

**Comment by Jas-SinghFSU** [comment]
Implemented: Options to enable floating are in `Configuration > Bar > Spacing`.

Please open a new feature request when you have time for the spacing of icons in the bar as you suggested.
