### ISSUE TITLE
Notification popup not respecting time format 

### ISSUE THREAD

**Issue by NotJoeMama727** [Jas-SinghFSU/HyprPanel#183]
**Describe the bug**
The notification popup will not show the correct time format

**To Reproduce**
Set time to anything other than 12 hour time and receive a notification 

**Expected behavior**
The notification popup will show the correct time format

**Screenshots**
![image](https://github.com/user-attachments/assets/a08e1db7-c8be-40f2-9660-906c1c08b6e0)

**Desktop (please complete the following information):**
 - EndeavourOS
 - Hyprland

**Additional context**
None

**Comment by Jas-SinghFSU** [comment]
Should be good now.
