### ISSUE TITLE
A minor inconsistency with the split style theming

### ISSUE THREAD

**Issue by rishav12s** [Jas-SinghFSU/HyprPanel#186]
the clock module icons are not colored like the rest which doesnt fit style 

i hope you implement it in such a way that we can remove the date and the clock icon will still display with the split style colouring 

![240825_18h38m38s_screenshot](https://github.com/user-attachments/assets/8f2624ce-4414-4877-a80a-8461490c761a)

**Comment by greed-d** [comment]
How did you enable this?
