### ISSUE TITLE
Memory consumption tile

### ISSUE THREAD

**Issue by greed-d** [Jas-SinghFSU/HyprPanel#195]
**Is your feature request related to a problem? Please describe.**
I have a laptop with limited memory and have to keep track of it, so instead of opening the dashboard or btop everytime, it'd be good to have a memory consumed tile

**Describe the solution you'd like**
Implementation of memory consumed ( RAM consumed ) tile, which polls once a second or two

**Describe alternatives you've considered**
Opening dashboard/btop ¯\_(ツ)_/¯

**Additional context**
None

**Comment by Jas-SinghFSU** [comment]
A lot of custom modules like this are coming soon (tm).

**Comment by Jas-SinghFSU** [comment]
Implemented: I'll update the Wiki to reflect the changes.
In the meantime you can refer to: https://github.com/Jas-SinghFSU/HyprPanel/pull/213#issue-2499190614
