### ISSUE TITLE
Missing battery percentage

### ISSUE THREAD

**Issue by Lurgrid** [Jas-SinghFSU/HyprPanel#2]
I've activated the battery display, but even after restarting AGS, I can't see the percentage.

![image](https://github.com/user-attachments/assets/ff171c35-59ef-4b44-8d2b-b21710e0b071)
![image](https://github.com/user-attachments/assets/0a08d15a-ad76-4e29-8823-3414472c9220)

**Comment by Jas-SinghFSU** [comment]
If you go to the Config Panel > Bar > "Bar Layouts for Monitors", is your monitor ID (ID would be 0 if only one monitor) configured to show the battery module? You can refer to this part of the documentation here: https://github.com/Jas-SinghFSU/HyprPanel?tab=readme-ov-file#specifying-bar-layouts-per-monitor

**Comment by Jas-SinghFSU** [comment]
So you would use this config which includes the battery module in the right hand section and paste it into that text box.
```json
{
    "0": {
        "left": [
            "dashboard",
            "workspaces",
            "windowtitle"
        ],
        "middle": [
            "media"
        ],
        "right": [
            "volume",
            "network",
            "bluetooth",
            "systray",
            "battery",
            "clock",
            "notifications"
        ]
    }
}
```

**Comment by Lurgrid** [comment]
Ah yes sorry it's my fault, I hadn't seen, after adding this, it works perfectly!
