### ISSUE TITLE
Battery percentage not rounded up

### ISSUE THREAD

**Issue by Keremimo** [Jas-SinghFSU/HyprPanel#20]
**Describe the bug**
On the status bar, the battery percentage is displayed as a very long float, like %99.75837836523756.

**To Reproduce**
Steps to reproduce the behavior: Have battery, use AGS.

**Expected behavior**
The battery amount rounded up to two decimals after float, like 99.75%.

**Screenshots**
![image](https://github.com/user-attachments/assets/aab86314-2c06-43f4-b4c7-dcf27568982f)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
Using Thinkpad T480 with dual batteries.

**Comment by Jas-SinghFSU** [comment]
Well that's not good, lol. I'll fix this in the morning.

**Comment by Keremimo** [comment]
Thank you!
