### ISSUE TITLE
Icons for workspaces

### ISSUE THREAD

**Issue by loki1368** [Jas-SinghFSU/HyprPanel#204]
It would nice to have an ability to set icons for workspaces instead of numbers or beside numbers. 
In waybar i've used the following config

    "hyprland/workspaces": {
        "format": "{icon}",
	    "on-click": "activate",
		"format-icons": {
		"1": "<span font_desc='Font Awesome 6 Free'> </span>",
        "2": " ,
        "3": " "3,
        "4": " "4,
        "5": " ",
		"6": " ",
		"7": " 7",
	  	"8": " "8,
	  	"9": "",
	  	"10": "<span font_desc='Font Awesome 6 Free'> </span>",
      },

**Comment by matavach** [comment]
Currently, you can set icons here in the menu under `Configuration -> Bar -> Workspaces`. These icons accept any text string at the moment.

![image](https://github.com/user-attachments/assets/c983f601-5035-47ad-8219-64d7b235c3b3)

Do you mean to set specifically numbers workspaces as specific icons?

As a side note, we're planning on implementing a feature in the future to allow workspace icons to be automatically set as the icon of the primary window of the workspace (ie, if the workspace only contains Firefox, the workspace icon will be Firefox)

**Comment by loki1368** [comment]
I mean something like this

![image](https://github.com/user-attachments/assets/1f32cc9e-cec0-4dd2-98ab-b564a4bbc9a4)

Instead of text, there can be a number.

**Comment by Jas-SinghFSU** [comment]
Should be fairly easy.

**Comment by Jas-SinghFSU** [comment]
Implemented via #261. Will update the wiki to include instructions; PR contains them in the meantime.
