### ISSUE TITLE
Unable to determine game data

### ISSUE THREAD

**Issue by BlueDragon320** [Jas-SinghFSU/HyprPanel#205]
**Describe the bug**
I am unable to use hyprpanel and overview of workspaces on hyprland. 

**To Reproduce**
just using super+A [super=windows key] or use ags command on terminal

**Expected behavior**
Over view of current 10 workspaces and hyprpanel should have run.

**Screenshots**
![image](https://github.com/user-attachments/assets/ee699103-895a-46ac-8dac-27e93ff9a02a)
![image](https://github.com/user-attachments/assets/84d18f9e-1f4d-4540-8cb7-f76c66671ba7)

**Desktop (please complete the following information):**
 - Distribution: [ Arch Linux]
 - Window Manager/Desktop Environment: [Hyprland]

**Additional context**
At first things worked fine except the workspace overview. HyprPanel was working fine except few features. so i decided to delete the folder and install again [Yes, this was bad]. And now im stuck with this issue.

I did delete ags and reinstall it multiple times but did not work. I dont really know how ags works. So please do help me solve this is simple steps.

**Comment by Jas-SinghFSU** [comment]
You installed the wrong package. You seem to have ran this command:
```
yay -S ags
``` 
in order to install `ags`.

But that is the wrong package. You need to install `aylurs-gtk-shell-git` which is done via:
```
yay -S aylurs-gtk-shell-git
```

**Comment by Jas-SinghFSU** [comment]
You should remove `ags` (adventure game studio) if you don't plan on using it so it doesn't cause further confusion.

**Comment by BlueDragon320** [comment]
Thank you Mr it started working.

**Comment by Jas-SinghFSU** [comment]
@BlueDragon320 Nice, are we good to close this issue?

**Comment by BlueDragon320** [comment]
well hyprpanel is working but workspace overview isn't working.  Is there any way i can use both hyprpanel and the workspaceoverview [Photo attached]. 

This is the only issue else everything works fine.
 
![image](https://github.com/user-attachments/assets/95297d35-a11f-429a-8a3c-b3eab57f2d0b)

**Comment by Jas-SinghFSU** [comment]
Where is that workspace overview coming from?

**Comment by BlueDragon320** [comment]
ja's hyprland i guess may be its a feature. I asked this on discord the answer i got is " i can use only 1 among hyprpanel or this workspace, may be its because of ags" if i want to use that workspaceoverview i need to make that hyprland's ags file as default for ags.

**Comment by Jas-SinghFSU** [comment]
At the end of the day it is really just AGS. You could bring in his Overview module if you wanted to and have it work in this system. You'd just have to do it manually but it's possible.

**Comment by BlueDragon320** [comment]
Thank you for letting me know i will try doing that
