### ISSUE TITLE
Weather font donesn't work

### ISSUE THREAD

**Issue by Tataridayo** [Jas-SinghFSU/HyprPanel#224]
**Describe the bug**
When I click clock menu and try to look weather I only see square not weather icon

**To Reproduce**
Steps to reproduce the behavior: Launch hyprpanel, click clock menu on panel. And weather icon broken.

**Expected behavior**
Normal weather icon.

**Screenshots**
![image](https://github.com/user-attachments/assets/55f60c11-12d4-43a8-8134-d40a2ef02195)

**Desktop (please complete the following information):**
 - Distribution: Arch linux
 - Window Manager/Desktop Environment: Hyprland
**Additional context**
I used ./install_fonts.sh to install fonts but It didn't solve issue.

**Comment by Jas-SinghFSU** [comment]
This is because the system's Icon Theme in your swtup is incomplete and doesn't contain those icons.

Refer to: https://github.com/Jas-SinghFSU/HyprPanel/issues/33#issuecomment-2254939079

**Comment by solotitan** [comment]
Implementing physical weather icons would be helpful. Many system icon packs don't include weather icons, which can be a real pain. Maybe with these [https://erikflowers.github.io/weather-icons/](url) then create a switch in the settings to set weather icons to default or system.

**Comment by smathles** [comment]
I reckon this would be a good approach. Even icon themes like breeze, breeze-dark, and BeautyLine don't have the icons correctly showing, despite actually having weather icons generally.
So I reckon having the weather/logout icons packaged as assets could negate some of these config problems, especially if one doesn't want to install a supported icon theme like Adwaita.
