### ISSUE TITLE
Firefox context menu overlaps panel

### ISSUE THREAD

**Issue by ChicuMihai** [Jas-SinghFSU/HyprPanel#228]
I am using a 2560x1600 13inch monitor with 2.0 scaling.In firefox context menu will overlap with the bar if there is not enough space and the options become unreachable.I've tried using reserved space option in hyprland but it wastes a lot of space.Is it possible to change z-index for the bar or is there any other solution?

![screenshot](https://github.com/user-attachments/assets/c1a815d3-bfab-4c43-b34a-572d578b7374)

 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Comment by Jas-SinghFSU** [comment]
Yes, you can go to `Configuration > Bar > Layer` and change it to `Bottom` or whatever you seem best.

**Comment by ChicuMihai** [comment]
Thanks,this solves my issue
