### ISSUE TITLE
Custom button borders

### ISSUE THREAD

**Issue by Arae-1** [Jas-SinghFSU/HyprPanel#229]
**Is your feature request related to a problem? Please describe.**
I like the entire thing but I dislike the lack of the ability to make custom button borders in the bar 

**Describe the solution you'd like**
The ability to make custom button borders in the bar, similar to Hyprland window borders but for buttons

**Describe alternatives you've considered**
Not using button borders

**Additional context**
N/A

**Comment by Jas-SinghFSU** [comment]
I had meant to get this done but other work got prioritized. This is definitely on the roadmap and should be finished soon.
