### ISSUE TITLE
Ability to edit source code on NixOS

### ISSUE THREAD

**Issue by Cyliann** [Jas-SinghFSU/HyprPanel#237]
**Is your feature request related to a problem? Please describe.**
I accidentaly chnged font size to 10rem and now ags is crashing every time I launch it. Because it's crashing I cannot change it back.

Also I would like to modify the source code, to customize the bar beyond options available in settings.

**Describe the solution you'd like**
Be able to change config files.

**Comment by Jas-SinghFSU** [comment]
Go into `~/.cache/ags/hyprpanel/options.json` and delete thr line regarding font size. You should be able to start HyprPanel afterwards.

**Comment by Cyliann** [comment]
Thanks. That helped. What about editing the config itself? Is there a possibility to do it?

**Comment by Jas-SinghFSU** [comment]
That is the config :) Unless you're referring to something else? The options.json are all of your configuration options that are loaded into HyprPanel on startup.

**Comment by Jas-SinghFSU** [comment]
I'm not sure how nixos works if you're planning on changing the source code. The project is installed in `~/.config/ags` so all the source code should be there. 

Maybe someone else with NixOS experience can comment on this.

**Comment by Cyliann** [comment]
> I'm not sure how nixos works if you're planning on changing the source code. The project is installed in `~/.config/ags` so all the source code should be there.

On NixOS the source code is stored in read-ony `/nix/store`, and it's not in `.config/ags`. Guess I'll have to just clone the repo and install dependencies manually.

**Comment by anotherhadi** [comment]
It would be very nice to have a good hyprpanel flake with settings options and the ability to add custom modules from options

**Comment by orxngc** [comment]
modify source code ... just fork hyprpanel and edit your fork
as well as change the hyprpanel.url to github:your-username/hyprpanel

**Comment by orxngc** [comment]
that could be done by making a github workflow that automatically pulls changes, i think

**Comment by Cyliann** [comment]
We don't have to edit the entire source code. We could just add the ability to overwrite certain modules. Eg. before loading a module hyprpanel checks if that file is in the  `.config/hypr/hyprpanel` and if yes, then loads that file instead.

**Comment by DockterTeagle** [comment]
one possible solution to the source code issue could be as mentioned in #287 to store config as a configuration file. Then maybe allow some source code to be changed through that file somehow, as in changing the config adds the features wanted. To modify the actual source code you have to clone and build locally cause otherwise it is in the nix store and can't be modified.
