### ISSUE TITLE
Some themes have missing icons after the addition of wave button styles

### ISSUE THREAD

**Issue by rishav12s** [Jas-SinghFSU/HyprPanel#238]
### Catppuccin Mocha :

![240909_18h14m30s_screenshot](https://github.com/user-attachments/assets/d5aba34c-e72a-4e10-85ff-a95ad315fa87)

### Tokyo Night :

![240909_18h15m10s_screenshot](https://github.com/user-attachments/assets/42ac4f2f-3eb4-4ab5-8e3a-6fc68d848b4f)

The split button styles work fine but the default and the two wave styles have this problem

**Comment by Jas-SinghFSU** [comment]
The issue persists despite re-importing the non-split theme?

**Comment by Jas-SinghFSU** [comment]
That seems to be because the icon color in split is dark grey which blends into the background when non-split is used. You have to import the regular (non-split) theme to fix that - or change the icon colors yourself.

**Comment by rishav12s** [comment]
I see so importing split and then changing style wont work thanks should we close this ?

**Comment by Jas-SinghFSU** [comment]
Right because the style changes but the icon color remains, which is split is the same as the background, so it blends it. One can manually change it or import the non-split theme.

Gonna close since it's determined that this isn't a bug.
