### ISSUE TITLE
[Bug] Double-clicking `clear notifications` crash system

### ISSUE THREAD

**Issue by zDyanTB** [Jas-SinghFSU/HyprPanel#239]
**Describe the bug**
When clearing notifications, double-clicking it will call for an infinite loop and eventually crash the system

**To Reproduce**
Click to clear notifications, and double-cliking 

[Video](https://streamable.com/xsf7jw)

Log
```console
(com.github.Aylur.ags:81406): Gjs-CRITICAL **: 11:16:09.726: Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.
The offending callback was draw(), a vfunc.
== Stack trace for context 0x313d3940 ==
#0       3149fe08 i   resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266 (2b4cabe7d560 @ 139)
Gdk-Message: 11:16:09.727: Error flushing display: Broken pipe
```

 - Distribution: NixOs
 - Window Manager/Desktop Environment: Hyprland

**Comment by Jas-SinghFSU** [comment]
Not sure that it causes an infinite loop as much as it tries to access a resource that's already been deleted (consecutive clicks) and crashes in the process.

But I added in house notification removal that tracks and disables the removal button.
