### ISSUE TITLE
HyprPanel prevents screen tearing

### ISSUE THREAD

**Issue by NyanMaths** [Jas-SinghFSU/HyprPanel#240]
Hello and first thank you for this amazing panel !

When I enable tearing in Hyprland with hyprPanel, fullscreen and borderless fullscreen games (Minecraft and Geometry Dash tested) are not torn as my window rule tell them to.

To reproduce :
Enable tearing in Hyprland, start HyprPanel and this should be enough.
The behaviour persists even when I disable the OSD.

With HyprPanel not running, tearing works fine.
You can check by `sleep 2 && hyprctl monitors` and quickly switching to your game
It is said that nothing except the fullscreen app should show on screen to get tearing to work but the bar effectively don't show, so this should not happen I guess.
I don't know whether this should be fixed in HyprPanel or in AGS though.

System information :
 - Arch Linux (updated today)
 - Hyprland 0.43 (same on 0.42)
 - GPUs : intel tiger lake i965 (iGPU), nvidia ampere nvidia-open (dGPU)

Thanks in advance for any answer.

**Comment by Jas-SinghFSU** [comment]
You can now enable the `Tearing Compatible` option in `Configuration > General`.

**Comment by NyanMaths** [comment]
Nice ! Thanks a lot for this, it works flawlessly now.
