### ISSUE TITLE
Build fails on NixOS after #93

### ISSUE THREAD

**Issue by Cyliann** [Jas-SinghFSU/HyprPanel#245]
**Describe the bug**
After 05a7f130ef3d50617ff35412f354431cabe02558 rebuilding system with `nixos-rebuild --switch` results in `error: value is a function while a set was expected`

**To Reproduce**
Update flake to master and rebuild system.

**Expected behavior**
Builds fine.

**Desktop (please complete the following information):**
 - Distribution: NixOS
 - Window Manager/Desktop Environment: N/A

**Comment by Jas-SinghFSU** [comment]
@nebunebu @orxngc Maybe you guys have some insight regarding this.

**Comment by orxngc** [comment]
@Cyliann please show us your flake

**Comment by Cyliann** [comment]
Here it is:
```
{
  description = "Nixos config flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    hyprpanel.url = "github:Jas-SinghFSU/HyprPanel";
    nixos-06cb-009a-fingerprint-sensor.url = "github:ahbnr/nixos-06cb-009a-fingerprint-sensor";
    rose-pine-hyprcursor.url = "github:ndom91/rose-pine-hyprcursor";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, ... }@inputs: 
  let
    system = "x86_64-linux";
    pkgs = import nixpkgs {
	    inherit system;
      config.allowUnfree = true;
	    overlays = [
        inputs.hyprpanel.overlay.${system}
	    ];
	  };
  in {
    nixosConfigurations = {
      thickpad = nixpkgs.lib.nixosSystem {
        specialArgs = {inherit system inputs pkgs;};
        modules = [
          ./hosts/thickpad/configuration.nix
            inputs.nixos-06cb-009a-fingerprint-sensor.nixosModules.open-fprintd
            inputs.nixos-06cb-009a-fingerprint-sensor.nixosModules.python-validity
        ];
      };
      server = nixpkgs.lib.nixosSystem {
        specialArgs = {inherit system inputs;};
        modules = [
          ./hosts/server/configuration.nix
        ];
      };
    };
  };
}
```

And hyprpanel is installed via `environment.systemPackages = with pkgs; [ hyprpanel ];`

**Comment by orxngc** [comment]
removing the .${system} is what worked for me

**Comment by Cyliann** [comment]
Works for me as well. I suggest changing the `flake.nix` part in the [installation wiki](https://hyprpanel.com/getting_started/installation.html).

**Comment by Jas-SinghFSU** [comment]
@orxngc Do we think it's safe to remove from wiki?

**Comment by orxngc** [comment]
> Do we think it's safe to remove from wiki?

yes i do, i'll make a PR now @Jas-SinghFSU
