### ISSUE TITLE
Profile image option in settings does not work

### ISSUE THREAD

**Issue by fib-nm** [Jas-SinghFSU/HyprPanel#247]
**Describe the bug**
Changing my profile image in settings does not do anything. The default image stays and after reboot, chosen image is removed from 'Profile Image' tab.

**To Reproduce**
Choose any image in Settings in Configuration/Dashboard Menu/Profile Image.
Reboot to get chosen image deleted from settings tab.

**Expected behavior**
Expected profile image to change immediately after choosing an image in settings.

**Screenshots**
First 2 images show default image staying the same despite changing it in settings.
Last image shows image getting deleted after rebooting.
![sh1](https://github.com/user-attachments/assets/142f07a1-768d-427b-ad0e-0e117d22847a)
![sh2](https://github.com/user-attachments/assets/77411967-2e75-432a-b499-7aa06f93e5a0)
![sh3](https://github.com/user-attachments/assets/21c54650-9113-4e1a-bd0b-69e82b4b8429)

**Desktop (please complete the following information):**

Hyprland, built from branch  at commit 0f594732b063a90d44df8c5d402d658f27471dfe  (props: bump version to 0.43.0).
Date: Sun Sep 8 16:48:21 2024
Tag: v0.43.0, commits: 5196

flags: (if any)

System Information:
System name: Linux
Node name: archlaptop
Release: 6.10.8-arch1-1
Version: #1 SMP PREEMPT_DYNAMIC Wed, 04 Sep 2024 15:16:37 +0000

GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-H GT2 [UHD Graphics] [8086:9bc4] (rev 05) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GA106M [GeForce RTX 3060 Mobile / Max-Q] [10de:2520] (rev a1) (prog-if 00 [VGA controller])

**Additional context**

**Comment by Jas-SinghFSU** [comment]
This is odd because I just tested it and it worked for me.

Could you:
1. Send me your image that fails to apply?
2. Try a different image and see if it works?

**Comment by Jas-SinghFSU** [comment]
Forgot to mention that the image isn't removed, it's just that the file file name you see is the file picker component remembering the name of the file you just selected. That doesn't represent whether the image is saved into memory or not; it's a temporary display.

**Comment by Jas-SinghFSU** [comment]
Ahhh, yep. That may be it. Let's leave the issue open and I can look into better name resolution.
