### ISSUE TITLE
ags crashes on NixOS

### ISSUE THREAD

**Issue by orxngc** [Jas-SinghFSU/HyprPanel#25]
**Describe the bug**
When attempting to start ags, it crashes. A screenshot is below. More accurately, it doesn't start at all, not crash.

**Expected behavior**
Ags to start.
**Screenshots**
![image](https://github.com/user-attachments/assets/8bcc13fb-c066-42f3-81fa-7a665be6cd68)
**Desktop (please complete the following information):**
 - Distribution: NixOS 
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
I think it may be due to not having one of the dependencies installed. In NixOS, there is no package for `bluez-utils` (although I do have bluez installed.)

**Comment by dringwald** [comment]
To get it to work for me I had to change `services/screen_record.sh` and `services/snapshot.sh` and replace `#!/bin/bash` to `#!/usr/bin/env bash` in each. 

In lieu of `bluez-utils` I installed `bluez-tools` -- I don't know if that was necessary but I didn't get any errors.

**Comment by Jas-SinghFSU** [comment]
Could you please share your full log dump. It might indicate what you have missing atop these errors.

**Comment by simonoscr** [comment]
I am on NixOS too and had problems even starting ags. With the correct `#!` in those scripts like @dringwald said,  it is starting now. But it looks like some css files did not load.

Somehow I dont have permission to opening the files in scss folder:
`~/.config/ags/scss/variables.scss”: Permission denied`

I do not copy the files manually in the `~/.config/ags` location, instead I get the content of your repo as a non-flake input. So it is stored as read-only in the nix/store and makes a symlink in the ~/.config/ags folder.

**Comment by Jas-SinghFSU** [comment]
@simonoscr Unfortunately I don't have a NixOS environment to test these changes quite yet. I have gone ahead and updated the scripts to use `#!/usr/bin/env bash` by default. But I'm not sure about the Permission Denied issue; I can't replicate that until I set up NixOS.

**Comment by simonoscr** [comment]
No worries. When I copy the files manually into the ags folder, it works fine. I think the issue happens because the files inside the ags folder change when the configuration changes. So they they cant be read-only.

**Comment by orxngc** [comment]
>can you please share your full log dump
That message repeated ~30 times is my entire log dump, there isn't anything other than that.
@dringwald  's suggestion fixed the issue; it starts now— thanks!
I did experience the issue @simonoscr , but I imagine that's because of home-manager.
I'll put it in manually, kek.

**Comment by Arqamz** [comment]
I had the a similiar error, I manually copied the whole folder directly into .config/ags.
Here is my ags crashlog:
[agscrashlog.txt](https://github.com/user-attachments/files/16424127/agscrashlog.txt)

I know its probably a dependency issue, but I'd be grateful if you could confirm. I don't have an nvidia gpu btw, and the README mentions gpustat to be an optional dependency yet I still get an error for it
