### ISSUE TITLE
Libgtop is not included in dependencies on wiki

### ISSUE THREAD

**Issue by fib-nm** [Jas-SinghFSU/HyprPanel#250]
Wiki's dependency list does not include libgtop. Without it application does not work.
Took me like 30 minutes to figure it out, so update the wiki please.

![sh](https://github.com/user-attachments/assets/023359ab-0f16-4a31-8f94-fe89c326962b)

**Comment by Jas-SinghFSU** [comment]
Thank you for catching that. Fixed and should be reflected soon on the website.
