### ISSUE TITLE
[Bug] Fix workspace widget display for scratchpad

### ISSUE THREAD

**Issue by smathles** [Jas-SinghFSU/HyprPanel#264]
(edited by orangc, as the issue of special workspaces being incorrectly displayed — ex. -99 — was solved in #283)

Expected behavior:
When clicking on the special workspace tab in the workspaces module, the special workspace to appear. It does not.

To reproduce:
- Move a window to a special workspace.
- Optionally, set an icon for the special workspace as well as add special workspaces to the ignored workspaces list to prevent incorrect displaying. 
- Click on the special workspace tab

Environment:
This has been tested on both Arch and NixOS.

**Comment by rubiin** [comment]
Can confirm this might be a regression . I have  numbered workspaces 

![image](https://github.com/user-attachments/assets/951b7f23-a089-4e46-96e8-3d10e8ab0613)

**Comment by smathles** [comment]
You can still either hide it or set the -99 to another icon. This is what I've done.

The reason this still can't work is actually a hyprland issue, where you cannot dispatch special workspaces/scratchpads I believe.

`hyprctl dispatch workspace 3` will work for going to workspace 3, but this will NOT work with a special workspace as hyprland doesn't actually support this. Additionally, unlike a normal workspace you can have scratchpads visually "shown" over a normal workspace and use either keybinds/swipe gestures to switch to another workspace and the scratchpad is still shown over it. This must be cancelled using the `togglespecialworkspace` command, normal workspace dispatching won't work.

I'm honestly not sure what waybar does in this instance, but it's annoyingly subtle 😕

**Comment by Jas-SinghFSU** [comment]
closing as this is no longer valid. Hyprland doesn't allow us to dispatch to special workspaces. Hyprpanel has implemented the ability to blacklist specific workspaces or assign special icons.
