### ISSUE TITLE
autohide media widget not working

### ISSUE THREAD

**Issue by rishav12s** [Jas-SinghFSU/HyprPanel#267]
The autohide option is enabled and was working fine few days when no media was playing it automatically hid itself like it should 

but it shows unknown title etc and doesnt hide it stays persistent until i restart ags or reload to change theme

![240917_00h40m37s_screenshot](https://github.com/user-attachments/assets/18e4bcdc-be46-4e49-bf53-2150daea0629)
![240917_00h40m53s_screenshot](https://github.com/user-attachments/assets/5f3bf47f-4675-4715-aace-beb12bfaf7d9)
![240917_00h42m40s_screenshot](https://github.com/user-attachments/assets/5e56e443-38b1-49c2-9e7e-fa314a400042)

**Comment by Jas-SinghFSU** [comment]
Hmm, nothing has changed in the component. I wonder if we need to improve the filter to check that the remaining players are valid rather than just check if there are none at all.

Seems that in your case there is a media player with unknown values. Can you look into what's open in your PC when you get this?

**Comment by Jas-SinghFSU** [comment]
When that happens can you run this command please? And share the output:
```sh
busctl --user list | grep org.mpris.MediaPlayer2 | awk '{print $1}'
```

**Comment by Jas-SinghFSU** [comment]
Lol, sounds good.

**Comment by smathles** [comment]
This actually turned up for me today, though I don't have autohide enabled.

```
❯ busctl --user list | grep org.mpris.MediaPlayer2 | awk '{print $1}'
org.mpris.MediaPlayer2.firefox.instance_1_832
org.mpris.MediaPlayer2.plasma-browser-integration
org.mpris.MediaPlayer2.playerctld
```

![image](https://github.com/user-attachments/assets/a5089135-eae5-4ed8-9874-c70d01954715)

Still shows this even when I close firefox/spotify/whatever. I honestly thing I could fix this by restarting ags/laptop/whatever, but it would be nice to know why this is happening.

**Comment by Jas-SinghFSU** [comment]
> This actually turned up for me today, though I don't have autohide enabled.
> 
> ```
> ❯ busctl --user list | grep org.mpris.MediaPlayer2 | awk '{print $1}'
> org.mpris.MediaPlayer2.firefox.instance_1_832
> org.mpris.MediaPlayer2.plasma-browser-integration
> org.mpris.MediaPlayer2.playerctld
> ```
> Still shows this even when I close firefox/spotify/whatever. I honestly thing I could fix this by restarting ags/laptop/whatever, but it would be nice to know why this is happening.

@smathles It looks like Firefox is being recognized as an active player here?

**Comment by smathles** [comment]
@Jas-SinghFSU Yeah, it registers FF as an active player. The issue I was experiencing was when FF was playing, yet it still returned "unknown title" etc in the actual widget.

Only has happened once IIRC, might just be a firefox thing tbh.

**Comment by Jas-SinghFSU** [comment]
This is more-so firefox registering an active player when there is none. Closing, as this is not a hyprpanel issue as hyprpanel/ags simply display media players represented by MPRIS.

Please reopen if incorrent.
