### ISSUE TITLE
How does HyprPanel handle color schemes?

### ISSUE THREAD

**Issue by greeid** [Jas-SinghFSU/HyprPanel#27]
I'd like to implement my own GTK color scheme, how would I do that?

**Comment by Jas-SinghFSU** [comment]
The panel doesn't inherit any GTK color settings. You would have to customize your theme through the 'theming' section of the dashboard. Though, I do plan on being able to create/select/export/import the theming config so one could share it or save it as a backup.

**Comment by painerp** [comment]
Would love to use it with something like pywal or wallust

**Comment by xsghetti** [comment]
pywal would be absolutely killer with this

**Comment by Jas-SinghFSU** [comment]
I will look into pywal integration.
