### ISSUE TITLE
[BUG] notification menu in the top bar is displayed out of monitor bounds when opened

### ISSUE THREAD

**Issue by DWarez** [Jas-SinghFSU/HyprPanel#274]
**Describe the bug**
The notification menu in the top bar is displayed out of monitor bounds when opened.

**To Reproduce**
For me, it's necessary to simply click on the Notification Menu.

**Expected behavior**
The Menu should be displayed entirely in the monitor.

**Screenshots**
![image](https://github.com/user-attachments/assets/2a3b028e-6197-4d7f-9b79-7adb33ee64e9)

Ignore the flameshot errors, they are unrelated. I didn't cut the image, it's how I see it at the edge of the screen. Resizing from the settings doesn't change the behavior, only the size of the menu.

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment:. Hyprland

**Comment by Jas-SinghFSU** [comment]
Could you share with me your output of the following commands please:
```
hyprctl monitors
```
and
```
echo $GDK_SCALE
echo $GDK_DPI_SCALE
```

Hyprland is super weird with scaling and in certain configurations or HiDPI displays it decides to autoscale but the dimensions aren't properly aligned with the scaling it states.

I may have to just provide different scaling presets for this issue since there doesn't seem to be a one size fits all solution.

**Comment by DWarez** [comment]
> ```hyprctl monitors```

```
Monitor HDMI-A-5 (ID 0):
        3840x2160@59.99700 at 0x0
        description: LG Electronics LG HDR 4K 311MAQQKPP24
        make: LG Electronics
        model: LG HDR 4K
        serial: 311MAQQKPP24
        active workspace: 1 (1)
        special workspace: 0 ()
        reserved: 0 40 0 0
        scale: 1.33
        transform: 0
        focused: yes
        dpmsStatus: 1
        vrr: 0
        activelyTearing: false
        disabled: false
        currentFormat: A XRGB8888 H XRGB8888
        availableModes: 3840x2160@60.00Hz 3840x2160@59.94Hz 3840x2160@50.00Hz 3840x2160@29.97Hz 3840x2160@29.98Hz 3840x2160@25.00Hz 3840x2160@23.98Hz 2560x1440@59.95Hz 1920x1080@60.00Hz 1920x1080@60.00Hz 1920x1080@59.94Hz 1920x1080@50.00Hz 1920x1080@29.97Hz 1920x1080@23.98Hz 1280x720@59.94Hz 1024x768@60.00Hz 800x600@60.32Hz 720x576@50.00Hz 720x480@59.94Hz 640x480@59.94Hz 640x480@59.93Hz
```

using it in Hyprland with these settings:

`monitor = HDMI-A-5, 3840x2160@60, 0x0, 1.33`

> `echo $GDK_SCALE`

is set at 1 and

> `echo $GDK_DPI_SCALE`

is not set

**Comment by Jas-SinghFSU** [comment]
Can you go to `Configuration General > Scaling > Scaling Priority` and set the Scaling Priority to either `hyprland` or `both` and see if that fixes it for you? Most likely `hyprland` in your case.

**Comment by DWarez** [comment]
Thanks for the quick fix! However, it seems to not be consistent.

I set the scaling of the Notifications Menu to 65 and it was fully visible. However, after some Hyprland window operations (like opening and closing programs/windows), it seems like it moved, like this (sorry for the Spotify notification :sweat_smile:):

![image](https://github.com/user-attachments/assets/65fdfe4b-84d5-44cc-afe8-85fd10190942)

It´s kinda weird because when I first set the option the menu was aligned correctly, then it moved out of the screen (partially) again.

**Comment by Jas-SinghFSU** [comment]
When you change the scaling of your menus, it needs to recalculate the position (since dimensions changed) and the only way for it to do that is after the next render. So any time you change scaling, you'll notice that the next click spawns the menu at the wrong place. Subsequent clicks should resolve it - until you change the scaling of course.

Is it spawning properly though? With `100` scale (or w/e scale you prefer)?

**Comment by DWarez** [comment]
Ah, thanks for the explanation, it's exactly like you said. The first click after the rescaling spawns the menu in the wrong position, but the subsequent ones make the menu spawn in the correct one.
Therefore the issue is 100% fixed.

Thanks a lot, keep up the good work! :smile:

**Comment by Jas-SinghFSU** [comment]
Perfect!
