### ISSUE TITLE
Errors when launching  ags

### ISSUE THREAD

**Issue by Lurifixen** [Jas-SinghFSU/HyprPanel#275]
**Describe the bug**
```
(com.github.Aylur.ags:96164): Gjs-Console-CRITICAL **: 04:10:51.035: GLib.SpawnError: Failed to execute child process “bun” (No such file or directory)
proc@resource:///com/github/Aylur/ags/utils/exec.js:11:27
execAsync@resource:///com/github/Aylur/ags/utils/exec.js:77:19
@file:///home/luri/.config/ags/config.js:15:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
```

**To Reproduce**
Install packages with pacman & aur. Clone the repo and move to your config folder. Launch ags.

**Desktop (please complete the following information):**
 - Distribution: Arch linux
 - Window Manager/Desktop Environment: Hyprland

**Comment by Lurifixen** [comment]
I'm dumb and not reading correctly it seems. Forgot to install bun!

**Comment by Lurifixen** [comment]
I'm dumb and not reading correctly it seems. Forgot to install bun!

**Comment by decqyd** [comment]
i've got the same issue despite the fact i got bun installed, bit stuck
