### ISSUE TITLE
Idle Inhibitor Widget With Dynamic Icon

### ISSUE THREAD

**Issue by dotaxis** [Jas-SinghFSU/HyprPanel#276]
**Is your feature request related to a problem? Please describe.**
Waybar has an idle inhibitor widget which is very nice when on Zoom meetings or watching videos. AGS does not have an equivalent.

**Describe the solution you'd like**
I would very much like to see the ability to replace one of the buttons in the dashboard with one that toggles idle inhibiting with [matcha](https://codeberg.org/QuincePie/matcha)

**Describe alternatives you've considered**
A widget that goes along the top bar is fine too but I'd really like it in the dashboard

**Additional context**
This is kind of what I'm hoping to have, with an icon that reflects whether the inhibitor is active or not
![image](https://github.com/user-attachments/assets/17aa924a-a952-4629-941b-23082da852ac)

**Comment by Jas-SinghFSU** [comment]
Is this meant to prevent hypridle from triggering?

**Comment by Jas-SinghFSU** [comment]
Reason I ask is that matcha isn't easily downloadable as a package. You have to build it yourself from what I understand. So if we plan to integrate with swayidle or hypridle, we can do so without matcha and handle inhibiting rules.

**Comment by dotaxis** [comment]
> Is this meant to prevent hypridle from triggering?

Yes

**Comment by dotaxis** [comment]
> Reason I ask is that matcha isn't easily installable as a package. You have to build it yourself from what I understand. So if we plan to integrate with swayidle or hypridle, we can do so without matcha and handle inhibiting rules.

Even a script that kills/launches hypridle would be fine. 

I'm just struggling to make the icon/widget properly reflect the state of that which is why I made the feature request

**Comment by anotherhadi** [comment]
A solution would be to add an option where we can define commands that return a label (as in waybar)
So we could do something like `if pidof ...; then ... else ...` in bash and dynamically change the button label

**Comment by rubiin** [comment]
If you guys are using hyperidle, I could make a widget that would do that

**Comment by dotaxis** [comment]
I know how to write a bash script that toggles hypridle.

I want a widget that has a different icon depending on whether it is running or not.

**Comment by rubiin** [comment]
I guess you have to wait. I did have a rough implementation but it still lacks proper testing

**Comment by Lurgrid** [comment]
It would be amazing to be able to make custom modules

**Comment by dotaxis** [comment]
https://github.com/Jas-SinghFSU/HyprPanel/pull/502 addresses this perfectly although I'm not sure if you want to close this since the idea I had was to have it in the dashboard menu

**Comment by Jas-SinghFSU** [comment]
We can open a separate request for adding this in the dashboard.
