### ISSUE TITLE
Bar Layout Wildcard / Default Layout

### ISSUE THREAD

**Issue by LDAP** [Jas-SinghFSU/HyprPanel#284]
**Is your feature request related to a problem? Please describe.**
I'd like to set one layout for my primary monitor and a layout for every other monitor without needing to type the same for monitor 2, 3, ...

**Describe the solution you'd like**
Bar Layouts should be either split into default layout and monitor specific or accept a special character (preferably *) as wildcard.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Jas-SinghFSU** [comment]
You actually can use a wildcard already. That's on me for not documenting it, sorry. Go ahead and just define it once and instead of a number, put a * instead and that'll apply to all monitors.

**Comment by LDAP** [comment]
Oh that's fantastic! Does it also work if I mix numbers and wildcard?

**Comment by Jas-SinghFSU** [comment]
Yep :) 
https://github.com/Jas-SinghFSU/HyprPanel/pull/252

Example in the linked PR description.

**Comment by LDAP** [comment]
Thanks!
