### ISSUE TITLE
Store configuration as text file in `.config`

### ISSUE THREAD

**Issue by LDAP** [Jas-SinghFSU/HyprPanel#287]
**Is your feature request related to a problem? Please describe.**
I'd like to sync my config using Git or a dotfile manager or similar

**Describe the solution you'd like**
The config should be stored in `.config` and be suitable for dotfiles tools (not binary)

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Jas-SinghFSU** [comment]
You can export your config from Configuration > General > Export.
Same with theme in Theming > General  > Export

**Comment by LDAP** [comment]
I know that, but this is an extra step :(

**Comment by Jas-SinghFSU** [comment]
Maybe I can allow users to define a path to where the config is saved. By default it's in cache but maybe you want to store it in `~/.config/hyprpanel/options.json`. Would that suffice? That way you can simply sync you hyprpanel directory.

**Comment by LDAP** [comment]
That would be fantastic! :)

**Comment by victorballester7** [comment]
Yesss, loking forwards to see that!

**Comment by smathles** [comment]
Just crossed my mind, it would be awesome if this had dynamic application on save, like hyprland.conf does. Waybar you have to manually kill it and restart it every time you edit the file to see the change, *if* it's possible that would be super nice here too.

**Comment by rubiin** [comment]
Looking forward to this.
