### ISSUE TITLE
[BUG] Use 24hr time seems to not work

### ISSUE THREAD

**Issue by DWarez** [Jas-SinghFSU/HyprPanel#293]
The "Use 24hr time" setting under the Clock Menu configuration seems to not work.

Enable the "Use 24hr time" setting.

Clock should be displayed in 24hr time (no AM/PM indicator and hours from 00 to 23).

 - Distribution: Arch Linux
 - Window Manager/Desktop Environment:  Hyprland
 -  Tzdata version: `tzdata 2024b-2`

**Comment by Jas-SinghFSU** [comment]
This may be bad documentation on my part. That setting is only for the clock drop-down menu. Aka the menu that shows up when you clock the time module. 

To change your clock in the bar, you can go to Configuration > Bar > Clock and put in any time format. Here's more info on the formats: https://hyprpanel.com/configuration/panel.html#clock

**Comment by DWarez** [comment]
> This may be bad documentation on my part. That setting is only for the clock drop-down menu. Aka the menu that shows up when you click the time module.
> 
> To change your clock in the bar, you can go to Configuration > Bar > Clock and put in any time format. Here's more info on the formats: https://hyprpanel.com/configuration/panel.html#clock

I completely missed that setting. Thanks a lot :smile:
