### ISSUE TITLE
[BUG] Panel crashes after switching network using Network Widget

### ISSUE THREAD

**Issue by DWarez** [Jas-SinghFSU/HyprPanel#295]
Basically, title. 
It constantly happens to me, either if I need to insert a password to connect to the network or not. 

In order to replicate, I simply need to click on the Network Widget and click on a different connection from the shown list.
The widget doesn't make the panel crash if I don't switch connection.

Is this a known issue? Or is it something wrong with my configuration?

Distro: Arch Linux
WM: Hyprland

**Comment by Jas-SinghFSU** [comment]
This is a known issue and not the fault of your configuration. The network widget in AGS doesn't provide much in terms of allowing you to connect to networks so a lot of that is handled by Hyprpanel through nmcli.

I need to revisit the network module and possible rework it to be more robust.

**Comment by Jas-SinghFSU** [comment]
Could you do me a favor and run AGS in the terminal and provide the logs when it crashes please?

**Comment by DWarez** [comment]
I'd like to do that, but I can't seem to replicate the bug :sweat: 
Is there a log file I can consult (and report its content here) in the case of this bug happening again? Since I start `ags` using the Hyprland config, I don't have a terminal open with the command when using the system.

**Comment by Jas-SinghFSU** [comment]
```
exec-once = ags > ~/ags.log 2>&1
```
This might work, if you update your `ags` exec-once. Hopefully it saves your logs in ~/ags.log

**Comment by Jas-SinghFSU** [comment]
I'll be moving to AGSv2/astal when it's fully released and that has a much more complete network module.
