### ISSUE TITLE
[BUG] Hyprpanel crashes when switching workspaces with 'Lost connection to wayland compositor'

### ISSUE THREAD

**Issue by Jas-SinghFSU** [Jas-SinghFSU/HyprPanel#297]
**Describe the bug**
@piecuuu has mentioned that Hyprpanel crashes when in Minecraft full screen and switching to a different workspace when a notification is active (spotify for example).

The crash occurs with the error `Lost connection to wayland compositor`.

Need to reproduce and determine the culprit.

**Comment by Jas-SinghFSU** [comment]
@piecuuu Could you give me your config file? Go to settings > configuration > general > export. Be sure to remove your API key if you have it in there since that's the only sensitive information it contains.
```js
"menus.clock.weather.key": ""
```

**Comment by Jas-SinghFSU** [comment]
https://github.com/user-attachments/assets/a8612249-6ef0-4822-9302-829836580810

**Comment by Piecuuu** [comment]
> @Piecuuu Could you give me your config file? Go to settings > configuration > general > export. Be sure to remove your API key if you have it in there since that's the only sensitive information it contains.
> 
> ```js
> "menus.clock.weather.key": ""
> ```
> 
> I'm trying to replicate it in minecraft but having no luck.

[hyprpanel_config.json](https://github.com/user-attachments/files/17249608/hyprpanel_config.json)

**Comment by Jas-SinghFSU** [comment]
@Piecuuu Hey friend. While I try to replicate the crash, I remember you mentioning that your media menu was slow and showed up half a second later.

I have made some changes in branch `minor/strict_events`. Could you check out the branch and let me know if the menus are faster and more responsive for you please? No hurry, whenever you get a moment.

**Comment by Piecuuu** [comment]
> Could you check out the branch and let me know if the menus are faster and more responsive for you please? No hurry, whenever you get a moment.

I'd love to, but I can't use the latest HyprPanel, due to #291

**Comment by Jas-SinghFSU** [comment]
Shoot, orange will take a look at that later today based off of his comment in #291. Hopefully we can get it resolved then.

**Comment by Jas-SinghFSU** [comment]
I've merged the branch to improve drop-down performance. It's much faster now, just need to fix the nix issue.

**Comment by Jas-SinghFSU** [comment]
Going to close since we determined that this was because of musikcube right? Please reopen if I'm wrong about that.
