### ISSUE TITLE
CLI: Get status of window

### ISSUE THREAD

**Issue by anotherhadi** [Jas-SinghFSU/HyprPanel#298]
**Is your feature request related to a problem? Please describe.**
I'm creating a script that disable border rounding, gaps, etc to focus on my work and I want to hide my bar.
I currently just pkill ags but that's not very clean, and I can't use the "--toggle-window bar-0" because I don't know the status.

**Describe the solution you'd like**
A quick command that take the window name (bar-0, dashboard, ...) and return 0/1, true/false, ...
`hyprpanel -s (--status) [window]`

**Describe alternatives you've considered**
pgrep ags

**Comment by Jas-SinghFSU** [comment]
Added a cli command to check window status. Please refer to the description of the MR until I update the documentation for instructions.
https://github.com/Jas-SinghFSU/HyprPanel/pull/301
