### ISSUE TITLE
Transparency in buttons not applying to customeModules

### ISSUE THREAD

**Issue by victorballester7** [Jas-SinghFSU/HyprPanel#299]
**Describe the bug**
The opacity of the buttons (both when static and when hovering) does not apply to custom modules, and there is (to my knowledge) no other option to modify this.

**To Reproduce**
With this settings:
``` 
  "theme.bar.opacity": 60,
  "theme.bar.buttons.opacity": 100,
  "theme.bar.buttons.background_opacity": 0,
  "theme.bar.buttons.background_hover_opacity": 0,
```
and any of the custom modules added to your bar

**Expected behavior**
You will see the background of the button on those modules that are custom only. (see image below)

**Screenshots**
![image](https://github.com/user-attachments/assets/1f333190-7e7a-490c-9042-a5e33fa8a00e)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Comment by Jas-SinghFSU** [comment]
Fixed, please pull latest.

**Comment by victorballester7** [comment]
Perfect, thanks!
