### ISSUE TITLE
notifications for volume increase 

### ISSUE THREAD

**Issue by victorballester7** [Jas-SinghFSU/HyprPanel#302]
**Describe the bug**
Notifications appear as 'proper' notifcations as well as as OSD.

**To Reproduce**
It was automatic from the beginning I guess, but it doesn't happen when decreasing hte volume or modifying the brightness

**Expected behavior**
Just only display the OSD

**Screenshots**
![image](https://github.com/user-attachments/assets/091268b2-d0b2-4fce-922d-efcead984075)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Comment by Jas-SinghFSU** [comment]
Hyprpanel doesn't show notifications for volume. Are you sure you don't have a script bound to your volume keys to execute notifications?

**Comment by victorballester7** [comment]
Sorry, yes that's true. I forgot to comment a line. My bad. Thanks for the suggestion. I close the issue.
