### ISSUE TITLE
Cannot rebuild on NixOS since latest commit(s) (`expecting '}'`) 

### ISSUE THREAD

**Issue by Piecuuu** [Jas-SinghFSU/HyprPanel#306]
**Describe the bug**
Unable to build on NixOS
```
[piecuu@nixos-laptop ~/flake]% rb test
> Building NixOS configuration
warning: Git tree '/home/piecuu/flake' is dirty
error:
       … while calling the 'head' builtin
         at /nix/store/5cypwijbjdxmr4i7ckpq1in7f09547fc-source/lib/attrsets.nix:1575:11:
         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'
         at /nix/store/5cypwijbjdxmr4i7ckpq1in7f09547fc-source/lib/modules.nix:809:9:
          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: syntax error, expecting '}'
       at /nix/store/ws7m4xfr98yns7q7aqw6wxy50yhas9da-source/nix/default.nix:24:8:
           23|   libgtop,
           24|   gnome.gnome-bluetooth,
             |        ^
           25|   gobject-introspection,
Error:
   0: Command exited with status Exited(1)

Location:
   src/commands.rs:151
```

**To Reproduce**
- Add HyprPanel git to flake inputs 

**Expected behavior**
The HyprPanel flake builds

**Screenshots**

**Desktop (please complete the following information):**
 - Distribution: NixOS 24.05
 - Window Manager/Desktop Environment: Hyprland (N/A)

**Additional Information:**
Flake is public at https://git.piecuu.pl/Piecuu/nixos-flake

**Comment by Piecuuu** [comment]
@orxngc

**Comment by kashw2** [comment]
Reverting https://github.com/Jas-SinghFSU/HyprPanel/pull/305 will likely fix this issue. Not sure why the change to `gnome.gnome-bluetooth` was made as `gnome-bluetooth` won't be available under the `gnome` attrset soon and will just be `gnome-bluetooth` anyway.

**Comment by kmath313** [comment]
@kashw2 i am on unstable and gnome-Bluetooth is not under the gnome attrset here either.

**Comment by Jas-SinghFSU** [comment]
I've merged the MR made by @kashw2 to revert the `gnome.` prefix. If this issue persists I'll probably need you to reopen this and get some help from those of you folks who use Nix.
