### ISSUE TITLE
Flake doesn't build on NixOS (`required argument "gnome-bluetooth"`)

### ISSUE THREAD

**Issue by Piecuuu** [Jas-SinghFSU/HyprPanel#311]
**Describe the bug**
You've heard it a million times already, it doesn't build on NixOS
```
warning: Git tree '/home/piecuu/flake' is dirty
building the system configuration...
warning: Git tree '/home/piecuu/flake' is dirty
error:
       … while calling the 'head' builtin
         at /nix/store/5cypwijbjdxmr4i7ckpq1in7f09547fc-source/lib/attrsets.nix:1575:11:
         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'
         at /nix/store/5cypwijbjdxmr4i7ckpq1in7f09547fc-source/lib/modules.nix:809:9:
          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "gnome-bluetooth" at /nix/store/y9dja4p08an2xdvnw3lp2nqiiibd9pk7-source/nix/default.nix:24'
```

**To Reproduce**
- Use NixOS 24.05
- Get the HyprPanel flake
- Try Rebuilding

**Expected behavior**
Flake builds and system rebuilds correctly

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Distribution: NixOS 24.05, Lix 2.91.0
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
Flake at https://git.piecuu.pl/Piecuu/nixos-flake

**Comment by Piecuuu** [comment]
So, I've fixed it by removing the hyprpanel overlay and installing it with the "typical flake way" and it worked! I haven't yet pushed my flake to my git repo, but i'm sure you'll figure it out (raf thanks bae kisses to you mwah)

**Comment by madfanat** [comment]
> So, I've fixed it by removing the hyprpanel overlay and installing it with the "typical flake way" and it worked! I haven't yet pushed my flake to my git repo, but i'm sure you'll figure it out (raf thanks bae kisses to you mwah)

Hi! Could you please share the code for “typical flake way” installtion? Facing the same problem and can't get it working.

**Comment by Piecuuu** [comment]
> > So, I've fixed it by removing the hyprpanel overlay and installing it with the "typical flake way" and it worked! I haven't yet pushed my flake to my git repo, but i'm sure you'll figure it out (raf thanks bae kisses to you mwah)
> 
> Hi! Could you please share the code for “typical flake way” installtion? Facing the same problem and can't get it working.

Sure, so, what you're gonna do is remove the nixpkgs overlay of hyprpanel, remove `hyprpanel` from your packages and then add `inputs.hyprpanel.packages."${pkgs.system}".default` to your packages

**Comment by madfanat** [comment]
> > > So, I've fixed it by removing the hyprpanel overlay and installing it with the "typical flake way" and it worked! I haven't yet pushed my flake to my git repo, but i'm sure you'll figure it out (raf thanks bae kisses to you mwah)
> > 
> > 
> > Hi! Could you please share the code for “typical flake way” installtion? Facing the same problem and can't get it working.
> 
> Sure, so, what you're gonna do is remove the nixpkgs overlay of hyprpanel, remove `hyprpanel` from your packages and then add `inputs.hyprpanel.packages."${pkgs.system}".default` to your packages

Ah, thanks for the reply. Will check if it works for me.

**Comment by madfanat** [comment]
> inputs.hyprpanel.packages."${pkgs.system}".default

Well, if I add this to home.packages, I get
<details>
  <summary>this error</summary>

```
error:
       … while calling the 'head' builtin

         at /nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source/lib/modules.nix:816:9:

          815|     in warnDeprecation opt //
          816|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          817|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: The option `home-manager.users.tim.programs.hyprpanel' does not exist. Definition values:
       - In `/nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source/flake.nix':
           {
             enable = true;
           }
```
</details>

And if I add this to imports then I get

<details>
  <summary>this error</summary>

```
error:
       … while calling the 'head' builtin

         at /nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source/lib/modules.nix:816:9:

          815|     in warnDeprecation opt //
          816|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          817|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: infinite recursion encountered

       at /nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source/lib/modules.nix:515:28:

          514|         addErrorContext (context name)
          515|           (args.${name} or config._module.args.${name})
             |                            ^
          516|       ) (functionArgs f);
```

</details>
Am I missing something?
