### ISSUE TITLE
Hide battery percentage when full

### ISSUE THREAD

**Issue by paiyayay** [Jas-SinghFSU/HyprPanel#313]
As title says it is a feature request.

It might be better to give users to change what their full charge is, in percentages. Some people like me limits the battery to charge up to 80%.

Additional input field can be given, if it is 0 disable this feature if it is not then enable.

**Comment by anotherhadi** [comment]
Did you mean hide the module or just hide "100%" and let the icon?

**Comment by paiyayay** [comment]
Yes I meant that.

**Comment by rubiin** [comment]
Yeah will update that and setting custom battery full % on next pr
