### ISSUE TITLE
Window autoreinitialization on monitor change

### ISSUE THREAD

**Issue by M0NsTeRRR** [Jas-SinghFSU/HyprPanel#318]
**Is your feature request related to a problem? Please describe.**
When a new monitor is connected to a computer hyprpanel needs a restart

**Describe the solution you'd like**
If possible hyprpanel could handle it itself

**Describe alternatives you've considered**
Make a script to handle it.

**Comment by Jas-SinghFSU** [comment]
implemented in #432
