### ISSUE TITLE
Bar overflow moves notifications off screen

### ISSUE THREAD

**Issue by smathles** [Jas-SinghFSU/HyprPanel#32]
**Describe the bug**
When a particularly long window name is encountered, filling all the available bar space, HyprPanel prefers to start pushing bar entries (such as the notifications icon) off of the screen instead of only displaying a portion of the window name.

**To Reproduce**
Use default bar configuration (on some monitors at least), open a long-named window.

**Expected behavior**
I would expect for very long-named windows, HyprPanel would prefer shortening the displayed name instead of pushing entries off of the screen.

**Screenshots**
Good behaviour:
![snapshot_2024-07-29_12-20-28](https://github.com/user-attachments/assets/4c91e388-b740-4c92-bfea-e3aea4ed35ad)

Bad behaviour:
![snapshot_2024-07-29_12-21-07](https://github.com/user-attachments/assets/f922efca-050c-4f4f-9169-b56a3b1662c0)

**Desktop (please complete the following information):**
- Arch linux + hyprland, latest.
- Plasma 6 with 150% scaling installed beside hyprland.
- 1920x1080 resolution, (probably being shown as 1280x720 from plasma scaling).
- `$GTK_SCALING` is not set to anything.

**Additional context**
You can do a dirty workaround by removing battery percentage status, date from widgets etc, and more space appears. Definitely a stopgap solution though.

**Comment by orxngc** [comment]
This appears to be the same issue as #28 .

**Comment by smathles** [comment]
I'm still experiencing this bug, after pull #49 even if only on higher scaling. I don't think it's quite the same thing as #28, as I can confirm that #28 is completely solved by this (even when the notifications icon is pushed halfway off the screen, the popup works correctly). 
I think that the notification widget should be restricted from movement somehow, as I can still overflow it.

![image](https://github.com/user-attachments/assets/c2807f09-c3d3-42fa-9143-6339b1752f55)

Note that despite the bar overflow still happening, the panel is now correctly inside the screen as per pull #49.
