### ISSUE TITLE
[BUG] Types symlink don't work on Nix

### ISSUE THREAD

**Issue by Ciflire** [Jas-SinghFSU/HyprPanel#327]
**Describe the bug**
The `types` folder cannot be linked to anything `/usr/lib` or anything there

**To Reproduce**
Clone on Nix

**Expected behavior**
I don't know if you want to take this into account, personnaly i would like not to clone it and set this up myself, adding this setup step to a contributing section, there might also be some extra steps like a `bun install` so one more command might not be that bad to be sure it works everywhere

**Desktop (please complete the following information):**
 - Distribution: NixOS
 - Window Manager/Desktop Environment: Hyprland

**Comment by Jas-SinghFSU** [comment]
Are you saying to remove the types reference `/types` from the repo?

**Comment by Ciflire** [comment]
There might be some use of that file i don't see to this file, but to me when i clone that's just a dead symlink, so yes I am saying to remove this reference
Maybe a shellhook could fix it, but that would mean it's gonna link it on every devshell activation
