### ISSUE TITLE
Weather Icons display as squares

### ISSUE THREAD

**Issue by NotJoeMama727** [Jas-SinghFSU/HyprPanel#33]
**Describe the bug**
The weather and sleep icon (which uses a weather icon) show as simple black squares

**To Reproduce**
This behavior occurs constantly 

**Expected behavior**
Show the correct weather icons 

**Screenshots**
![image](https://github.com/user-attachments/assets/e8244857-5925-4d68-bf5a-820c3ae61c17)
![image](https://github.com/user-attachments/assets/4a1c1389-f12f-4fbe-840c-bb6fdd26732d)

**Desktop (please complete the following information):**
 - EndeavourOS
 - Hyprland

**Additional context**
I have got nerd fonts installed

**Comment by Jas-SinghFSU** [comment]
These icons are based off of your system's icon theme. It may be that the theme is missing the required icons. Could you tell me which icon theme it is that you're using; and if possible try a different icon theme and see if the issue persists?

**Comment by NotJoeMama727** [comment]
Currently using breeze dark. I can confirm that switching to adwaita or qogir makes the icons show up

**Comment by Jas-SinghFSU** [comment]
Ah gotcha, in that case you may have to reinstall or update Breeze Dark. In either case I'll close the issue since it isn't a HyprPanel related issue.
