### ISSUE TITLE
Can't Catch notifications from some applications

### ISSUE THREAD

**Issue by iamthen0ise** [Jas-SinghFSU/HyprPanel#330]
**Describe the bug**
I'm experiencing an issue where notifications from various applications do not appear in the AGS widgets. For example, this one https://aur.archlinux.org/packages/pachca-bin

**To Reproduce**
--
**Expected behavior**
Notifications from apps should appear in Notifications widget as intended.

**Screenshots**
---

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
I am new to AGS, so can't even check whether daemon or script handles notifications from any app. Appreciate any help with debug. Thank you!

**Comment by Jas-SinghFSU** [comment]
Was this closed because it's not a bug? @iamthen0ise

**Comment by iamthen0ise** [comment]
> Was this closed because it's not a bug? @iamthen0ise

yes, not a HyprPanel bug at all. 3rd party app problem.
