### ISSUE TITLE
feature: backlight component

### ISSUE THREAD

**Issue by rubiin** [Jas-SinghFSU/HyprPanel#340]
**Is your feature request related to a problem? Please describe.**
Add a component that controls backlight using brightnessctl

**Add a component that controls backlight using brightnessctl
Describe the solution you'd like**

**Describe alternatives you've considered**
I have a rough implementation already made

**Additional context**

**Comment by smathles** [comment]
Is this best as a separate module?
Haven't thought through it too hard, but I think it would look nice as a slider above/below the screen brightness slider in the battery module.

What do you reckon?

**Comment by rubiin** [comment]
Yeah a slider. with hover scroll feature would be best.

**Comment by smathles** [comment]
Yeah cool. I remember having this feature on waybar, haven't bothered tinkering with it for a while.
IMO both options would be great, scrollable module for quick access, but possibly a slider in the battery menu that could be toggled on in settings would be nice too!

Keybinds are a thing too I guess, but idrc.

**Comment by rubiin** [comment]
I think we already have the slider under power but wouldnt hurt to keep it here too IG

**Comment by smathles** [comment]
Pretty sure it only works for monitor brightness in the current battery module. I know in Gnome there's a slider both for monitor and keyboard backlight brightness, that's more what I'm thinking.

I'm okay with a separate module too if anyone finds it useful, I guess I just tend to have less modules on my bar.

Adding both could be good, then we can choose either way.

**Comment by rubiin** [comment]
lets track it here https://github.com/Jas-SinghFSU/HyprPanel/issues/176
