### ISSUE TITLE
[Bug] Custom Modules don't follow button background

### ISSUE THREAD

**Issue by zDyanTB** [Jas-SinghFSU/HyprPanel#353]
Custom modules don't follow button background opacity
![image](https://github.com/user-attachments/assets/c7c3d1a5-7189-43fb-9b97-dab4a0e80f3d)

 - Distribution: NixOs
 - Window Manager/Desktop Environment: Hyprland

**Comment by Jas-SinghFSU** [comment]
This should have been fixed by #300
Try to pull latest version.

**Comment by zDyanTB** [comment]
Same, maybe it's a problem with my nix, will close for now
