### ISSUE TITLE
[req]  use the '.face.icon' for profile image when detected 

### ISSUE THREAD

**Issue by kRHYME7** [Jas-SinghFSU/HyprPanel#359]
**Is your feature request related to a problem? Please describe.**

Adding an option to use `~/.face.icon`  fo unset "Profile Image"

**Describe the solution you'd like**

Some DE and display manager uses this file to detect the profile image of a user to be displayed in lock screen or in a DM

**Describe alternatives you've considered**
Use `  ~/.face/icon `  when available and none is set 
If did not exist use the Hyprpanel logo. 

**Additional context**
![image](https://github.com/user-attachments/assets/0f7c1aac-32ec-4be9-9074-8a65886f957d)

**Comment by rubiin** [comment]
I did fix this. Was easy enough

**Comment by rubiin** [comment]
More context: https://askubuntu.com/questions/114060/what-is-face-binary

**Comment by kRHYME7** [comment]
@rubiin  Question is does  ` ~/.face  `  & `~/.face.icon`  should work ? 
Or 
`~/.face ` -> Gnome -> GDM 
`~/.face.icon`  - > KDE -> SDDM
