### ISSUE TITLE
Adding a persistent configuration file which contains our preferences

### ISSUE THREAD

**Issue by Keremimo** [Jas-SinghFSU/HyprPanel#36]
**Is your feature request related to a problem? Please describe.**
I could not find where the preferences are stored, but related to this, it would be nice to have a file that we could add to our dotfiles for persistence of settings. As of now I cannot move my setup from one PC to another.

**Describe the solution you'd like**
Adding a file in the .config folder like ags.conf which contains our preferences.

**Describe alternatives you've considered**
A JSON or TS file would also suffice. Thanks!

**Comment by Jas-SinghFSU** [comment]
This is definitely a planned feature. In the meantime you can back up this file: `/tmp/ags/hyprpanel/config.json`. As that's your current configuration.

**Comment by Keremimo** [comment]
That works for me until a more permanent solution is made. Thanks!

**Comment by orxngc** [comment]
> This is definitely a planned feature. In the meantime you can back up this file: `/tmp/ags/hyprpanel/config.json`. As that's your current configuration.

I was backing up `~/.cache/ags/HyprPanel/options.json` till now, is there a difference between the two?

**Comment by matavach** [comment]
> This is definitely a planned feature. In the meantime you can back up this file: `/tmp/ags/hyprpanel/config.json`. As that's your current configuration.

Why not overwrite "options.ts" with the config menu choices?
You can save a default copy of "options.ts" for a restore to default if needed.

**Comment by Jas-SinghFSU** [comment]
> I was backing up `~/.cache/ags/HyprPanel/options.json` till now, is there a difference between the two?
The cache file is as the name implies. It's the file that persists between sessions and updates whenever an option is changed in the dialog. The `/tmp/` file is the runtime file which actually changes  your environment.

Long story short, you should be backing up your `cache` file as those are the settings that are pulled in when HyprPanel is initialized; so ignore my advice about the `/tmp/`.  Of course if you want to apply those changes after pasting the contents or replacing your cache file, you'd have to restart HyprPanel.

**Comment by Jas-SinghFSU** [comment]
@Keremimo Implemented via #120. Themes and Configs can now be imported and exported. Some themes are already provided out of the box and exist in the `themes` directory of the repo.

**Comment by Keremimo** [comment]
That's awesome, thank you for your efforts!
