### ISSUE TITLE
CPU and Memory values not shown at the Dashboard.

### ISSUE THREAD

**Issue by RoccoRakete** [Jas-SinghFSU/HyprPanel#363]
**Describe the bug**
Both Values are always at 0%

**To Reproduce**
Start AGS

**Expected behavior**
Values should be shown.

**Screenshots**
![image](https://github.com/user-attachments/assets/8e936fa0-5695-4cc1-870d-634cdb443513)

**Desktop (please complete the following information):**
 - Distribution: ArchLinux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
I'm not afraid to edit code :)

**Comment by rubiin** [comment]
Thats odd. Working on mine.
![image](https://github.com/user-attachments/assets/2dc68047-7caa-4d1a-afbb-6d6067e02451)

**Comment by Jas-SinghFSU** [comment]
@RoccoRakete could you verify that the cpu and ram bar modules work? I need to update the dashboard to use the bar modules logic which is significantly more robust.

**Comment by RoccoRakete** [comment]
Indeed they work!

**Comment by Jas-SinghFSU** [comment]
I'll fix these later today. Thanks for confirming.

**Comment by RoccoRakete** [comment]
No problem :) I have to thank you!

**Comment by Jas-SinghFSU** [comment]
You should be able to pull latest branch and have them working now.
