### ISSUE TITLE
Bug: workspace

### ISSUE THREAD

**Issue by rubiin** [Jas-SinghFSU/HyprPanel#364]
**Describe the bug**
HideUnOccupied still shows the unoccupied workspace

**To Reproduce**

Toggle hideUnOccupied slider.

**Expected behavior**

**Screenshots**

Hide unoccupied options should just list the occupied workspaces only. Here is the comaprision with waybr

![image](https://github.com/user-attachments/assets/55575021-c86e-433f-9e16-efde4d8e8edc)

**Desktop (please complete the following information):**
 - Distribution: [e.g. Arch Linux]
 - Window Manager/Desktop Environment: [e.g. Hyprland]

**Additional context**

**Comment by Jas-SinghFSU** [comment]
Make sure to reduce the minimum workspaces to 0. Otherwise you will always have the specified number of workspaces visible regardless of if they're hidden or not.

**Comment by rubiin** [comment]
Doesnt flinch even with setting zero
![image](https://github.com/user-attachments/assets/71fe9571-fe85-47bd-a852-cb95ee678991)

**Comment by Jas-SinghFSU** [comment]
In the snapshots it seems you don't have the setting enabled. You only have 'Monitor Specific' enabled.

**Comment by rubiin** [comment]
I think we have to update the label on hide unoccupied  `Make sure to reduce the minimum workspaces to 0.`

**Comment by Jas-SinghFSU** [comment]
Yeah there has to be a more intuitive way for these 2 options to work together. You're not the first to run into this and won't be the last. I wonder of the best approach is to just lower the static workspace number to 5 and add a subtitle to the autohide?

**Comment by rubiin** [comment]
Yeah that should help mitigate the issue a bit if not all
