### ISSUE TITLE
Matugen - Workspace available and occupied color is the same

### ISSUE THREAD

**Issue by Nocxium** [Jas-SinghFSU/HyprPanel#370]
Hi. Im getting the same color for "workspace available" and "workspace occupied" color with matugen. I assume this is a bug?

Im on NixOS if that matters.

**Comment by Jas-SinghFSU** [comment]
Matugen can only generate 3 colors and depending on which variation of Matugen you choose, it's possible that it applies the same colors. You'd have to use something other than colors to determine active workspaces: highlights, underlines or icons.
