### ISSUE TITLE
[BUG?] Hyprpanel sleep with hyprlock is not working

### ISSUE THREAD

**Issue by notquitethereyet** [Jas-SinghFSU/HyprPanel#373]
**Describe the bug**
Suspend from hyprpanel does not seem to work. 

**To Reproduce**
Launch hyprpanel using ags like usual. Then click on "sleep" which is hyprpanel's way of suspending ig.

**Expected behavior**
Suspend system like normal

**Screenshots**
N/A here

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**

launched ags from the terminal and clicked the sleep button. This was the log:
```
❯ ags

(com.github.Aylur.ags:14682): Gjs-WARNING **: 13:09:32.028: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
execAsync@resource:///com/github/Aylur/ags/utils/exec.js:78:12
exec@file:///tmp/ags/hyprpanel/main.js:7102:11
Button/<@resource:///com/github/Aylur/ags/widgets/button.js:31:44
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34

```

**Comment by Jas-SinghFSU** [comment]
Are you able to suspend via this command?
```
systemctl suspend
```
This is what the sleep command runs essentially.

**Comment by notquitethereyet** [comment]
Yes, I have a wlogout module that uses `hyprlock & disown && systemctl suspend`
Also running it in the terminal works too

**Comment by Jas-SinghFSU** [comment]
Could you do me a favor and see what command is supplied to the sleep button?

Configuration > Dashboard Menu > Sleep Command

**Comment by notquitethereyet** [comment]
it had `systemctl suspend` but it wont trigger the lockscreen. so i changed it to `hyprlock & disown && systemctl suspend`

**Comment by Jas-SinghFSU** [comment]
Nice! I imagine that means it's working properly?

**Comment by notquitethereyet** [comment]
uhhh yeah ig. my bad for not explaining the issue properly. is there any way to trigger the lockscreen before suspend from the hyprpanel dash? suspend through wlogout works fine with the same command

**Comment by Jas-SinghFSU** [comment]
Hmm... the panel doesn't run any logic, it simply executes the command in bash. I'm not entirely sure why the same command works in your terminal/wlogout but not hyprpanel.

**Comment by yorunoken** [comment]
`systemctl suspend` by itself shouldn't trigger any lockscreens.

**Comment by notquitethereyet** [comment]
@yorunoken yes, I'm aware. I'm just trying to figure out a way to run hyprlock and then suspend like how wlogout does

**Comment by yorunoken** [comment]
you could simply make it run a bash file

**Comment by notquitethereyet** [comment]
good idea. thanks
