### ISSUE TITLE
[Feature] Clear notification with right click

### ISSUE THREAD

**Issue by chucklefart** [Jas-SinghFSU/HyprPanel#378]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When there is a notification popup right clicking will clear it.

**Describe alternatives you've considered**
There's already a clear button on notifications, so just triggering the clear on a right click anywhere should be easy enough to implement.

**Additional context**
N/A

**Comment by rubiin** [comment]
@Jas-SinghFSU should this be default behaviour?
