### ISSUE TITLE
[Feature] Manally trigger check for updates

### ISSUE THREAD

**Issue by chucklefart** [Jas-SinghFSU/HyprPanel#379]
**Is your feature request related to a problem? Please describe.**
When performing updates, it can take quite a while for the update count in the bar to reset.
Being able to trigger a manual refresh after updating would solve this

**Describe the solution you'd like**
Have a command to manually trigger an update check.
This can then be hooked into pacman to run after each update or similar.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Jas-SinghFSU** [comment]
Doing any actions (left/right/middle click, scroll) on the button now automatically trigger an updated value after the script defined for those actions is run.
