### ISSUE TITLE
OSD obstructing screen when not showing

### ISSUE THREAD

**Issue by NotJoeMama727** [Jas-SinghFSU/HyprPanel#38]
**Describe the bug**
The OSD will obstruct the user from interacting with the screen below the location of the OSD when it is not showing

**To Reproduce**
Move cursor to the location the OSD usually is

**Expected behavior**
The OSD will allow the user to press under it when not displaying

**Desktop (please complete the following information):**
 - EndeavourOS
 - Hyprland

**Additional context**
This issue does not come up when the OSD is disabled

**Comment by Jas-SinghFSU** [comment]
Leaving a note from the pull request here. I have fixed this issue temporarily by release the mouse events once the OSD is hidden. 

NOTE: The current Gtk component called 'Overlay' can allow click through events, but this component breaks the moment you change ANYTHING about it. In other words, if you: change your overlay to a different monitor, resize it, change margins, change orientation it will then stop allowing passthroughs and we're back to square one.

This PR hides the entire window once the OSD is hidden, as a workaround for now. I will have to spend more digging to find a better solution but I also don't want it hijacking the screen of users, so this will do for now.
