### ISSUE TITLE
Bar not start, critical errors

### ISSUE THREAD

**Issue by Al3xxx84** [Jas-SinghFSU/HyprPanel#382]
**Describe the bug**
Bar dont start with ags command

**To Reproduce**
Type ags

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
Errors from terminal:

(com.github.Aylur.ags:9399): Gjs-Console-CRITICAL **: 13:42:35.760: net.hadess.PowerProfiles is not available

(com.github.Aylur.ags:9399): Gjs-Console-CRITICAL **: 13:42:35.921: TypeError: foundPlayer is undefined
Bar2/setup/<@file:///tmp/ags/hyprpanel/main.js:9033:19
poll/<@resource:///com/github/Aylur/ags/widgets/widget.js:67:41
interval@resource:///com/github/Aylur/ags/utils/timeout.js:3:5
poll@resource:///com/github/Aylur/ags/widgets/widget.js:67:17
setup@file:///tmp/ags/hyprpanel/main.js:9031:18
_init@resource:///com/github/Aylur/ags/widgets/widget.js:115:18
Slider@resource:///com/github/Aylur/ags/widgets/slider.js:27:9
newSlider@resource:///com/github/Aylur/ags/widgets/slider.js:10:12
Bar2@file:///tmp/ags/hyprpanel/main.js:9018:23
Media2@file:///tmp/ags/hyprpanel/main.js:9071:53
media_default@file:///tmp/ags/hyprpanel/main.js:9108:16
@file:///tmp/ags/hyprpanel/main.js:11133:3
async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Box 0x631ba1c2fb90.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Label 0x631ba2632b60.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Label 0x631ba2632b60.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Box 0x631ba204f5e0.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Label 0x631ba1c3c710.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Label 0x631ba1c3c710.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Box 0x631ba2dc42d0.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Label 0x631ba2281880.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Label 0x631ba2281880.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Box 0x631ba2e61a30.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Box 0x631ba2ca4ad0.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Button 0x631ba2ea36d0.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.926: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Button 0x631ba2ea36d0.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Icon 0x631ba2ea2590.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Button 0x631ba2e6cd90.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Button 0x631ba2e6cd90.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Icon 0x631ba2ca5740.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Button 0x631ba1365960.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Button 0x631ba1365960.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Icon 0x631ba2cf2cc0.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Icon 0x631ba2cf2cc0.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Box 0x631ba2df41e0.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Button 0x631ba2e5be40.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Button 0x631ba2e5be40.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Icon 0x631ba2e5ab20.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Box 0x631ba3c5f720.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Button 0x631ba2df5dc0.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Button 0x631ba2df5dc0.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Icon 0x631ba2df4ed0.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.927: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Icon 0x631ba2df4ed0.
== Stack trace for context 0x631ba0fdbe50 ==

(com.github.Aylur.ags:9399): Gjs-CRITICAL **: 13:42:35.946: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was access-point-removed on NMDeviceWifi 0x631ba1b90a20.
== Stack trace for context 0x631ba0fdbe50 ==

**Comment by linkosaur4480** [comment]
Experiencing the same issue

**Comment by theeddiestudio** [comment]
same here. not gonna create a new issue. the whole panel is broken with the new update. it was working fine last time.

**Comment by Jas-SinghFSU** [comment]
Woops, sorry about that. This should be fixed.

**Comment by dbl-hoo** [comment]
I see that this should be fixed, but I am having this same issue.

**Comment by Jas-SinghFSU** [comment]
@dbl-hoo could you share your logs and your commit hash please?

**Comment by Sumanthbhumi** [comment]
got the same error, but after clearing the ags cache with `ags --clear-cahce` it worked
