### ISSUE TITLE
Hyprland does NOT launch it automatically at exec-once.

### ISSUE THREAD

**Issue by enessmr** [Jas-SinghFSU/HyprPanel#388]
**Describe the bug**
Hyprland does not launch it automatically after start.

**To Reproduce**
Split config files
Move the user to another one and cancel at some point
Stop SDDM (optinoal)
Do it again and it will give a error
Start SDDM with SystemCTL
Log in.
ags will fail to load a JS file.
Recompile it again
log out and log in
Not launching except kitty (manual, no exec-once.)

**Expected behavior**
Normally launch

**Screenshots**
(no screenshot :(((( )

**Desktop (please complete the following information):**
 - Distribution: Arch Linux (originally 6.11.4-arch1-1, upgraded to 6.11.5-arch-1-1)
 - Window Manager/Desktop Environment: Hyprland (latest git)

**Additional context**

**Comment by Jas-SinghFSU** [comment]
Could you update your `exec-once` to this please:
```
exec-once = ags > ~/ags_logs.txt 2>&1
```

Then provide the logs that show up in your `~/ags_logs.txt` file.

**Comment by rx3lixir** [comment]
@Jas-SinghFSU Got the same issue, here's logs:
---
(com.github.Aylur.ags:1173): Gjs-Console-CRITICAL **: 23:14:27.913: GLib.SpawnError: Failed to execute child process “bun” (No such file or directory)
proc@resource:///com/github/Aylur/ags/utils/exec.js:11:27
execAsync@resource:///com/github/Aylur/ags/utils/exec.js:77:19
@file:///home/rx3lixir/.config/ags/config.js:15:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
---
Same distro, same wm

**Comment by Jas-SinghFSU** [comment]
@rx3lixir Could you verify that bun is installed please? https://hyprpanel.com/getting_started/installation.html#bun

Also if I may have the output of your following command:
```
which bun
```

**Comment by rx3lixir** [comment]
@Jas-SinghFSU yep, bun is installed for sure, thank u for your respond, here's output

```
❯ bun --version
1.1.33
❯ which bun
/home/rx3lixir/.bun/bin/bun

```

**Comment by Haraven** [comment]
Same issue here on a fresh install of HyprPanel, with all required dependencies installed beforehand.

**Comment by Jas-SinghFSU** [comment]
@rx3lixir can you re run this command (may require sudo)
```
sudo ln -s $HOME/.bun/bin/bun /usr/local/bin/bun
```

And try again? It can't seem to find bun when launching through exec-once.

**Comment by rx3lixir** [comment]
now we're talking. thanks a lot for your investigation everything works finee

**Comment by Jas-SinghFSU** [comment]
Yay :tada: !!

**Comment by SpyPower** [comment]
Came into this requirement myself as well. Bun was not installed as i am not using javascript. Shouldn't that be on the requirements?

**Comment by rx3lixir** [comment]
@SpyPower actually bun is a key dependency on hyprpanel and moreover this installation script is provided by the docs, I personally don't know how I missed symlink part or mb something went wrong ![image](https://github.com/user-attachments/assets/3026e416-da37-4707-b200-f0c700e52ba3)

**Comment by enessmr** [comment]
logging out and in, cancelling my android build.

**Comment by enessmr** [comment]
Logged in and

(com.github.Aylur.ags:281660): Gjs-Console-CRITICAL **: 23:16:00.183: GLib.SpawnError: “bun” alt süreç çalıştırılamadı (Böyle bir dosya ya da dizin yok)
proc@resource:///com/github/Aylur/ags/utils/exec.js:11:27
execAsync@resource:///com/github/Aylur/ags/utils/exec.js:77:19
@file:///home/hyprlanduser/.config/ags/config.js:15:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  
BUN DOES NOT EXIST???
I symlinked bun! I think .bashrc executes too late...

**Comment by enessmr** [comment]
So the fix is should i edit my hyprland config then source bashrc?

**Comment by enessmr** [comment]
(com.github.Aylur.ags:286094): Gjs-Console-CRITICAL **: 23:24:13.092: GLib.SpawnError: “bun” alt süreç çalıştırılamadı (Böyle bir dosya ya da dizin yok)
proc@resource:///com/github/Aylur/ags/utils/exec.js:11:27
execAsync@resource:///com/github/Aylur/ags/utils/exec.js:77:19
@file:///home/hyprlanduser/.config/ags/config.js:15:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
  

NO.. sourced bashrc in hyprland and it did not work.

I think it uses fish instead ☹️

**Comment by enessmr** [comment]
yay

Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
hyprlanduser@archuser ~> bash -c
bash: -c: seçenek bir argüman gerektiriyor
hyprlanduser@archuser ~ [2]> bash -c "ags"
Ags with busname "ags" is already running
hyprlanduser@archuser ~> bash -c "ags"
,Ags with busname "ags" is already running
hyprlanduser@archuser ~>

**Comment by enessmr** [comment]
so i think, this is solved.

**Comment by enessmr** [comment]
Solved.

# How to solve this in the future

Delete symbolic linked bun
Rerun the install command again

# Will your Config stay?

Yes.

**Comment by enessmr** [comment]
proof: (just a empty desktop)
![snapshot_2024-11-02_23-42-12](https://github.com/user-attachments/assets/2ffd82fc-b218-489c-879f-af2b1b7a77ee)
