### ISSUE TITLE
[Feature] option to render empty workspaces in the bar

### ISSUE THREAD

**Issue by albohlabs** [Jas-SinghFSU/HyprPanel#395]
I would like to have an option to enable empty workspaces to be displayed in the bar in front of a non-empty workspace.

Let's say I have an existing Firefox client on workspace 3.
Currently, only this one workspace is rendered in the bar.

What I want is to have the 2 empty workspaces rendered before it.

The reason for this is that I use shortcuts like ctrl + 1 to jump to workspaces. If the empty workspaces are rendered before a non-empty one, it would be easier to find the corresponding shortcut.

**Comment by Jas-SinghFSU** [comment]
Would this be satisfied by upping the number of `Total Workspaces` in `Configuration > Bar`?

That number forces N number of workspaces to always show. So you can set it to 2 in this case, so it always shows the first 2.

**Comment by albohlabs** [comment]
Setting the workspaces to 9 would be a workaround for me and I could live with that. 

But just to illustrate the behaviour a bit more, if I have a hpyrland client open on workspace 5, then workspace 4 is not rendered. So again, I could not see the empty workspace in between.

But as I said, I could live with setting the total number of workspaces to 9 as a workaround. The question for me was, does it make sense for you to implement this feature into the codebase?

**Comment by Jas-SinghFSU** [comment]
Ahhh I think I understand what you mean. You want to show all workspaces prior to your higher workspace at all times?

**Comment by albohlabs** [comment]
Yessss, that is exactly the behaviour i want. What do you think about adding it?

**Comment by Jas-SinghFSU** [comment]
Yeah, that should be doable and probably useful. I'll look into adding it.

**Comment by albohlabs** [comment]
I can also have a look at it and create a MR?

**Comment by Jas-SinghFSU** [comment]
> I can also have a look at it and create a MR?

Most welcomed to ❤️

**Comment by Daholli** [comment]
This can also be done by "assigning" workspaces to a monitor such as
```
workspace=1, monitor:DP-2
workspace=2, monitor:DP-2
workspace=3, monitor:DP-2
workspace=4, monitor:DP-2
```
in your hyprland config, this will make it so they always show up regardless if they have a window in them or not
