### ISSUE TITLE
[Question] Configuration file in `~/.cache` instead of the usual `~/.config`

### ISSUE THREAD

**Issue by Ptitet** [Jas-SinghFSU/HyprPanel#397]
I just installed HyprPanel and made some configuration using the GUI, and then I wanted to backup the config file. So I search through the files in `~/.config/ags` and eventually found that the config was located in `~/.cache` thank to these lines in `lib/session.ts`:
```ts
Object.assign(globalThis, {
    OPTIONS: `${GLib.get_user_cache_dir()}/ags/hyprpanel/options.json`,
    TMP: `${GLib.get_tmp_dir()}/ags/hyprpanel`,
    USER: GLib.get_user_name(),
});
```
I was wondering why the config is in the cache directory rather than the config directory, and why HyprPanel itself has to be installed in the config directory. That doesn't make any sense to me.

These are just questions, I understand that it is impossible to change this as it would be a breaking change.

Thanks !

**Comment by anotherhadi** [comment]
See #287
