### ISSUE TITLE
Volume OSD keeps on showing whenever there is media change or sound plays from different tabs in the same browser

### ISSUE THREAD

**Issue by rishav12s** [Jas-SinghFSU/HyprPanel#40]
It's kind of annoying when the osd shows every time im changing videos on yt or reels on insta and it also shows up when kitty terminal makes a sound while using the arrow keys to go through the previous commands used 

Hope you can fix this as i have completely switched to using the osd(s) now instead of using notify-send scripts

**Comment by Jas-SinghFSU** [comment]
Have you git pulled recently? I'm trying to replicate this issue but having no luck.
Could you run `git show` and provide the commit id?

**Comment by rishav12s** [comment]
```
commit 49a25e8741c69f2cbc88b34aae40aa91dd760ec1 (HEAD -> master, origin/master, origin
/HEAD)
```

**Comment by Jas-SinghFSU** [comment]
Replicated: Will get a fix soon.

**Comment by Jas-SinghFSU** [comment]
Could you please git pull and verify the fix?

**Comment by rishav12s** [comment]
Works perfectly now thanks man 👍
