### ISSUE TITLE
Mouse actions not working on workspaces after toggle

### ISSUE THREAD

**Issue by Nocxium** [Jas-SinghFSU/HyprPanel#406]
**Describe the bug**
The mouse actions doesnt work on the workspace widget after I use hyprpanel -t bar-# (twice) command in NixOS.
The other widgets work fine though.

**To Reproduce**
toggle (twice) with hyprpanel/ags -t bar-# and try to switch workspaces with the mouse.

**Expected behavior**
I expect the mouse actions to still work after toggling the bar.

**Desktop (please complete the following information):**
 - Distribution: NixOS (stable)
 - Window Manager/Desktop Environment: Hyprland

**Comment by Jas-SinghFSU** [comment]
I'm unable to replicate this. Could you please share your logs if possible?
