### ISSUE TITLE
Lingering app icon in workspaces after closing app

### ISSUE THREAD

**Issue by Joni-Samanen** [Jas-SinghFSU/HyprPanel#414]
**Describe the bug**
After closing app(s) in a workspace, the workspace icon is replaced with the fallback icon and not with the empty workspace icon. Only after opening an app in another workspace the empty workspace icon is displayed again. 

**To Reproduce**
Settings: Map Workspaces to (Application) Icons. Open app in an empty workspace. close the app. Now the current workspace icon is the fallback icon until another app is opened in another workspace.

**Expected behavior**
Workspace icon should change to empty workspace icon as soon as apps are closed.

**Screenshots**
empty workspace:
![2024-10-31_20:47:32-screenschot](https://github.com/user-attachments/assets/a8d0ad2d-45c4-43fe-97a0-4e83f5c6ea44)

app opened in workspace:
![2024-10-31_20:55:31-screenschot](https://github.com/user-attachments/assets/28fe4b6d-0295-4dbe-a45b-a5046eec7569)

app closed in workspace:
![2024-10-31_20:56:08-screenschot](https://github.com/user-attachments/assets/77ee5d56-3422-4d43-b93f-2347c8031a03)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
n/a

**Comment by Joni-Samanen** [comment]
Also making an app fullscreen anywhere and returning it to normal makes the workspace icon get back to "empty workspace" icon

**Comment by Jas-SinghFSU** [comment]
Can you show me your output of:
```
hyprctl -j
```
When this happens please?

And what apps are causing this?

**Comment by Joni-Samanen** [comment]
I had an old, make-installed version of hyprland running alongside the version installed via pacman, so even though I thought I was running hyprland 0.44 I was running the old make-installed version 0.35 So this was also my bad. Embarrassing.
