### ISSUE TITLE
Nixos : can't refer to the packages with home manager

### ISSUE THREAD

**Issue by noahfraiture** [Jas-SinghFSU/HyprPanel#420]
**Describe the bug**
Hello,

I'm trying to refer to the package to execute it with hyprland `  wayland.windowManager.hyprland.settings.exec-once = [ "${pkgs.hyprpanel}/bin/hyprpanel" ];`

But the problem is that I can't install it there `  home.packages = [ pkgs.hyprpanel ];`

My flake.nix is the following : 
```
      nixosConfigurations = {
        inspiron =
          let
            system = "x86_64-linux";
          in
          nixpkgs.lib.nixosSystem {
            specialArgs = {
              inherit inputs;
              inherit system;
            };
            modules = [
              { nixpkgs.overlays = [ inputs.hyprpanel.overlay ]; }

              ./hosts/inspiron/configuration.nix
              inputs.home-manager.nixosModules.home-manager
              inputs.stylix.nixosModules.stylix
              inputs.nix-flatpak.nixosModules.nix-flatpak
              inputs.spicetify-nix.nixosModules.default # TODO : move that in home-manager
            ];
          };
```

I followed the installation guide for nixos since the one for home-manager is for home-manager as standalone and I can't figure out how to adapt it if needed.

**Comment by VerySweetBread** [comment]
```
modules = [
  { nixpkgs.overlays = [ inputs.hyprpanel.overlay ]; }
  ...
];
```

dude...

**Comment by VerySweetBread** [comment]
It's not a module at all, it's an overlay of pkgs

Example:
```
    homeConfigurations = {
      sweetbread = home-manager.lib.homeManagerConfiguration {
        pkgs = import nixpkgs {
	  inherit system;
	  overlays = [ inputs.hyprpanel.overlay ];
        };
        extraSpecialArgs = { inherit inputs; };
        modules = [
          ./home-manager/users/sweetbread/home.nix
          inputs.sops-nix.homeManagerModules.sops
          inputs.stylix.homeManagerModules.stylix
          inputs.ags.homeManagerModules.default
        ];
      };
...
```

**Comment by noahfraiture** [comment]
> [ "${pkgs.hyprpanel}/bin/hyprpanel" ];

The thing is that it seems to be in configuration for nixos, and I'm on nixos, home-manager is not a standalone, I tried to follow this https://hyprpanel.com/getting_started/installation.html
Or maybe you know how to transform your solution in nixosconfiguration solution ? I'm still learning nix. Because it appears that the solution from the website doesn't work

**Comment by noahfraiture** [comment]
> Well, I'm wrong. Can you send an error? Module variant works on my machine

If I try to execute it once with hyprland I get an error saying `pkgs.hyprpanel` doens't exist (and it recommends to correct to hyprpaper). And if I remove that, I have an error sayings `home.packages = [ pkgs.hyprpanel ];` is wrong because hyprpanel doesn't exist.

**Comment by VerySweetBread** [comment]
I'm not an expert, but make sure your `pkgs` in HM is really overlayed

**Comment by noahfraiture** [comment]
It seems to be.
I gave up and configured hyprpanel via nixos without home-manager

**Comment by benvonh** [comment]
You can install with
```
home.packages = [ inputs.hyprpanel.packages.${pkgs.system}.default ];
```
Just make sure to replace restartCommand with `hyprpanel -q; hyprpanel`

I am also in the middle of creating a home manager module for it but it's going to be tough with how this application was made :(

**Comment by noahfraiture** [comment]
Yeah, having a configuration file in the cache for instance is a real pain. Also the migration to ags v2 must be pretty hard to do

**Comment by Jas-SinghFSU** [comment]
In Hyprpanel v2 the config is in `~/.config/hyprpanel`, so hopefully that makes life easier.

**Comment by benvonh** [comment]
@Jas-SinghFSU Regarding that, I want to ask some questions to make the Home Manager module easier to implement.

1. Is it possible to refer to the JSON as nested objects? Currentlty, they're just massive strings with dots. Can it support something like

```
