### ISSUE TITLE
Panel Only Spawns on first Monitor to Wake

### ISSUE THREAD

**Issue by awsumatt** [Jas-SinghFSU/HyprPanel#421]
**Describe the bug**

Panel spawns only on first display to wake (in this case my second monitor) and does not appear on the other display without a restart of ags. 

**To Reproduce**
Set hypridle to shut off monitors prior to calling hyprlock, have 2 different monitors with a significant difference in startup time (one starts in ~2 seconds the other takes a full 8 seconds to power on), wake screens.  

**Expected behavior**
The panel to be open on both displays as is normally configured

**Desktop (please complete the following information):**
 - Distribution: Arch w/ 6.11.5-zen1-1 kernel
 - Window Manager/Desktop Environment: Hyprland
 - Monitors: Generic 1080p@60Hz IPS LG (HDMI) and Samsung Odyssey G7 1440p@240Hz (DP)

**Comment by Jas-SinghFSU** [comment]
Fixed in #432
