### ISSUE TITLE
Allow removal of all dashboard shortcuts besides settings

### ISSUE THREAD

**Issue by Daholli** [Jas-SinghFSU/HyprPanel#422]
**Is your feature request related to a problem? Please describe.**

I would like to have my dashboard more minimalistic, but due to me using nixos and currently still tinkering, i cannot turn off the shortcuts in the dashboard or else I use access to the settings completely, until I turn shortcuts back on using the json

![image](https://github.com/user-attachments/assets/39e0e9ee-e892-4a12-985d-3e102ecd59c7)

**Describe the solution you'd like**
A way to enable the settings gear separate from the shortcuts, or a way to disable the screen record feature separatly

**Describe alternatives you've considered**
At some point this will not be an issue anymore since I will source the config file with home-manager once everything is configured how I want it to.

**Comment by Jas-SinghFSU** [comment]
You can just disable the shortcuts entirely and assign the following command to your Dashboard icon right click (Configuration > Bar > Dashboard):
```
ags -t settings-dialog
```
This way you can open the settings dialog when you right click the dashboard icon.

**Comment by Daholli** [comment]
Ayy that might just work thanks!

**Comment by Daholli** [comment]
yeah, that works. for nix it is `hyprpanel -t settings-dialog` thanks thats perfect
