### ISSUE TITLE
Gtop is missing but not

### ISSUE THREAD

**Issue by SpyPower** [Jas-SinghFSU/HyprPanel#423]
**Describe the bug**
```
[spy@spy-linux ~]$ ags

(com.github.Aylur.ags:72404): Gjs-Console-CRITICAL **: 13:01:38.343: Error: Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found
require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
@gi://GTop:3:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34
```

**To Reproduce**
During first run

**Expected behavior**
run

**Desktop (please complete the following information):**
 - Distribution: [EndeavourOS]
 - Window Manager/Desktop Environment: [Hyprland]

**Additional context**
```
[spy@spy-linux ~]$ whereis gtop
gtop: /usr/bin/gtop
```

**Comment by Kemboiray** [comment]
I've encountered a similar problem. I have both `gtop` and `libgtop` installed.

**Comment by rubiin** [comment]
@SpyPower @Kemboiray try this `sudo pacman -S libgtop`. Its not referring to the system viewer rather a lib

**Comment by rubiin** [comment]
made a pr on docs here https://github.com/Jas-SinghFSU/hyprpanel-docs/pull/4

**Comment by Kemboiray** [comment]
I already have `libgtop` (`sudo zypper in libgtop`. I'm on openSUSE Tumbleweed btw. The problem persists.

**Comment by rubiin** [comment]
did you by any chance reload ags?

**Comment by Kemboiray** [comment]
After installing I rebooted my PC, but the problem persists.

**Comment by SpyPower** [comment]
I am totally sorry, I think I missed something there.

**Comment by rubiin** [comment]
> I am totally sorry, I think I missed something there.

No worries. Glad you posted the error. Helped to dig down the issue
