### ISSUE TITLE
Ncmpcpp added to media

### ISSUE THREAD

**Issue by itstoxicqt** [Jas-SinghFSU/HyprPanel#427]
**Describe the solution you'd like**
Pick up and possibly be able to show what's being played through Ncmpcpp/mpd 

**Describe alternatives you've considered**
none since i currently dont play for spotify premium 

**Additional context**

**Comment by rubiin** [comment]
as long as playerctl can get the metadata, it should be doable. Havent used ncmpp until now so can you ` playerctl metadata` screenshot what the command outputs when you are playing a song via ncmpp

**Comment by itstoxicqt** [comment]
> the above screenshot seems to be broken

yea idk what happened just was showing it working lol

**Comment by itstoxicqt** [comment]
![snapshot_2024-11-03_01-44-49](https://github.com/user-attachments/assets/57c01138-4c6d-40a5-9479-a419b1b37408)
seems it doesnt even pick up ncmpcpp?

**Comment by rubiin** [comment]
@itstoxicqt https://github.com/altdesktop/playerctl/issues/255 says something about additional plugin. Try it out

**Comment by itstoxicqt** [comment]
that seems of made the media tab pick up ncmpcpp! might want to toss it in the wiki/read me, that the service needs to be enabled/running mpd-mpris.service and the media tab will now have control over ncmpcpp!

**Comment by itstoxicqt** [comment]
![Uploading snapshot_2024-11-03_01-53-39.png…]()

**Comment by rubiin** [comment]
the above screenshot seems to be broken
