### ISSUE TITLE
Bluetooth multipoint audio edge case not handled

### ISSUE THREAD

**Issue by smathles** [Jas-SinghFSU/HyprPanel#429]
Testing the limits of the bluetooth module :stuck_out_tongue_closed_eyes:!

So if I have my sony WH-1000XM5's connected to both my laptop (arch, hyprland, hyprpanel) and my phone, the bluetooth does not work such that whichever audio source last pressed "play", that source is played in my headphones.

**To Reproduce**
1. Firstly connect headphones to laptop (works great)
2. Connect to phone as well (works great on phone)
3. Pause phone, press play on laptop
4. See in bluetooth module is "connected" in the widget itself, but battery is "0%" and no actual audio is working.
5. Disconnect from phone.
6. See security popup, confirm popup.
7. Audio works, battery percentage works.

**Expected behavior**
I would expect the battery/connection to work with multipoint well, where the audio source changes to whichever audio source was last played, whether this is the phone or laptop (this works on KDE and windows well, idk about GNOME).

**Screenshots**
![image](https://github.com/user-attachments/assets/0410e3ff-fcc4-4049-9864-4fb3927ddfa7)

**Desktop (please complete the following information):**
 - Distribution: Arch btw
 - Window Manager/Desktop Environment: Hyprland btw, HyprPanel btw

**Why does this happen?**
I don't know for sure, but I suspect it's an AGS thing. Might be hyprpanel's specific implementation, but idk fr.

**Additional context**
Elephants are NOT for eating

**Comment by davfsa** [comment]
Random, but i recently got some WH-1000XM4 and the multipoint audio works great, so I believe that the AGS v2 upgrade fixed it!
