### ISSUE TITLE
hyprpanel error - NixOS

### ISSUE THREAD

**Issue by gnussbaum1967** [Jas-SinghFSU/HyprPanel#436]
**Describe the bug**

Hi,

I get the following when running **sudo nixos-rebuild switch --flake ~/.config/nixos#nixos** (where nixos is my hostname)

`error: builder for '/nix/store/1qysn8bysi5gxya79iyanv1jkgz1xdkb-hyprpanel-latest.drv' failed with exit code 132; last 9 log lines: > Running phase: unpackPhase > unpacking source archive /nix/store/dxp36f7aj4cs8px5hjsv6iphcg9b8prb-kf3d107nnhk53vwl21k41ggy0ksgml5j-source > source root is kf3d107nnhk53vwl21k41ggy0ksgml5j-source > Running phase: patchPhase > Running phase: updateAutotoolsGnuConfigScriptsPhase > Running phase: configurePhase > no configure script, doing nothing > Running phase: buildPhase > /nix/store/ncv68hjnidcd2bm5abkhklrijhn0cgn6-stdenv-linux/setup: line 1712:    42 Illegal instruction     (core dumped) /nix/store/hilx2jwdslc05d38q4fzpsli6pgc56sa-bun-1.1.31/bin/bun build ./main.ts --outfile main.js --external "resource://*" --external "gi://*" For full logs, run 'nix log /nix/store/1qysn8bysi5gxya79iyanv1jkgz1xdkb-hyprpanel-latest.drv'. error: 1 dependencies of derivation '/nix/store/7c95isk973r9wzcbapvva4xv8n63x20q-hyprpanel.drv' failed to build error: 1 dependencies of derivation '/nix/store/8z9yy3ipjyvs2mxx0qyqa0pi9daxr6l9-hm_hyprhyprland.conf.drv' failed to build error: 1 dependencies of derivation '/nix/store/3zfi2918z6av01pb01sb2ad7b55pmb2x-home-manager-path.drv' failed to build error: 1 dependencies of derivation '/nix/store/v50frb739hhcfi2pm8r3i5ssydy9kdhd-home-manager-generation.drv' failed to build error: 1 dependencies of derivation '/nix/store/l0cgsk7q3i8kadk3f9sa3jqvnm5a3hjz-user-environment.drv' failed to build error: 1 dependencies of derivation '/nix/store/f5my9m1myiylr7sarv5p12sr7sji2nwy-etc.drv' failed to build error: 1 dependencies of derivation '/nix/store/6c85asx7ind986zghvyccxwrxk1wwz4y-nixos-system-nixos-24.11.20241029.807e915.drv' failed to build `

I tried running a **sudo nix build -L '/nix/store/1qysn8bysi5gxya79iyanv1jkgz1xdkb-hyprpanel-latest.drv^*'** and got this:

`hyprpanel-latest> Running phase: unpackPhase hyprpanel-latest> unpacking source archive /nix/store/dxp36f7aj4cs8px5hjsv6iphcg9b8prb-kf3d107nnhk53vwl21k41ggy0ksgml5j-source hyprpanel-latest> source root is kf3d107nnhk53vwl21k41ggy0ksgml5j-source hyprpanel-latest> Running phase: patchPhase hyprpanel-latest> Running phase: updateAutotoolsGnuConfigScriptsPhase hyprpanel-latest> Running phase: configurePhase hyprpanel-latest> no configure script, doing nothing hyprpanel-latest> Running phase: buildPhase hyprpanel-latest> /nix/store/ncv68hjnidcd2bm5abkhklrijhn0cgn6-stdenv-linux/setup: line 1712:    42 Illegal instruction     (core dumped) /nix/store/hilx2jwdslc05d38q4fzpsli6pgc56sa-bun-1.1.31/bin/bun build ./main.ts --outfile main.js --external "resource://*" --external "gi://*" error: builder for '/nix/store/1qysn8bysi5gxya79iyanv1jkgz1xdkb-hyprpanel-latest.drv' failed with exit code 132 `

Any idea what may be causing this? This is a NixOS vm on virtualbox.

**To Reproduce**

run sudo nixos-rebuild switch --flake ~/.config/nixos#nixos

**Expected behavior**

hyprpanel builds successfully

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Distribution: [e.g. Arch Linux] NixOS
 - Window Manager/Desktop Environment:  [e.g. Hyprland] Hyprland

**Additional context**
Using https://github.com/anotherhadi/nixy to try to build his dotfiles.  This is a NixOS VM on virtualbox.

**Comment by Data8021** [comment]
I received a similar error trying to build this from flake:

```
evaluation warning: The 'gnome.gnome-bluetooth' was moved to top-level. Please use 'pkgs.gnome-bluetooth' directly.
error: builder for '/nix/store/q3q19czcgpl617s53985kh9i6abnsfcr-hyprpanel-latest.drv' failed with exit code 132;
       last 9 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/74bkimpsz0w9yq79lxw1i0s389fj9z7w-mvy40s8rwx8k16ar2cl1wdsrxpjnhwqy-source
       > source root is mvy40s8rwx8k16ar2cl1wdsrxpjnhwqy-source
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > /nix/store/a9c7qzxdm2h2ga4awbxwin7ylxfvq31g-stdenv-linux/setup: line 1712:    42 Illegal instruction     (core dumped) /nix/store/gimbmhysr6l7fbzk25alznv0mphiy97a-bun-1.1.31/bin/bun build ./main.ts --outfile main.js --external "resource://*" --external "gi://*"
       For full logs, run 'nix log /nix/store/q3q19czcgpl617s53985kh9i6abnsfcr-hyprpanel-latest.drv'.
error: 1 dependencies of derivation '/nix/store/3jgpx77gf2c8391ky3z7hpmrbpa9sm4b-hyprpanel.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fq2zqjfr22wgz75wli1qxiwykxnj044m-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/j1j92k71jqr8s26k5disw726qyaga4ni-nixos-system-hlhyprnix-24.11.20241105.4aa3656.drv' failed to build
```

When I produced the full log, I received this:

```
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/q3q19czcgpl617s53985kh9i6abnsfcr-hyprpanel-latest.drv^*'
Running phase: unpackPhase
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/74bkimpsz0w9yq79lxw1i0s389fj9z7w>
source root is mvy40s8rwx8k16ar2cl1wdsrxpjnhwqy-source
Running phase: patchPhase
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScrip>
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "configurePhase" }
no configure script, doing nothing
Running phase: buildPhase
@nix { "action": "setPhase", "phase": "buildPhase" }
/nix/store/a9c7qzxdm2h2ga4awbxwin7ylxfvq31g-stdenv-linux/setup: line>

```

**Comment by git-meywo** [comment]
Tried today, issue is either still here or is back.

**Comment by bigbabyboost** [comment]
> I received a similar error trying to build this from flake:
> 
> ```
> evaluation warning: The 'gnome.gnome-bluetooth' was moved to top-level. Please use 'pkgs.gnome-bluetooth' directly.
> error: builder for '/nix/store/q3q19czcgpl617s53985kh9i6abnsfcr-hyprpanel-latest.drv' failed with exit code 132;
>        last 9 log lines:
>        > Running phase: unpackPhase
>        > unpacking source archive /nix/store/74bkimpsz0w9yq79lxw1i0s389fj9z7w-mvy40s8rwx8k16ar2cl1wdsrxpjnhwqy-source
>        > source root is mvy40s8rwx8k16ar2cl1wdsrxpjnhwqy-source
>        > Running phase: patchPhase
>        > Running phase: updateAutotoolsGnuConfigScriptsPhase
>        > Running phase: configurePhase
>        > no configure script, doing nothing
>        > Running phase: buildPhase
>        > /nix/store/a9c7qzxdm2h2ga4awbxwin7ylxfvq31g-stdenv-linux/setup: line 1712:    42 Illegal instruction     (core dumped) /nix/store/gimbmhysr6l7fbzk25alznv0mphiy97a-bun-1.1.31/bin/bun build ./main.ts --outfile main.js --external "resource://*" --external "gi://*"
>        For full logs, run 'nix log /nix/store/q3q19czcgpl617s53985kh9i6abnsfcr-hyprpanel-latest.drv'.
> error: 1 dependencies of derivation '/nix/store/3jgpx77gf2c8391ky3z7hpmrbpa9sm4b-hyprpanel.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/fq2zqjfr22wgz75wli1qxiwykxnj044m-system-path.drv' failed to build
> error: 1 dependencies of derivation '/nix/store/j1j92k71jqr8s26k5disw726qyaga4ni-nixos-system-hlhyprnix-24.11.20241105.4aa3656.drv' failed to build
> ```
> 
> When I produced the full log, I received this:
> 
> ```
> warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/q3q19czcgpl617s53985kh9i6abnsfcr-hyprpanel-latest.drv^*'
> Running phase: unpackPhase
> @nix { "action": "setPhase", "phase": "unpackPhase" }
> unpacking source archive /nix/store/74bkimpsz0w9yq79lxw1i0s389fj9z7w>
> source root is mvy40s8rwx8k16ar2cl1wdsrxpjnhwqy-source
> Running phase: patchPhase
> @nix { "action": "setPhase", "phase": "patchPhase" }
> Running phase: updateAutotoolsGnuConfigScriptsPhase
> @nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScrip>
> Running phase: configurePhase
> @nix { "action": "setPhase", "phase": "configurePhase" }
> no configure script, doing nothing
> Running phase: buildPhase
> @nix { "action": "setPhase", "phase": "buildPhase" }
> /nix/store/a9c7qzxdm2h2ga4awbxwin7ylxfvq31g-stdenv-linux/setup: line>
> ```
> 
> This was run on a nixos VM running on proxmox using nix flakes and unstable packages.

Same, did you manage to solve it?

**Comment by ShadowReaper420** [comment]
Also having the same issue
