### ISSUE TITLE
Cannot open ags - Arch Linux

### ISSUE THREAD

**Issue by yorunoken** [Jas-SinghFSU/HyprPanel#437]
**Describe the bug**
ags fails to open after killing and running it again

**To Reproduce**
kill ags and re-enable it

**Expected behavior**
ags should open

**Screenshots**
gets stuck on `ags`
![image](https://github.com/user-attachments/assets/652e98b9-928c-4fe5-8d41-e7decc001483)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
The panel froze before I killed it for some reason, and after I went to re-enable it, this happened.

**Comment by Jas-SinghFSU** [comment]
Do you happen to remember what caused it to freeze? Was there any media player open at the time?
