### ISSUE TITLE
How are you hiding the dropdown windows when the user clicks away from it?

### ISSUE THREAD

**Issue by MonstrousOgre** [Jas-SinghFSU/HyprPanel#44]
This isn't a bug or a feature request. I was just curious how you implemented this functionality. I already have my own ags config which includes a bar for each monitor and a dropdown window. Right now, the only way to hide or show the dropdown window for my config is to click on a button on the bar. I'd love to be able to close the dropdown window by clicking away from it anywhere.

I tried looking at your config but couldn't figure out how you accomplished this. I'm guessing it has something to do with all the EventBox widgets in DropdownMenu?

**Comment by Jas-SinghFSU** [comment]
I have 2 EventBoxes. The parent EventBox that covers the entire screen (className: "parent-event"). This parent event box will then close the window if it registers a click.

Then I have a child EventBox inside of the parent EventBox above. This child also registers clicks but it returns true instead. This allows you to interact with it's children.

**Comment by Jas-SinghFSU** [comment]
Let's go ahead and move this conversation over in [Discussions](https://github.com/Jas-SinghFSU/HyprPanel/discussions).
