### ISSUE TITLE
Fix network icon for wired connection

### ISSUE THREAD

**Issue by Houdiee** [Jas-SinghFSU/HyprPanel#447]
**Describe the bug**
currently with a wired connection the network module looks like this:
![image](https://github.com/user-attachments/assets/76d3d3ad-171b-4f5f-a574-d870d7d2cac4)

**To Reproduce**
Using the nix flake

**Comment by Houdiee** [comment]
(com.github.Aylur.ags:59662): Gjs-Console-WARNING **: 07:44:30.957: Error: can't assign "view-refresh-symbolic" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
_handleParamProp@resource:///com/github/Aylur/ags/widgets/widget.js:124:13
Icon@resource:///com/github/Aylur/ags/widgets/icon.js:25:14
newIcon@resource:///com/github/Aylur/ags/widgets/icon.js:8:12
Option@file:///nix/store/izcp6lfnwgl1qwz1fggw5is2a85f8j3x-hyprpanel-latest/config.js:11864:23
DashboardMenuTheme@file:///nix/store/izcp6lfnwgl1qwz1fggw5is2a85f8j3x-hyprpanel-latest/config.js:12614:9
ThemesMenu/<.children<@file:///nix/store/izcp6lfnwgl1qwz1fggw5is2a85f8j3x-hyprpanel-latest/config.js:13541:31
transform/bind.transformFn@resource:///com/github/Aylur/ags/service.js:16:37
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by Jas-SinghFSU** [comment]
This is because your system icon theme is incomplete and doesn't have that icon. You have to install something like Adwaita, Breeze or Papirus which does.

**Comment by rubiin** [comment]
@Jas-SinghFSU maybe we should add it to faq

**Comment by Jas-SinghFSU** [comment]
@rubiin It's in this section: https://hyprpanel.com/help/faq.html#help-why-are-some-of-my-icons-missing-or-showing-up-as-squares

Maybe we add some examples like the ones listed above.

**Comment by rubiin** [comment]
Yrah tha can be done. I had a pr on docs too maybe i can update them by tomorrow. How does that sound

**Comment by Houdiee** [comment]
> This is because your system icon theme is incomplete and doesn't have that icon. You have to install something like Adwaita, Breeze or Papirus which does.

I see. I thought a nerd font was enough. Thanks for letting me know
