### ISSUE TITLE
[BUG]: very annoying bug. if internet connection is lost ags is killed

### ISSUE THREAD

**Issue by its-19818942118** [Jas-SinghFSU/HyprPanel#45]
**Describe the bug**
so my issue is that i have very bad internet connection and my ethernet cable is broken. so like it keeps getting killed when internet is disconnected.

**To Reproduce**
i aint sure if its reproducable but
kill internet. wait for it to get killed

**Expected behavior**
like it will keep running like. normal. as far as i have seen the code. its very dependant on each modules which is annoying. it loses functionality that way.
**Screenshots**
welp i mean none
**Desktop (please complete the following information):**
 - Distribution: EOS ``Linux Aurora 6.10.0-arch1-2 #1 SMP PREEMPT_DYNAMIC Mon, 22 Jul 2024 17:28:23 +0000 x86_64 GNU/Linux``
 - Window Manager/Desktop Environment: hyprland duh

**Additional context**
hmm as far as i know none

**Comment by Jas-SinghFSU** [comment]
I will look into this later today.

**Comment by Jas-SinghFSU** [comment]
Could you send me a complete log dump of the crash? I can't seem to replicate it on my end by disconnected the wifi.

**Comment by Jas-SinghFSU** [comment]
Replicated: Investigating now....

**Comment by its-19818942118** [comment]
> Replicated: Investigating now....

@Jas-SinghFSU thanks. lol my internet died so i couldnt get back to you
