### ISSUE TITLE
Theme isn't loading at first boot

### ISSUE THREAD

**Issue by LifeLovesYou** [Jas-SinghFSU/HyprPanel#451]
**Describe the bug**
It looks like HyprPanel's theme isn't setting correctly on the system's first boot, when using exec-once = ags I have to manually use pkill ags then ags again in a terminal or restart hyprland after the system has booted.

**To Reproduce**
Reboot your system or start it after it was turned on.

**Expected behavior**
The theme should be applied

**Screenshots**
![image](https://github.com/user-attachments/assets/5d8f9eb8-829f-4565-b5fe-eda11fcab231)
![image](https://github.com/user-attachments/assets/09c19ab7-bbbd-4d9c-83af-3699d03d065e)

**Desktop (please complete the following information):**
 - Distribution: Fedora 41
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
None

**Comment by rozodru** [comment]
having the exact same issue on Nobara/Fedora 40, says missing dependencies sass but sass is installed. have to pkill ags and then manually launch ags and it works. exec once = ags results in the same as above

**Comment by Jas-SinghFSU** [comment]
Can you install nodejs and do
```
npm i -g sass
```
Then try again? I feel like there's an issue with installing sass via bun where it doesn't set the path correctly and node might.

**Comment by rozodru** [comment]
> Can you install nodejs and do
> 
> ```
> npm i -g sass
> ```
> 
> Then try again? I feel like there's an issue with installing sass via bun where it doesn't set the path correctly and node might.

this fixed it for me on Nobara/Fedora 40. just tested and it works on reboot.
