### ISSUE TITLE
CLI command to change wallpaper path.

### ISSUE THREAD

**Issue by GoGoGadgetGitHub** [Jas-SinghFSU/HyprPanel#459]
**Is your feature request related to a problem? Please describe.**

Currently the only way to tell Hyprpanel what wallpaper I'm using is by changing it through the settings. This makes it hard for anyone using a pywall/wallpaper script to integrate Hyprpanel into their config.

**Describe the solution you'd like**

A CLI command to pass a wallpaper path to Hyprpanel would make integrating it allot simpler. Something like `ags -r "setWallpaperPath(path)"`. This way the color scheme of the bar can be made to adapt to a wallpaper change via some other means such as a script using it's existing mutagen setup. (Ideally this would only actually change the wallpaper if you have "Apply Wallpapers" on)

**Describe alternatives you've considered**

I could probably make a script to change the variable in the options.json file, but this seems silly.

I cold also set the path of the wallpaper to be a file which I replace using a script, but then the problem would be file extensions.

**Additional context**

What I did with waybar was just import the file generated by pywal into the css, and connected the `wal -i` command to waypaper, changing waybar as I change my wallpaper. Then in my hyprland config I just bound a key to selecting a random wallpaper, through `waypaper --random`

**Comment by Jas-SinghFSU** [comment]
closed by #463
