### ISSUE TITLE
Unresponsive bottom right part of the screen

### ISSUE THREAD

**Issue by HAS2437** [Jas-SinghFSU/HyprPanel#460]
**Describe the bug**
The bottom right part of the screen is unresponsive in a tall rectangular region.

**To Reproduce**
Interact with something on the specified region.

**Expected behavior**
The interaction should do something.

**Screenshot**
![Bug](https://github.com/user-attachments/assets/5525640a-bb33-4228-9863-6dc7a4e587a9)
The red region is an approximation of the unsesponsive region.

**Desktop (please complete the following information):**
 - Archlinux
 - Hyprland

**Comment by Jas-SinghFSU** [comment]
Can you export your config and share it please? Please remember to redact your weather API key.

**Comment by HAS2437** [comment]
Here is my config.
[hyprpanel_config.json](https://github.com/user-attachments/files/17687899/hyprpanel_config.json)

**Comment by Jas-SinghFSU** [comment]
This should be fixed now, please reopen if the issue still persists.
