### ISSUE TITLE
New Matugen breaks Theming

### ISSUE THREAD

**Issue by awsumatt** [Jas-SinghFSU/HyprPanel#464]
**Describe the bug**
Matugen theming no longer works. Any selected profile maintains the same rainbow-style color scheme, regardless of wallpaper. 

**To Reproduce**
Update Matugen and cycle through theme presets (contents, tonal-spot, vivid, monochrome, etc.)

**Expected behavior**
Proper wallpaper-based theme generation 

**Desktop (please complete the following information):**
 - Distribution: Arch
 - Window Manager/Desktop Environment: Hyprland
-Matugen Version: 2.4.0-1

**Additional context**
Console output of `ags`:

```
(com.github.Aylur.ags:1038143): Gjs-Console-CRITICAL **: 07:29:44.393: An error occurred while generating matugen colors: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

(com.github.Aylur.ags:1038143): Gjs-Console-CRITICAL **: 07:29:59.573: matugen image /home/awsumatt/Pictures/mountain.png -t scheme-tonal-spot --contrast 0 --json hex error: unexpected argument '--json' found

  tip: to pass '--json' as a value, use '-- --json'

Usage: matugen image --type <TYPE> --contrast <CONTRAST> <PATH>

For more information, try '--help'.

(com.github.Aylur.ags:1038143): Gjs-Console-CRITICAL **: 07:29:59.573: An error occurred while generating matugen colors: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

**Comment by Jas-SinghFSU** [comment]
Wow, matugen introduced breaking changes in a minor version huh. Fun lol.

I'll look into this, thanks for the heads up.

**Comment by Jas-SinghFSU** [comment]
Scratch that, it seems like a bug instead. We can track it here: https://github.com/InioX/matugen/issues/126

It seems that the valid flags and options are no longer recognized.

**Comment by Jas-SinghFSU** [comment]
@awsumatt I think you're better off installing matugen via cargo, it seems to be working for me.
```
yay -Rns matugen-bin && cargo matugen
```

**Comment by Jas-SinghFSU** [comment]
Scratch that, you have to built it yourself with
```
git clone https://github.com/InioX/matugen.git
cd matugen
cargo install --path . --features dump-json
```

**Comment by awsumatt** [comment]
That works 👍 
For anyone else with this issue, I also symlinked the executable into my `/usr/bin` so Hyprpanel can use it:
`sudo ln -s /home/$USER/.cargo/bin/* /usr/bin`

**Comment by raininja** [comment]
I rebuilt matugen and it didn't fix the problem .
```
zsh/2 20119 % agsv1                                                   

(com.github.Aylur.ags:14695): Gjs-Console-CRITICAL **: 01:49:24.759: An error occurred while generating matugen colors: SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 2 column 1 of the JSON data
```
