### ISSUE TITLE
HyprPanel Notifications dont work anymore

### ISSUE THREAD

**Issue by lolpowerluke** [Jas-SinghFSU/HyprPanel#468]
**Describe the bug**
I updated to github repo this morning (using git pull)
and since then the notifications dont work anymore

**To Reproduce**
idk tbh

**Expected behavior**
notifications work like before

**Screenshots**
(yazi folder view, idk what else to show)
![image](https://github.com/user-attachments/assets/8363422c-62b3-4885-84bb-8416e83a3348)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
I have another notification daemon, but before today the one from hyprpanel used to take priority so I didnt see the other one, now I only see the other one

**Comment by Jas-SinghFSU** [comment]
You should always disable the other daemon when using hyprpanel. So go ahead and do that first and then restart hyprpanel. I am on latest and notifications don't seem to be having any issues.

**Comment by lolpowerluke** [comment]
that was the issue, ty
