### ISSUE TITLE
Workspace color doesnt work anymore

### ISSUE THREAD

**Issue by lolpowerluke** [Jas-SinghFSU/HyprPanel#474]
**Describe the bug**
I think it used to be "Workspace Occupied Color" to change the text color for occupied workspaces
this doesnt do anything anymore

**To Reproduce**
change workspace occupied color
see nothing being changed

**Expected behavior**
text color changes for occupied workspaces
(quick edit using krita, so quality isnt great)
![image](https://github.com/user-attachments/assets/1451aaf9-0c0d-4927-8164-21cd1a03b81c)

**Screenshots**
![image](https://github.com/user-attachments/assets/0c6fb399-6e42-4a36-9d1e-00fc5fe05d40)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Comment by Jas-SinghFSU** [comment]
Could you export your config and share it please? There might be a setting that's causing this unintentionally.
Note: Please redact your weather API key from the exported config

**Comment by lolpowerluke** [comment]
[hyprpanel_theme.json](https://github.com/user-attachments/files/17692784/hyprpanel_theme.json)

**Comment by Jas-SinghFSU** [comment]
That is the theme, could you share the config instead please.

**Comment by lolpowerluke** [comment]
[hyprpanel_config.json](https://github.com/user-attachments/files/17692862/hyprpanel_config.json)

**Comment by Jas-SinghFSU** [comment]
Ah, I see what's happening. You have global colors enabled so it's taking the colors from the Button Icon setting. I'll update this so that workspaces still use their own colors rather than a global color as that makes no sense.
