### ISSUE TITLE
[Bug] Volume module uses way too much horizontal space when placed on the left side

### ISSUE THREAD

**Issue by areyoufeelingitnowmrkrebs** [Jas-SinghFSU/HyprPanel#493]
I mentioned this in the discord server but wanted to make an official bug report here for better tracking. This behavior only happens when placing the module on the left, not the center or right.

**Comment by areyoufeelingitnowmrkrebs** [comment]
> screenshots would be nice

![snapshot_2024-11-12_09-55-04](https://github.com/user-attachments/assets/61c95885-0bb0-4d04-bcff-49763e83c5ff)

**Comment by rubiin** [comment]
let me try to replicate

**Comment by areyoufeelingitnowmrkrebs** [comment]
> indeed a bug

I know lol. Like I said I already mentioned it in Discord and spoke with Jas about it directly.

**Comment by rubiin** [comment]
will try to close this on free time unless Jas does it first
