### ISSUE TITLE
[BIG ISSUE] Update sha256 for nix systems

### ISSUE THREAD

**Issue by Houdiee** [Jas-SinghFSU/HyprPanel#495]
can't rebuild my nixos system as I get the following error:
```
error: hash mismatch in fixed-output derivation '/nix/store/1nn8yqkcgds1frzkh4hxhbk3d0ifv2wd-source.drv':
         specified: sha256-SN4m0ka5VHLIQYTszhlCIB+2D+nyWMzJM5n5bZdkG/I=
            got:    sha256-l623fIVhVCU/ylbBmohAtQNbK0YrWlEny0sC/vBJ+dU=
error: 1 dependencies of derivation '/nix/store/ksbmi4ar7nzjd88zgq4py9a7kx9bkz27-matugen-2.4.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fyhjq3q83xnjh5iaq9qwphsnhk16gxgd-hyprpanel.drv' failed to build
error: 1 dependencies of derivation '/nix/store/9sc3fdq0jampwrxgaf2jb5mg2hv9f7gb-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1rr81cv1l1l6xclhbjzi69gqbcw5kfvz-nixos-system-nixtoast-24.11.20241110.aebe249.drv' failed to build
```
this prevents nix users from upgrading any other part of their system as well, which is a pretty big deal. Appreciate the fast responses you guys always put out, so hoping this gets patched quick :)

**Comment by rubiin** [comment]
duplicate https://github.com/Jas-SinghFSU/HyprPanel/issues/479

**Comment by Houdiee** [comment]
> This is now fixed afaik, try updating your `nixpkgs` input.

unfortunately not :( but from what i've read it shouldn't be long before this is fixed as its simply waiting on another dependency to be updated

**Comment by Houdiee** [comment]
fixed now
