### ISSUE TITLE
Workspace count with multi-monitor

### ISSUE THREAD

**Issue by xyzbtw** [Jas-SinghFSU/HyprPanel#498]
Even when you have monitor specific enabled, hyprpanel shows all workspaces that aren't linked to a specific monitor.

Feature request: for it to only show a workspace depending on the monitor that it's on.

Issue example
workspace 1 is linked to monitor 1
workspaces 2 and 3 are linked to monitor 2

Workspaces 4 and 5 are on monitor 2.

Hyprpanel on monitor 1 shows workspaces 4 and 5 that are on monitor 2.

**Comment by xyzbtw** [comment]
made a "fix" in occupied.ts for workspaces
 .filter((i) => {
                        const workspace = hyprland.workspaces.find((ws) => ws.id === i);
                        return workspace && (!monitorSpecific || (curMonitor && workspace.monitorID === curMonitor.id));
                    })
                    
                    
![image](https://github.com/user-attachments/assets/6942e5b2-8ed3-47cc-8629-3b6bd8b454b5)

**Comment by xyzbtw** [comment]
> you can create a PR if you like

not sure if i want to because idk how reliable it is with other settings

**Comment by MasterMind7777777** [comment]
+ rep. That fix solved it for me also.
