### ISSUE TITLE
System tray popups behave weirdly.

### ISSUE THREAD

**Issue by xyzbtw** [Jas-SinghFSU/HyprPanel#499]
When right clicking something in tray, and then clicking on an empty "desktop" or a floating terminal, it stays there and behaves weirdly. See video

https://github.com/user-attachments/assets/d50204eb-87e6-4d54-8557-059904732069

**Comment by abenezerw** [comment]
oh yeah. this is weird. happens on waybar popups too. i think its something to do with the tooltip package and not this repo.\
