### ISSUE TITLE
When I click on a wifi connection that I wasnt connected with before, nothing happens

### ISSUE THREAD

**Issue by simonlearnscoding** [Jas-SinghFSU/HyprPanel#507]
**To Reproduce**

- I click on the network module and I am not connected to any wifi. 
- I click on a connection to connect to it for the first time
- a loading spinner will appear.
- nothing else happens. this "loading" state persists forever.

**Expected behavior**
- when I click on a new connecction, I expect a popup to appear to prompt me to insert the password.
- afterwards I expect to be connected to that wifi

**Desktop (please complete the following information):**
This behavior was observed on NixOS with hyprland
- perhaps this is due to a missing dependency?

**Comment by Jas-SinghFSU** [comment]
Network module is being reworked for AGSv2.
