### ISSUE TITLE
Fine tuning mistake on the configuration panel (font size in the first field...typed in manually) ....a made a typo and it was an instant crash.  Unable to restore to default settings.

### ISSUE THREAD

**Issue by OceanusHelios** [Jas-SinghFSU/HyprPanel#514]
Fine tuning mistake on the configuration panel (font size in the first field...typed in manually) ....a made a typo and it was an instant crash.  Unable to restore to default settings.

**To Reproduce**
First field, first panel in the config widget...on my hidpi display, I tried to manually enter a value too high for my monitor / gdk to support.

**Expected behavior**
A way / command or a conditional of some kind that will ask to reset to a default configuration for user errors, or at least something in the wiki on how to restore to default settings.

**Screenshots**

(com.github.Aylur.ags:506961): Gdk-CRITICAL **: 05:04:25.367: ../gtk/gdk/wayland/gdkdisplay-wayland.c:1433: Unable to create Cairo image surface: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
Segmentation fault (core dumped)

**Desktop (please complete the following information):**
 - Arch Linux
 - Hyprland
 - Nvidia 2080 GPU without previous issues with Hyprland or Hyprpanel (it worked before)

**Additional context**
If anything I would just like to be able to find where I messed up and edit it in a text editor to the default value.

**Comment by Jas-SinghFSU** [comment]
I will add this to the wiki but if you want to reset all settings to default you can use
```sh
ags --clear-cache

# Or if uisng agsv1
agsv1 --clear-cache
```

This will wipe every setting from your config. If, however, you prefer to change that setting back manually, you can find the property in `~/.cache/ags/hyprpanel/options.json` and set it to a realistic value.

Please let me know if that satisfies your request so I can add it to the wiki.

**Comment by OceanusHelios** [comment]
This worked perfectly and instantly.   Thank you very much for your very prompt response.  I was expecting my issue to go unnoticed.   You have my deepest gratitude.
