### ISSUE TITLE
bad vertically centered text from icons

### ISSUE THREAD

**Issue by victorballester7** [Jas-SinghFSU/HyprPanel#519]
**Describe the bug**
There is a small inconsistency in the vertical alignment between the text and the icons. Not sure if it is a proper issue or bad configuration from me.

**To Reproduce**
I attatch my configs files:
[hyprpanel_config.json](https://github.com/user-attachments/files/17792239/hyprpanel_config.json)
[hyprpanel_theme.json](https://github.com/user-attachments/files/17792240/hyprpanel_theme.json)

**Expected behavior**
Icons and text vertically centered.

**Screenshots**
![image](https://github.com/user-attachments/assets/0df3a093-e91c-4859-bc84-474fd6343472)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland 0.45.0-1
 - Using agsv1

**Comment by Jas-SinghFSU** [comment]
I think the issue here is that the font you've chosen seems to be misaligned on the horizontal axis. May I ask what font you're using?

**Comment by victorballester7** [comment]
Oh I see, actually i had `None` int he font section. Now I selected a particular one and it's solved!!! Thanks again!! :)
