### ISSUE TITLE
not showing modules when hovering

### ISSUE THREAD

**Issue by victorballester7** [Jas-SinghFSU/HyprPanel#520]
**Describe the bug**
When I hover over my modules, the text becomes invisible. Not sure if this is an issue or a misconfiguration in my dot files. I am using the matugen color theme based on the wallpaper colors, if that helps.

**To Reproduce**
Here I attacth my config files:
[hyprpanel_config.json](https://github.com/user-attachments/files/17792282/hyprpanel_config.json)
[hyprpanel_theme.json](https://github.com/user-attachments/files/17792283/hyprpanel_theme.json)

**Expected behavior**
It should show the same text and icon but in another color. 

**Screenshots**
![WhatsApp Image 2024-11-17 at 20 16 05](https://github.com/user-attachments/assets/2caa3af4-d3fd-47ae-9f69-b0b0e4781a6d)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Comment by Jas-SinghFSU** [comment]
What are your settings in Theming > Bar for this section:
![image](https://github.com/user-attachments/assets/1c31d4eb-4196-481f-b0b6-a6614451d874)

**Comment by victorballester7** [comment]
My bad, I had a 0 in `Button Background Hover Opacity`. Thanks for your rapid point.
