### ISSUE TITLE
[FEATURE] Smart Workspace icons

### ISSUE THREAD

**Issue by paiyayay** [Jas-SinghFSU/HyprPanel#523]
**Is your feature request related to a problem? Please describe.**
When I open a firefox window in workspace 1 for example, workspace 1 icon on the bar should be the firefox icon. This would be dynamic and potentially improve navigation.

**Describe the solution you'd like**
An option and feature to make workspace icons dynamic based on opened windows. hyprctl clients should give the enough information to implement this, but I do not know about if there could be a signal when window is opened or there should be a timer checks every second.

**Describe alternatives you've considered**
There are static workspace icons but this is an alternative to that. Dynamic workspace icons sounds like a niche idea but I thought it would be neat too.

**Comment by Jas-SinghFSU** [comment]
This is currently already possible if you go to Configuration > Bar and enable `Map Workspaces to Application Icons`.
![image](https://github.com/user-attachments/assets/19e03ede-3971-4143-904d-31bb9ef99196)

You can define custom icons for the apps in the `App Icon Mappings` field, ex:
```ts
{ "class:kitty$": "󰄛" }
```

And specific colors to workspaces via the `Workspace Icon & Color Mappings` field
```ts
{
    "1": { "color": "#c4a7e7" },
    "2": { "color": "#31748f" },
    "3": { "color": "#eb6f92" },
    "4": { "color": "#c4a7e7" },
    "5": { "color": "#c4a7e7" },
    "6": { "color": "#9ccfd8" },
    "7": { "color": "#c4a7e7" },
    "8": { "color": "#ebbcba" },
    "9": { "color": "#f6c177" },
    "10": { "color": "#c4a7e7" }
}
```

**Comment by amanhex** [comment]
how do i set icon for workspace where no application is launched?

**Comment by paiyayay** [comment]
> This is currently already possible if you go to Configuration > Bar and enable `Map Workspaces to Application Icons`.
> 
> ![image](https://github.com/user-attachments/assets/19e03ede-3971-4143-904d-31bb9ef99196)
> 
> 
> 
> You can define custom icons for the apps in the `App Icon Mappings` field, ex:
> 
> ```ts
> 
> { "class:kitty$": "󰄛" }
> 
> ```
> 
> 
> 
> And specific colors to workspaces via the `Workspace Icon & Color Mappings` field
> 
> ```ts
> 
> {
> 
>     "1": { "color": "#c4a7e7" },
> 
>     "2": { "color": "#31748f" },
> 
>     "3": { "color": "#eb6f92" },
> 
>     "4": { "color": "#c4a7e7" },
> 
>     "5": { "color": "#c4a7e7" },
> 
>     "6": { "color": "#9ccfd8" },
> 
>     "7": { "color": "#c4a7e7" },
> 
>     "8": { "color": "#ebbcba" },
> 
>     "9": { "color": "#f6c177" },
> 
>     "10": { "color": "#c4a7e7" }
> 
> }
> 
> ```

oh my bad... I guess I forgot to look at some updates.
