### ISSUE TITLE
overlay in weather text

### ISSUE THREAD

**Issue by victorballester7** [Jas-SinghFSU/HyprPanel#524]
**Describe the bug**
For certain weather forecasts there is an ovberlay between the description of the phenomena an the icon

**To Reproduce**
Just wait for `Patchy heavy snow` in your city xd.

**Expected behavior**
No overlay, maybe by widening the box or adjusting the text in two lines. 

**Screenshots**
![image](https://github.com/user-attachments/assets/01b71337-5427-4b8d-87d3-4c74e957bc04)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Comment by Jas-SinghFSU** [comment]
Should be resolve with the latest fix.
