### ISSUE TITLE
Low battery notification don't replace $POWER_LEVEL

### ISSUE THREAD

**Issue by DivineMK** [Jas-SinghFSU/HyprPanel#532]
**Describe the bug**
According to #441 $POWER_LEVEL should be replaced by current battery percentage.

**To Reproduce**
Use default settings. Change the threshold to make the notification trigger.

**Screenshots**
![image](https://github.com/user-attachments/assets/00d57c26-f401-45f2-a6da-7938a63c582a)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux 6.11.9-arch1-1
 - Window Manager/Desktop Environment: Hyprland 0.45.2

**Additional context**

**Comment by asakshat** [comment]
On line 238-239. Remove the regex indicator 
`      summary: lowBatteryNotificationTitle.value.replace('/$POWER_LEVEL/g', battery.percent.toString()),
                body: lowBatteryNotificationText.value.replace('/$POWER_LEVEL/g', battery.percent.toString()),
 ` to 
 
 `summary: lowBatteryNotificationTitle.value.replace('$POWER_LEVEL', battery.percent.toString()),
                body: lowBatteryNotificationText.value.replace('$POWER_LEVEL', battery.percent.toString()),
  `

**Comment by DivineMK** [comment]
It works!
