### ISSUE TITLE
ags install failing / install guide confusion

### ISSUE THREAD

**Issue by devdumpling** [Jas-SinghFSU/HyprPanel#536]
[**Describe the bug**
_Unsure whether to post here or in ags repo_

I'm trying to install HyprPanel and have managed to install of the required dependencies on Arch (EndeavourOS)--however, it seems like ags is failing to install repeatedly due to a failing git ref. 

For example, running `yay -S aylurs-gtk-shell` (same problem happens with `aylurs-gtk-shell-git` fails with the following:

```
  -> Creating working copy of astal git repo...
Cloning into 'astal'...
done.
fatal: invalid reference: origin/feat/cava
==> ERROR: Failure while creating working copy of astal git repo
    Aborting...
 -> error making: libastal-cava-git-exit status 1
 -> Failed to install the following packages. Manual intervention is required:
aylurs-gtk-shell - exit status 8
libastal-meta - exit status 8
libastal-cava-git - exit status 1
```

Trying to install libastal-cava-git directly has the same problem. Was a branch renamed or something? Can't find anything else about this. 

**To Reproduce**
`yay -S aylurs-gtk-shell`

**Expected behavior**
Dependencies should install via AUR

**Screenshots**

**Desktop (please complete the following information):**
 - Distribution: EndeavourOS 
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
](url)

Pretty new to Arch/EOS/hyprland--happy to post more logs/debug traces if someone could point me in the right direction.

**Comment by xyzbtw** [comment]
https://hyprpanel.com/getting_started/installation.html#ags-v2

**Comment by devdumpling** [comment]
I see. It wasn't clear to me reading through the install instructions what order to install things in. Based on what's there I assumed it was

- bun
- deps (including ags)
- clone hyprpanl
- run agsv1 install script 

Seems like the correct order is all of the above minus ags?

**Comment by devdumpling** [comment]
ty! all smooth after that

do you think it'd be helpful to add a clarification to the docs while the migration is underway?

**Comment by xyzbtw** [comment]
I mean the clarification is on the website during the installation process, and im not the maintainer so idk

**Comment by devdumpling** [comment]
Thanks for the help. I understand you're not the maintainer and that writing docs is hard. I think I'm not explaining well, nor am I trying to criticize. Let me try to clarify. 

As someone going through reading the install guide for the first time, I experienced it like this:

### Visited [installation](https://hyprpanel.com/getting_started/installation.html#installation)

> HyprPanel has a few dependencies that need to be installed before you can use it. You can find a list of these dependencies below:

Great, cool. Installing deps first makes sense, let's dig in.

### Dependencies

Installed `bun`, move on to [`panel` dependencies`](https://hyprpanel.com/getting_started/installation.html#panel-dependencies)

Immediately notice there's a lot of deps and wonder if there's a yay install for it instead. Look below and see Arch install guide. While I'm scrolling to that I'm presented with a __second reminder__ to install all deps before running HyprPanel.

> WARNING
> HyprPanel will not run without the required dependencies.

At this point I'm starting to double check deps between the install command from AUR and the list. They don't exactly match up, so I think maybe some of the deps here must be included as subdependencies. I run

```sh
yay -S grimblast-git gpu-screen-recorder hyprpicker matugen-bin python-gpustat hyprsunset-git hypridle-git
```

and double check to see what I have/am missing still. I install that except for AGS because at this point I see the note about AGSv2 and the steps. 

This is the first time in the install guide of any mention of cloning Hyprpanel. It's at this point that I'm beginning to question whether I'm missing something. I backed up and read through the whole guide again.

### Running HyprPanel

On rereading, I see this section and it starts to click a bit that there's some necessary setup scripts within the Hyprpanel repo.

> Once you've installed the dependencies, you must put the contents of the HyprPanel repository in your ~/.config/ags directory. The command to do this is provided below

This is the first time (I think??) there's any mention of actually installing Hyprpanel itself. We see _a third reminder that dependencies should already be installed. To me, this implies AGS as well.

### Backing up

At this point there are two competing claims. On one hand there's the multiple reminders to install all the deps _before_ proceeding with Hyprland itself. On the other, there's the callout about using the install script to make AGSv1. 

Now maybe this is where I was being dumb, but I decided to just try installing AGS and seeing what would break. I did this and was surprised I couldn't even get the install to work period. Then I came here to try and search and see if I was missing something and filed an issue before finally trying to make v1 directly. 

So, the install process _does clarify_ what needs to be done, but it's a little all over the place IMO. I know writing docs is hard and am guessing it's just in flux. My suggestion (and PR potentially) would be to simply clarify the state of the migration and the install process at the top / clarify the relationship of the dependencies/AGS and Hyprpanel earlier. 

If someone can point me in the direction of the docs, I'd love to fork a suggestion.

**Comment by xyzbtw** [comment]
https://github.com/Jas-SinghFSU/hyprpanel-docs
I'm pretty sure it's this, understandable that it was confusing
