### ISSUE TITLE
Add adjustable or scalable top/bottom widget padding

### ISSUE THREAD

**Issue by smathles** [Jas-SinghFSU/HyprPanel#55]
**Le Problemo?**
When I use different font sizes to scale hyprpanel appropriately, the padding between the bar's widgets and the top and bottom of the black panel background seems to stay consistent/very similar across all scaling, instead of scaling with the bar.

Now that I've tried scaling hyprpanel down, the top/bottom padding of the bar widgets seems aesthetically too big but there is no customisation option.

**Solution? Maybe?**
To solve this, I would propose either adding a 'top/bottom' padding customisation option in Configurations > Bar OR making the top/bottom gap scale up and down appropriately.

**Pics**
60ish% Scaling: Top/bottom gap way bigger than inter-widget spacing.
![40ish%](https://github.com/user-attachments/assets/e61f56e6-9f2e-47e9-861e-a6ce0caea727)

200ish% Scaling: Top/bottom gap similar to inter-widget spacing.
![200ish%](https://github.com/user-attachments/assets/dd96e98b-3c42-463b-9300-6f33dca24de9)

400ish% Scaling: Top/bottom gap way smaller than inter-widget spacing.
![400%](https://github.com/user-attachments/assets/ba6fe312-5b7b-4549-bd2a-9aa55050efcb)

Among these three screenshots, the gap between the top/bottom of each widget seemingly stays (approximately) the same, despite much change in scaling (to the point where the margins between widgets are either larger or smaller than the top/bottom gaps depending on the current scaling settings).

**Mmmm, Anything Else?**
Maybe less related to this issue, but I'd love to have the option for non-floating bars to set the black background to transparent (sort of floating? but not really floating). If this option were selected, the above issue would become largely irrelevant, but this probably isn't worth making a separate issue over.

**Comment by Jas-SinghFSU** [comment]
@smathles I'll fix the padding issue but you can go to Configuration > Bar and make it transparent.

**Comment by smathles** [comment]
Oh dang didn't realise it was already a thing, sorry. Cheers for letting me know!

**Comment by smathles** [comment]
@Jas-SinghFSU I believe commit 830de04b145eac4dcffade17b508eed1f59a56b2 has solved this issue completely (y-padding option is now present), happy to have it marked as solved unless there's additional elements you were planning?
![image](https://github.com/user-attachments/assets/f209f280-cdc3-4e4f-b12e-f3d59a7b3cfe)
