### ISSUE TITLE
Readme unchanged 

### ISSUE THREAD

**Issue by isquack** [Jas-SinghFSU/HyprPanel#566]
Just a simple question,
Astal branch was merged to main but the readme still says migrating to astal

Shouldn't it be changed?

Also nixpkgs doesn't seem to have agsv2 or astal.will there be any issues with using nixos?

It's fine if you close this issue after answering since I may forget to close it

**Comment by Jas-SinghFSU** [comment]
Oops, forgot to update the readme. Nix is being worked on by @orangci right now, should be good SoonTM.
