### ISSUE TITLE
OBS in vertical position looks weird in AGS v2

### ISSUE THREAD

**Issue by davfsa** [Jas-SinghFSU/HyprPanel#571]
**Describe the bug**
After upgrading to Ags V2, the OBS in the vertical direction looks different from before AGS v2. If intended, then it would be nice to have a way to have the old OBS 

**To Reproduce**
Migrate config to Ags V2 and trigger the obs.

**Expected behavior**
See screenshots bellow

**Screenshots**
| New | Old |
------|-----|
| ![image](https://github.com/user-attachments/assets/d7a0fd89-9b43-4826-9c34-00d89cb244dc) | ![image](https://github.com/user-attachments/assets/7fc339d0-7732-41f8-98c6-f035ae338e87)

**Desktop:**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment:  Hyprland

**Additional context**
N/A

**Comment by myamusashi** [comment]
```
if (currentOrientation === 'vertical') {
                        return (
                            <box vertical>
                                <OSDLabel />
                                <OSDBar orientation={currentOrientation} />
                                <OSDIcon />
                            </box>
                        );
                    }
```
