### ISSUE TITLE
agsv2: The progress bar keeps running even when the video is paused

### ISSUE THREAD

**Issue by myamusashi** [Jas-SinghFSU/HyprPanel#573]
**Describe the bug**
progress bar is still going when the video is paused

**To Reproduce**
Watch any youtube video

**Screenshots**
https://github.com/user-attachments/assets/57a208e7-5b9a-4ea4-89fe-a1c8e2b4fcce

**Desktop (please complete the following information):**
 - Distribution: [e.g. Arch Linux]
 - Window Manager/Desktop Environment: [e.g. Hyprland]

**Comment by Jas-SinghFSU** [comment]
This is an issue with firefox's bad implementation of MPRIS.
You can verify this if you run the following command to get a list of all players:
```
playerctl -l
```
Then find the firefox instance's name. Ex: `firefox.instance###`

Then you can get the current position of the player via:
```
playerctl --player=firefox.instance### position
```

Notice that every time you input that command, the position keeps going up, even while paused.

**Comment by myamusashi** [comment]
Alr, thank you
