### ISSUE TITLE
Media auto-hide doesnt properly detect when media is playing

### ISSUE THREAD

**Issue by davfsa** [Jas-SinghFSU/HyprPanel#574]
**Describe the bug**
I am unsure on what is the cause for this, but when I play any type of media and have "Auto hide" turned on for the media component in the bar, it will stay hidden even if media is playing, no matter what happens.

In my case, killing spotify and re-opening it, pausing/resuming the media player will not cause it to appear.

The only case I have found to fix this is to disable auto hide, but I am quite fond of it.

**To Reproduce**
1. Launch hyprpanel with the media component in the bar and "Auto hide" on
2. Play media from any source (I have tried both Spotify and Youtube through Firefox)
3. Notice that the media component doesn't show

**Expected behavior**
Autohide works as expected

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
N/A

**Comment by davfsa** [comment]
For what its worth, this was not the case before ags v2

**Comment by Jas-SinghFSU** [comment]
Fixed in #588
