### ISSUE TITLE
Low battery notification is not sent

### ISSUE THREAD

**Issue by davfsa** [Jas-SinghFSU/HyprPanel#575]
**Describe the bug**
The low battery notification is not sent when battery drops bellow the limit

**To Reproduce**
1. Enable low battery notification
![image](https://github.com/user-attachments/assets/489ce90c-c228-4d3f-9654-b8b9ad3e799e)
2. Wait for the battery to drop under that level
3. Notice no notification is sent

There are quite bad reproduction steps, but if needed I can gather and post more information :)

**Expected behavior**
Notification is sent when battery drops under threshold.

**Screenshots**
N/A

**Desktop:**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
This happened before ags v2 migration, but I waited to report it until the migration was complete. It unfortunately still happens

**Comment by davfsa** [comment]
Tracked this down, working on a fix!

**Comment by smathles** [comment]
I believe the $BATTERY_LEVEL or whatever the variable name is was also broken (would return "$BATTERY_LEVEL" instead of "15%" or whatever)... LMK if it works for you if you get this fixed!

**Comment by davfsa** [comment]
> I believe the $BATTERY_LEVEL or whatever the variable name is was also broken (would return "$BATTERY_LEVEL" instead of "15%" or whatever)... LMK if it works for you if you get this fixed!

Yep, noticed that too! Have a look at the linked pr, it should fix all the issues!

**Comment by smathles** [comment]
Dang dude, that looks fire! Keen for this :muscle:
