### ISSUE TITLE
Clock module (Time & Weather) doesn't respond to settings changes

### ISSUE THREAD

**Issue by chikobara** [Jas-SinghFSU/HyprPanel#578]
**Describe the bug**
The clock module settings isn't responding by any change in the settings.

**To Reproduce**
I wanted to hide the seconds and use the 24Hr time mode, but whatever I change in the hyprpanel settings in the clock section it doesn't affect at all, even the weather settings 

![image](https://github.com/user-attachments/assets/80f32067-e820-4786-9f85-220977d2beec)
**Desktop (please complete the following information):**
 - Distribution: Arch Linux(EOS)
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
note that this bug was even before migrating to astal/ags2, I didn't report waited to the migration release.

**Comment by chikobara** [comment]
but the clock seconds and time mode cant switch too

**Comment by davfsa** [comment]
Good point, will have a look since I already invested the code a bit

**Comment by OneGraund** [comment]
What also doesn't seem to work properly is the "Units" boolean in Weather. Pasting API key triggers a change to different city/country, but not unit change
