### ISSUE TITLE
OSD doesn't follow cursor

### ISSUE THREAD

**Issue by myamusashi** [Jas-SinghFSU/HyprPanel#580]
**Describe the bug**
The OSD always appears on the first monitor, not on the second monitor, even if the cursor is on the second monitor

**To Reproduce**
Trigger any OSD

**Expected behavior**
The OSD will show which monitor the cursor is on

**Desktop (please complete the following information):**
 - Distribution: [e.g. Arch Linux]
 - Window Manager/Desktop Environment: [e.g. Hyprland]

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the getOsdMonitor function to determine the current monitor based on the cursor position. This ensures that the OSD appears on the monitor where the cursor is located.

You can review changes in this commit: https://github.com/wwqwq2313/Jas-SinghFSU-HyprPanel-580/commit/0df2d71844f0d8bee0f7953aec91f0a73174f1ab.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by myamusashi** [comment]
I fixed it with this
```
export const getOsdMonitor = (): Binding<number> => {
    return Variable.derive(
        [bind(hyprlandService, 'focusedMonitor'), bind(monitor), bind(active_monitor)],
        (focusedMonitor, defaultMonitor, followMonitor) => {
            if (followMonitor === true) {
                return focusedMonitor.id;
            }

            return defaultMonitor;
        },
    )();
};
```
There might be a better way to fix it, but idk.
