### ISSUE TITLE
Wifi List is not scrollable

### ISSUE THREAD

**Issue by paridhi089** [Jas-SinghFSU/HyprPanel#590]
### Description
When there are many wifi networks, the list becomes too long and overflows the screen real estate.

### Steps to reproduces
This is a bit tricky to reproduce. it entirely depends on the area  you live in.  You will need a lot of wifi networks near you. 
1. click on the network icon and turn on wifi

### Expected behavior
When you click on the network module, the popup menu should not exceed the screen real estate.  It would be ideal if the popup menu has a max height to about 50-60% of the screen height and the list of wifi networks should be scrollable

### Screenshot
![bug](https://github.com/user-attachments/assets/a9aeeb76-05d6-4a85-9396-ad68268fd2ed)

I had blurred the SSIDs for privacy reasons

### Desktop
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland
 -  Screen Resolution: 1920x1080

**Comment by Jas-SinghFSU** [comment]
My lord, that's a lot of networks man.

**Comment by Jas-SinghFSU** [comment]
Side question, are your icon colors blended into the background?

**Comment by paridhi089** [comment]
> Side question, are your icon colors blended into the background?

yes It was blended. Now  i am using Matugen. I think this ss is from when i was playing with the top bar and i selected split style

**Comment by Jas-SinghFSU** [comment]
Oh, nice! Wasn't sure if there was a bug or something. Good to know!

**Comment by paridhi089** [comment]
> Oh, nice! Wasn't sure if there was a bug or something. Good to know!

It was probably a bug with one of the  builtin themes. I will check it if i get time.
