### ISSUE TITLE
Inconsistent network sthrength icon indicator for connected network

### ISSUE THREAD

**Issue by davfsa** [Jas-SinghFSU/HyprPanel#594]
**Describe the bug**

**To Reproduce**
A bit uncertain, but it seems to be caused when there are multiple (if its just one, then it seems to work) networks on the list and you are connected to one of them

**Expected behavior**
Consistent network strength indicator

**Screenshots**
Notice the icon discrepancy between the menu bar and the one on the list
![image](https://github.com/user-attachments/assets/0aad5e6c-c2e5-465d-81fd-c2e94f367bed)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
N/A

**Comment by davfsa** [comment]
This seems to be not really a hyprpanel issue, but more to do with whatever is reporting the strength of the wifi access, as they are sending incorrect information
![image](https://github.com/user-attachments/assets/8ef75634-c14b-49c4-812a-c19c17f922f9)

**Comment by davfsa** [comment]
Ok, this seems like just an astral issue, as it seems to believe that the strength is lower than it actually is.

I will file an issue with them, but I have no clue what could be the issue here.

Sorry for the noise! Should have investigated it a bit further earlier. I didnt expect to reach a dead-end so quickly

**Comment by Jas-SinghFSU** [comment]
@davfsa Can you ensure that Astal is matching what networkmanager is giving it?

Run this command and see what network manager is recognizing as the strength of the wifi network:
```
nmcli device wifi list
```
