### ISSUE TITLE
Notifications do not persist in the notification area. After the toast goes away.

### ISSUE THREAD

**Issue by onefish2** [Jas-SinghFSU/HyprPanel#596]
**Describe the bug**
Notifications do not persist in the notification area. After the toast goes away. The notification does not move to the notification area.

**Expected behavior**
Notifications should move from the toast into the notification area and show a number next to the bell icon.

**Desktop (please complete the following information):**
 - Distribution: Arch
 - Window Manager/Desktop Environment: Hyprland

**Comment by Jas-SinghFSU** [comment]
Are you by chance dismissing them during the toast?

**Comment by onefish2** [comment]
No. The notification toast times out and then nothing is incremented or displayed in the notification area.

**Comment by Jas-SinghFSU** [comment]
Could you share your config please?

Settings > Configuration > General > Export

Make sure to remove your weather API key if you have it.

**Comment by onefish2** [comment]
Attached.
[hyprpanel_config.json](https://github.com/user-attachments/files/18223253/hyprpanel_config.json)

**Comment by Jas-SinghFSU** [comment]
I'm not able to replicate this. Is this happening with all notifications? Even if you do a `notify-send test` in the CLI.

**Comment by onefish2** [comment]
I just tried with notify-send. That works. What was not working was the notification after I saved the config file from the Hyprpanel settings export. Try exporting your config and let the toast expire. Shouldn't that notification go into the notification area?

**Comment by Jas-SinghFSU** [comment]
There was a hard timeout set on most notifications originating from HyprPanel. I've removed those as they're redundant and cause notifications to dismiss.

Should be good now.

**Comment by onefish2** [comment]
Ty for your quick replies and help. I love Hyprpanel. Thank you for your time and effort.
