### ISSUE TITLE
Critical: Volume Module on the bar can be overamplified  infinitely. 

### ISSUE THREAD

**Issue by paridhi089** [Jas-SinghFSU/HyprPanel#616]
### Description
Scrolling on the Volume module can infinitely increase volume percentage. 

### How to reproduce
Scroll on the volume module indefinitely to increase the volume to a very high percentage.

### Expected behavior
If overamplification is enabled, volume should cap at 150% or if it is not enables, it should be capped at 100%

### Screenshots
![swappy-20241224-182131](https://github.com/user-attachments/assets/6e149681-a0aa-4d75-b64c-cb25dd16be0c)
![swappy-20241224-182144](https://github.com/user-attachments/assets/316eabb9-ce01-4101-813f-7622c229acae)

### Desktop
 - Distribution: Arch
 - Window Manager/Desktop Environment: Hyprland
 -  Pipewire

### Additional context
The reason this is critical is because I have had instances where I have damages laptop speakers by over amplifying it to 150%.

**Comment by Jas-SinghFSU** [comment]
Added a new command to adjust volume based on hyprpanel settings. Caps volume to 100% or 150% (if overamplification is enabled).

Please make sure to reset your scroll up/down settings in Configuration > Bar > Volume > Scroll Up/Down to make sure that the new command is used. Simply click the reset icon next to the text field of both of these settings.

![image](https://github.com/user-attachments/assets/128f14a9-9dd1-42e8-9864-df9ba74c5510)

**Comment by paridhi089** [comment]
This is perfect thanks
