### ISSUE TITLE
AGS not respecting libnotify convention

### ISSUE THREAD

**Issue by greeid** [Jas-SinghFSU/HyprPanel#62]
**Describe the bug**
When using `swaync` a notification can be overridden using "synchronous" hint to to create a "confirmation" notification that will replace previous confirmation notifications. For example:
```bash
notify-send "Message" -h string:x-canonical-private-synchronous:anything
``` 
and doing 
```bash
notify-send "Message1" -h string:x-canonical-private-synchronous:anything
```
will replace "Message" with "Message1", IDK if this is expected behavior or not but AGS notification doesn't follow said convention

**To Reproduce**
- Install `swaync` and execute it 
- Try running : `notify-send "Message" -h string:x-canonical-private-synchronous:anything` and `notify-send "Message1" -h string:x-canonical-private-synchronous:anything` 
- The "Message" will be overridden by "Message1" but doesn't happen in AGS

**Expected behavior**
Previous notification with same `ID` be overridden instead of shown in different notification

**Screenshots**

https://github.com/user-attachments/assets/c585ddd9-6346-49e9-9b27-fc6db57b5279

**Desktop (please complete the following information):**
 - Distribution: EndeavourOS
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
None

**Comment by Jas-SinghFSU** [comment]
Similarly to my comment [here](https://github.com/Jas-SinghFSU/HyprPanel/issues/13#issuecomment-2254338349), you can should be able to achieve this my using the -r flag. The -r flag will prevent notifications from the same id from showing up multiple times; instead they'll be overwritted.

**Comment by greeid** [comment]
Cool, thanks
