### ISSUE TITLE
Add a scaling Priority option to the Home Manager module

### ISSUE THREAD

**Issue by DockterTeagle** [Jas-SinghFSU/HyprPanel#627]
**Is your feature request related to a problem? Please describe.**
currently (to my knowledge) there is no way to manage scaling priority in home Manager
**Describe the solution you'd like**
Either a home manager option or an extra option like .text that allows us to write things that are ommited from the module

**Describe alternatives you've considered**
Not using homeManager module at all

**Additional context**

**Comment by DockterTeagle** [comment]
on an unrelated note I am having the issue where home-manager seems to not  be writing to ~/.config/hyprpanel at all

**Comment by kjurl** [comment]
have you tried `overwrite.enable = true;`?

**Comment by benvonh** [comment]
You should show your module config... it helps a lot.

Also, I added scaling priority - https://github.com/Jas-SinghFSU/HyprPanel/pull/628
