### ISSUE TITLE
feat(nix): add theme settings to nix module

### ISSUE THREAD

**Issue by emsquid** [Jas-SinghFSU/HyprPanel#632]
As of now the only way to set a theme through the new hyprpanel nix module is with predesigned theme, it would be great if all options were added to settings ! @benvonh

**Comment by benvonh** [comment]
Can you try my fork? Option is `override = {}`

```nix
{
  inputs = {
    hyprpanel.url = "github:benvonh/hyprpanel";
  };
  # ...
}
```
```nix
{ inputs, ... }:
{
  # ...

  programs.hyprpanel = {
    # ...
    override = {
      theme.bar = {
        buttons.media = {
          text = "#123456";
          icon = "#987654";
        };
        menus.text = "#123ABC";
      };
    };
  };
}
```

**Comment by emsquid** [comment]
Yeah that seems like a good temporary fix for now !!
I tried the same on my own and it seems to work :+1:

**Comment by benvonh** [comment]
https://github.com/Jas-SinghFSU/HyprPanel/pull/633

**Comment by benvonh** [comment]
You can close this
