### ISSUE TITLE
Missing argument for -t

### ISSUE THREAD

**Issue by lolpowerluke** [Jas-SinghFSU/HyprPanel#635]
**Describe the bug**
Opening settings dialog doesnt work anymore
yesterday or the day before, I could do `hyprpanel -t settings-dialog` and the settings panel would launch

**To Reproduce**
run `hyprpanel -t settings-dialog`
see error as in titel

**Expected behavior**
open settings-dialog

**Screenshots**
![image](https://github.com/user-attachments/assets/ac6844cd-867f-45cb-b3e5-b5d4cc7ebae1)

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
fastfetch output
![image](https://github.com/user-attachments/assets/7f312022-2179-4a24-a1d3-254bf3f7a172)

**Comment by Jas-SinghFSU** [comment]
It's 'hyprpanel t settings-dialog' now. Before it was using AGS commands but hyprpanel after migrating to astal uses it's own CLI commands.

You can view them via 'hyprpanel explain'

**Comment by lolpowerluke** [comment]
I see ty
