### ISSUE TITLE
Config Gets Deleted on Syntax Error

### ISSUE THREAD

**Issue by alexankitty** [Jas-SinghFSU/HyprPanel#639]
**Describe the bug**
If there is a syntax error in the JSON, the config gets wiped.

**To Reproduce**
1. Forget a comma in your JSON when editing it.
2. Restart the panel.
3. Watch the panel load with defaults
4. Go look at the config to see that it's been replaced by:
```json
{
  "bar.customModules.updates.pollingInterval": 1440000
}
```

**Expected behavior**
Config shouldn't be overwritten, and instead if there is a config error, the config error should be presented to the user so they have a chance to fix it without losing their config.

**Desktop (please complete the following information):**
 - Arch Linux
 - Hyprland

**Comment by Jas-SinghFSU** [comment]
closed by #640
