### ISSUE TITLE
Use/add-option to use hyprPaper instead of swww

### ISSUE THREAD

**Issue by soymadip** [Jas-SinghFSU/HyprPanel#668]
**Is your feature request related to a problem? Please describe.**
the bar is for hyprland. so why use swww. its better to stick in hypr ecosystem

**Describe the solution you'd like**
use hyprpaper to set wallpaper. or have option to use it instead

**Describe alternatives you've considered**
i am using hyprpaper. that is not supported by hyprpanel

**Comment by benvonh** [comment]
Sorry, ima have to defend this: just because it has hypr in its name, doesn't mean it's better with Hyprland.


anyway, did you want hyprpanel to do you wallpaper? like for the matugen colors? if not, it'd be easier to disable wallpaper and just use hyprpaper separately for now

**Comment by paridhi089** [comment]
> Sorry, ima have to defend this: just because it has hypr in its name, doesn't mean it's better with Hyprland.
> 
> anyway, did you want hyprpanel to do you wallpaper? like for the matugen colors? if not, it'd be easier to disable wallpaper and just use hyprpaper separately for now

the recent patch i submitted should allow one to use ` hyprpanel setWallpaper  `  to set matugen theme for both hyprpanel and any other apps specified in matugen.
