### ISSUE TITLE
Bar size changes with "underline" Workspace highlight and changing monitor focus

### ISSUE THREAD

**Issue by matavach** [Jas-SinghFSU/HyprPanel#72]
**Describe the bug**
The underline workspace highlight adds a bit of padding to the bar height, which is fine, however, when the monitor that's highlight loses focus, the highlight dissapears and the whole bar shrinks back. It's a bit hard to see in screenshots, but is very noticeable when the hyprland windows readjust to the new bar size.

![image](https://github.com/user-attachments/assets/fe60d44f-b1a7-4658-9a17-51795f2f8626)
![image](https://github.com/user-attachments/assets/c75c9c32-9890-454e-9166-2dedc6a40256)

This could be fixed by changing the bar to not flex its size when its not being highlighted, however, I would like to rework the way workspaces are highlighted to allow for highlights to appear on all active monitors.

**Comment by Jas-SinghFSU** [comment]
Couldn't replicate it and added a fix for the underline pushing the number up a little bit in the related MR. Feel free to reopen this if you're still seeing the issue.
