### ISSUE TITLE
Widgets become unresponsive and Keyboard loses focus after two clicks

### ISSUE THREAD

**Issue by Shubham-550** [Jas-SinghFSU/HyprPanel#91]
**Describe the bug**

After two left mouse button (LMB) clicks on the widgets:
1. The widgets do not respond to subsequent LMB clicks when the mouse does not move.
2. The keyboard loses focus of the window even after clicking on it.

**To Reproduce**

1. Click on any widget more than twice without moving the mouse; the widgets will stop responding.
2. Click on any widget more than twice and then switch to another window; the keyboard will not work.

**Expected behavior**
Widgets should respond to all left mouse button (LMB) clicks, regardless of mouse movement. Additionally, the keyboard should retain focus on the window after clicking on it.

**Desktop (please complete the following information):**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
RMB do not have this problem.

**Comment by matavach** [comment]
I actually had a similar issue before
Are you using any virtual input services (ydotool) etc?
Do you have any hyprland keybinds with "bindl"

I found those to be the cause of my issue.

**Comment by Jas-SinghFSU** [comment]
Is there a specific widget causing this? I can't seem to replicate it give your steps to reproduce. I see that the menus don't close if you don't move your mouse however.

**Comment by Shubham-550** [comment]
> I actually had a similar issue before Are you using any virtual input services (ydotool) etc? Do you have any hyprland keybinds with "bindl"
> 
> I found those to be the cause of my issue.


I found `xdotool` but deleting it and after restarting still issue is there. I don't know anything about those services.
There is no `bindl` keybind in the config.

 
> Is there a specific widget causing this? I can't seem to replicate it give your steps to reproduce. I see that the menus don't close if you don't move your mouse however.

It is happening on all the widgets.

In the attached video, the cursor was blinking but after two clicks on the widget the cursor blinking stop. 

https://github.com/user-attachments/assets/b5960a38-b30f-4b4c-b71b-6afbc653fd96

**Comment by Jas-SinghFSU** [comment]
Hmm, the menu that is spawned when you click a module listens to keypress events, which is probably why you're losing focus; it's listening for input - escape specifically to close the menu. My question is, when you click back on the window, does it restore the focus? Are you saying that you don't want the focus to get lost when clicking menus or that the focus can't be regained once lost?

If it's the former then that's an easy fix: we implement the ability to disable key press events for menus. If it's the latter then I'll need some more info since I can't seem to replicate this behavior with the same steps you did in the video.

**Comment by Shubham-550** [comment]
> when you click back on the window, does it restore the focus?
No

> Are you saying that you don't want the focus to get lost when clicking menus or that the focus can't be regained once lost?
Focus can't be regained unless I move the window or mouse crosses to another window and move back.

**Comment by Jas-SinghFSU** [comment]
Could you checkout branch `menu_layer` and try 2 things:
1. See is the issue still persists (I've changed the layer from 'top' to 'overlay' for menus)
2. Go to Settings > Configuration > General and Disable 'Escape To Close Menus' and see if it still persists

**Comment by Shubham-550** [comment]
> Could you checkout branch `menu_layer` and try 2 things:
> 
>     1. See if the issue still persists (I've changed the layer from 'top' to 'overlay' for menus)
> 
>     2. Go to Settings > Configuration > General and Disable 'Escape To Close Menus' and see if it still persists

This works.

>  I see that the menus don't close if you don't move your mouse however.

This is happening in this branch.

**Comment by Jas-SinghFSU** [comment]
Did the branch work out of the box or did step 2 make it work for you?

As for the clicks not registering if mouse doesn't move at least one pixel, it seems that it's either an AGS or GTK issue :(. I'll have to dig in to find out which ones the culprit and open a issue.

**Comment by Shubham-550** [comment]
Step 2 make it work.

**Comment by Jas-SinghFSU** [comment]
With step 1 only. Is the behavior 100% the same?
Also would it be possible for you to share your hyprland config?

**Comment by Shubham-550** [comment]
> With step 1 only is the behavior 100% the same?

yes

> Also would it be possible for you to share your hyprland config?
yes. I will edit it in few mins for the github config link

**Comment by Jas-SinghFSU** [comment]
I was able to pull your configuration into my environment but can't seem to replicate the issue. The moment I close the menu, I can bring focus right back to the window with no issues.

**Comment by Jas-SinghFSU** [comment]
@Shubham-550 Is this still an issue for you? I'm still trying to find a way to replicate it, haven't forgotten about this.

**Comment by Shubham-550** [comment]
> As for the clicks not registering if mouse doesn't move at least one pixel, it seems that it's either an AGS or GTK issue :(. I'll have to dig in to find out which ones the culprit and open a issue.

Did you find a solution regarding this?

And second issue is resolved. Thank you.

**Comment by Jas-SinghFSU** [comment]
> Did you find a solution regarding this?
Unfortunately not :( 
Seems like some Gtk funyness when it comes to event boxes. I'll keep a lookout for a fix.

Are you using my custom branch for your fix to the second issue or is master branch working fine for you now?

**Comment by Shubham-550** [comment]
I am using menu_layer branch.

**Comment by Jas-SinghFSU** [comment]
Gotcha, issue there is that since no key press events are passed through, you can enter your wifi password :(

**Comment by smathles** [comment]
I'm also experiencing this issue.
On mouse hover over any widget it changes colour (focused on that widget), click (opens widget menu, colour changes back [indicating focus lost?]), click again (close widget menu), don't move mouse a single pixel and click again (no result, as the colour/focus was lost in after first click).

Could be an ags issue, I've got no idea. Might just be useful to add my experience + 2 cents.

**Comment by Jas-SinghFSU** [comment]
This apparently is related to AGS and Hyprland. Few people have reported that they see the same behavior (outside of Hyprpanel) with their AGS configs but not on other Compositors. 

I'll keep a lookout for news on this.

**Comment by Jas-SinghFSU** [comment]
Closing since stale

**Comment by andradei** [comment]
They new version made hyprpanel snappier, it starts much faster at startup too.
This is issue seems to be gone too.
🎉

**Comment by smathles** [comment]
Interesting! I'll have to test this in a minute, (it's my most desired feature lmao).

**Comment by smathles** [comment]
Tested, unfortunately it's still present in the majority of cases.

However, one case now works when it didn't before!
After clicking a button:
- Clicking the same button (WITHOUT moving mouse) now toggles the dropdown menu/whatever successfully once (it didn't before IIRC)!
- Clicking a different button while the dropdown menu/whatever is open closes the menu successfully.
    - subsequent clicks on that same button will still open and close the menu successfully once
- However, repeated efforts to toggle a button without moving the mouse will still fail (click once, open; click twice, close; click three times, failure).

So it's somewhat improved (first toggle works now), but still a bit to go yet.

Any progress is good progress!
