### ISSUE TITLE
Misaligned icons

### ISSUE THREAD

**Issue by ashraddhansh** [Jas-SinghFSU/HyprPanel#96]
Some icons are misaligned 
![20240808_16h42m02s_grim](https://github.com/user-attachments/assets/00a40633-5dae-4661-939e-76c79ca0f83e)
![20240808_16h42m31s_grim](https://github.com/user-attachments/assets/a65f0bf6-0849-4b15-9d28-3ee8b9985c48)
![20240808_16h44m39s_grim](https://github.com/user-attachments/assets/cf4114e8-067a-4271-a3c5-9fecfd6a2762)
**Fonts I had installed in my system are**:
1. nerd-fonts-symbol
2. jetbrains mono
3. firacode nerd font
Distro is arch. Should I need to install whole 8GB nerd-fonts group package or is there any other solution?

**Comment by Jas-SinghFSU** [comment]
I think the solution here might be to require a certain font for icons as @matavach suggested. The only solution I've found is to pick a font that aligns them well. I'll go ahead and get started on replacing these nerdfont icons with real icons later today since they don't seem to have issues.

**Comment by matavach** [comment]
@Jas-SinghFSU I plan on tackling the icons tonight. Don't want us doing double work.

**Comment by ashraddhansh** [comment]
It is fixed now. All the icons working well with jetbrains mono which I haven't selected in bar general settings earlier.

**Comment by dringwald** [comment]
Just to add: I had this same issue and it was solved by choosing the "propo" / proportional nerdfont option.

**Comment by matavach** [comment]
Interesting. I would have expected propo to do the opposite

**Comment by Jas-SinghFSU** [comment]
JetBrainsMono Nerd Font Propo seems to be a font that works extremely well with NerdFonts in terms of alignment. It's also a clean looking font so until we normalize nerdfont icon fonts, anyone stumbling upon the same issue can use that font instead.
